// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum CCSPlayerAnimationState__AirAction_t : byte
{
    None = 0,
    Jump = 1,
    StartFall = 2,
    Land = 3,
}
