// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum CCSPlayerAnimationState__GroundMoveState_t : byte
{
    None = 0,
    Idle = 1,
    Start = 2,
    Move = 3,
    TurnOnSpot = 4,
    TurnOnSpotLoop = 5,
    PlantAndTurn = 6,
}
