// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum CCSPlayerAnimationState__MoveType_t : byte
{
    None = 0,
    Ground = 1,
    Air = 2,
    Ladder = 3,
}
