// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum ChoreoExternalAnimgraphControlState_t : uint
{
    eNone = 0,
    eBegin = 1,
    eLooping = 2,
    eExit = 3,
    eAbort = 4,
    eCount = 5,
}
