// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum CInfoChoreoLocatorShapeType_t : uint
{
    POINT = 0,
    LINE = 1,
    COUNT = 2,
    NONE = 3,
}
