// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum CNmEventTargetEntity_t : uint
{
    Self = 0,
    Weapon = 1,
    HeldItem = 2,
    Custom = 3,
}
