// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum CNmTargetWarpNode__TargetUpdateRule_t : byte
{
    None = 0,
    Recalculate = 1,
    Offset = 2,
    RecalculateOrOffset = 3,
}
