// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum FuncMoverMovementSummaryFlags_t : uint
{
    eNone = 0,
    eMovementBegin = 1,
    eStopBegin = 2,
    eStopComplete = 4,
    eReversing = 8,
    eEventsDispatched = 16,
}
