// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum GPUParticleCollisionMode_t : uint
{
    PARTICLE_GPU_COLLISION_MODE_RT = 0,
    PARTICLE_GPU_COLLISION_MODE_DEPTH = 1,
    PARTICLE_GPU_COLLISION_MODE_HYBRID = 2,
}
