// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum InteractionPassive_t : uint
{
    INTERACT_PASSIVE_NONE = 0,
    INTERACT_PASSIVE_LOOKAT = 1,
    INTERACT_PASSIVE_SPEAK = 2,
}
