// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum ParticleMultiSegmentCountSelection_t : uint
{
    PARTICLE_MULTISEGMENT_SEG_COUNT_7 = 7,
    PARTICLE_MULTISEGMENT_SEG_COUNT_14 = 14,
    PARTICLE_MULTISEGMENT_SEG_COUNT_16 = 16,
}
