// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum ParticleMultiSegmentInputSelection_t : uint
{
    PARTICLE_MULTISEGMENT_SELECTION_FLOAT = 0,
    PARTICLE_MULTISEGMENT_SELECTION_STRING = 1,
}
