// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum ParticleToolsState_t : uint
{
    PARTICLE_TOOLS_STATE_ALWAYS_ON = uint.MaxValue,
    PARTICLE_TOOLS_STATE_TOOLS_ONLY = 0,
    PARTICLE_TOOLS_STATE_GAME_ONLY = 1,
}
