// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum ParticleVolumetricSmokeCreationType_t : uint
{
    PARTICLE_VOLUMETRIC_SMOKE_TYPE_CONTINUOUS = 0,
    PARTICLE_VOLUMETRIC_SMOKE_TYPE_IMPULSE = 1,
}
