// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum ParticleMultiSegmentSpecialCharacter_t : uint
{
    PARTICLE_MULTISEGMENT_SPECIAL_NONE = uint.MaxValue,
    PARTICLE_MULTISEGMENT_SPECIAL_DECIMAL = 0,
    PARTICLE_MULTISEGMENT_SPECIAL_COLON = 1,
    PARTICLE_MULTISEGMENT_SPECIAL_DEGREES = 2,
}
