// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum ParticleVolumetricSmokeType_t : uint
{
    PARTICLE_VOLUMETRIC_SMOKE_TYPE_EMISSION = 0,
    PARTICLE_VOLUMETRIC_SMOKE_TYPE_SINK = 1,
    PARTICLE_VOLUMETRIC_SMOKE_TYPE_REPEL = 2,
}
