// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum PhysInterfaceId_t : uint
{
    PIID_UNKNOWN = 0,
    PIID_IPHYSICSBODY = 1,
    PIID_IPHYSAGGREGATE = 2,
    PIID_IPHYSICSJOINT = 3,
    PIID_IPHYSICSMOTIONCONTROLLER = 4,
    PIID_IPHYSICSPARTICLEROPE = 5,
    PIID_IPHYSICSRAGDOLLCONTROL = 6,
    PIID_NUM_TYPES = 7,
}
