// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum PlayerConnectedState : uint
{
    NeverConnected = uint.MaxValue,
    Connected = 0,
    Connecting = 1,
    Reconnecting = 2,
    Disconnecting = 3,
    Disconnected = 4,
    Reserved = 5,
}
