// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum SndSeqPlayerType_t : uint
{
    eSndSeqPlayerNull = 0,
    eSndSeqPlayerSndEvt = 1,
    eSndSeqPlayerMidiSeq = 2,
}
