// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum SndSeqSyncType_t : uint
{
    eSndSeqSyncTypeNone = 0,
    eSndSeqSyncTypeWait = 1,
    eSndSeqSyncTypeSeek = 2,
}
