// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum SndSeqMidiStatusType_t : uint
{
    SndSeqMidiStatusNoteOff = 8,
    SndSeqMidiStatusNoteOn = 9,
    SndSeqMidiStatusKeyPressure = 10,
    SndSeqMidiStatusCtrlChange = 11,
    SndSeqMidiStatusProgramChange = 12,
    SndSeqMidiStatusChannelPressure = 13,
    SndSeqMidiStatusPitchBend = 14,
}
