// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum SndSeqQuantizeType_t : uint
{
    eSndSeqQuantizeInvalid = uint.MaxValue,
    eSndSeqQuantizeNone = 0,
    eSndSeqQuantizeBeat = 1,
    eSndSeqQuantizeBar = 2,
    eSndSeqQuantizeSequence = 3,
    eSndSeqQuantizeSeek = 4,
    eSndSeqQuantizeReset = 5,
}
