// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum SndSeqTrackPlaybackType_t : uint
{
    eSndSeqTrackPlaybackTypeStep = 0,
    eSndSeqTrackPlaybackTypeFwd = 1,
}
