// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum SndSeqRegionType_t : uint
{
    eSndSeqRegionTypeNull = 0,
    eSndSeqRegionTypeSndEvt = 1,
    eSndSeqRegionTypeMidiSeq = 2,
}
