// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum SndSeqInstrumentType_t : uint
{
    eSndSeqInstNull = 0,
    eSndSeqInstSndEvt = 1,
    eSndSeqInstMidiSampler = 2,
}
