// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum soundcommands_t : uint
{
    SOUNDCTRL_CHANGE_VOLUME = 0,
    SOUNDCTRL_CHANGE_PITCH = 1,
    SOUNDCTRL_STOP = 2,
    SOUNDCTRL_DESTROY = 3,
    SOUNDCTRL_FADEOUT = 4,
}
