// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface AI_BaseNPCAnimGraph_DebugSnapshotData_t : DebugSnapshotBaseStructuredData_t, ISchemaClass<AI_BaseNPCAnimGraph_DebugSnapshotData_t>
{
    static AI_BaseNPCAnimGraph_DebugSnapshotData_t ISchemaClass<AI_BaseNPCAnimGraph_DebugSnapshotData_t>.From(nint handle) => new AI_BaseNPCAnimGraph_DebugSnapshotData_tImpl(handle);
    static int ISchemaClass<AI_BaseNPCAnimGraph_DebugSnapshotData_t>.Size => 40;
    static string? ISchemaClass<AI_BaseNPCAnimGraph_DebugSnapshotData_t>.ClassName => null;


    public ref CGlobalSymbol E_action_desired { get; }

    public ref bool B_action_restart { get; }

    public ref CGlobalSymbol E_movement_type_desired { get; }

    public ref bool B_movement_type_restart { get; }


}