// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface AI_BaseNPC_DebugSnapshotData_t : DebugSnapshotBaseStructuredData_t, ISchemaClass<AI_BaseNPC_DebugSnapshotData_t>
{
    static AI_BaseNPC_DebugSnapshotData_t ISchemaClass<AI_BaseNPC_DebugSnapshotData_t>.From(nint handle) => new AI_BaseNPC_DebugSnapshotData_tImpl(handle);
    static int ISchemaClass<AI_BaseNPC_DebugSnapshotData_t>.Size => 120;
    static string? ISchemaClass<AI_BaseNPC_DebugSnapshotData_t>.ClassName => null;


    public ref CGlobalSymbol Npc_state { get; }

    public ref CHandle<CBaseEntity> Current_enemy { get; }

    public string S_current_schedule { get; set; }

    public ref CGlobalSymbol S_current_task { get; }

    public string S_schedule_interrupt_reason { get; set; }

    public string S_schedule_fail_reason { get; set; }

    public ref CUtlVector<CGlobalSymbol> Conditions { get; }

    public ref CUtlVector<CGlobalSymbol> Anim_events { get; }

    public ref CGlobalSymbol E_action_body_section { get; }

    public ref CGlobalSymbol E_movement_body_section { get; }


}