// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface AI_DefaultNPC_DebugSnapshotData_t__PathQuery_t : ISchemaClass<AI_DefaultNPC_DebugSnapshotData_t__PathQuery_t>
{
    static AI_DefaultNPC_DebugSnapshotData_t__PathQuery_t ISchemaClass<AI_DefaultNPC_DebugSnapshotData_t__PathQuery_t>.From(nint handle) => new AI_DefaultNPC_DebugSnapshotData_t__PathQuery_tImpl(handle);
    static int ISchemaClass<AI_DefaultNPC_DebugSnapshotData_t__PathQuery_t>.Size => 40;
    static string? ISchemaClass<AI_DefaultNPC_DebugSnapshotData_t__PathQuery_t>.ClassName => null;


    public ref CGlobalSymbol InitialQueryName { get; }

    public ref CGlobalSymbol CurrentQueryName { get; }

    public ref CGlobalSymbol Mode { get; }

    public ref CGlobalSymbol Type { get; }

    public ref CGlobalSymbol State { get; }


}