// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface AI_Motor_DebugSnapshotData_t : DebugSnapshotBaseStructuredData_t, ISchemaClass<AI_Motor_DebugSnapshotData_t>
{
    static AI_Motor_DebugSnapshotData_t ISchemaClass<AI_Motor_DebugSnapshotData_t>.From(nint handle) => new AI_Motor_DebugSnapshotData_tImpl(handle);
    static int ISchemaClass<AI_Motor_DebugSnapshotData_t>.Size => 32;
    static string? ISchemaClass<AI_Motor_DebugSnapshotData_t>.ClassName => null;


    public ref CGlobalSymbol Current_movement_gait_set { get; }

    public ref CGlobalSymbol Current_movement_gait { get; }

    public ref CGlobalSymbol Movement_setting_id { get; }


}