// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface AI_MotorGroundAnimgraph_DebugSnapshotData_t : DebugSnapshotBaseStructuredData_t, ISchemaClass<AI_MotorGroundAnimgraph_DebugSnapshotData_t>
{
    static AI_MotorGroundAnimgraph_DebugSnapshotData_t ISchemaClass<AI_MotorGroundAnimgraph_DebugSnapshotData_t>.From(nint handle) => new AI_MotorGroundAnimgraph_DebugSnapshotData_tImpl(handle);
    static int ISchemaClass<AI_MotorGroundAnimgraph_DebugSnapshotData_t>.Size => 80;
    static string? ISchemaClass<AI_MotorGroundAnimgraph_DebugSnapshotData_t>.ClassName => null;


    public ref CGlobalSymbol State { get; }

    public ref bool B_has_path { get; }

    public ref float F_remaining_ground_path_length { get; }

    public ref float F_current_speed { get; }

    public ref CGlobalSymbol Move_type { get; }

    public ref float F_move_heading_actual { get; }

    public ref float F_move_heading_desired { get; }

    public ref float F_current_lean { get; }

    public ref float F_target_lean { get; }

    public ref CUtlVector<AI_MotorGroundAnimgraph_DebugSnapshotData_t__Event_t> Vec_events { get; }


}