// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface AI_MotorGroundAnimgraph_DebugSnapshotData_t__Event_t : ISchemaClass<AI_MotorGroundAnimgraph_DebugSnapshotData_t__Event_t>
{
    static AI_MotorGroundAnimgraph_DebugSnapshotData_t__Event_t ISchemaClass<AI_MotorGroundAnimgraph_DebugSnapshotData_t__Event_t>.From(nint handle) => new AI_MotorGroundAnimgraph_DebugSnapshotData_t__Event_tImpl(handle);
    static int ISchemaClass<AI_MotorGroundAnimgraph_DebugSnapshotData_t__Event_t>.Size => 24;
    static string? ISchemaClass<AI_MotorGroundAnimgraph_DebugSnapshotData_t__Event_t>.ClassName => null;


    public string Description { get; set; }

    public ref Vector Location { get; }


}