// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface AI_Navigator_DebugSnapshotData_t__Waypoint_t : ISchemaClass<AI_Navigator_DebugSnapshotData_t__Waypoint_t>
{
    static AI_Navigator_DebugSnapshotData_t__Waypoint_t ISchemaClass<AI_Navigator_DebugSnapshotData_t__Waypoint_t>.From(nint handle) => new AI_Navigator_DebugSnapshotData_t__Waypoint_tImpl(handle);
    static int ISchemaClass<AI_Navigator_DebugSnapshotData_t__Waypoint_t>.Size => 20;
    static string? ISchemaClass<AI_Navigator_DebugSnapshotData_t__Waypoint_t>.ClassName => null;


    public ref Vector Position { get; }

    public ref uint Nav_type { get; }

    public ref uint Flags { get; }


}