// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface AnimGraph2SerializedPoseRecipe_t : ISchemaClass<AnimGraph2SerializedPoseRecipe_t>
{
    static AnimGraph2SerializedPoseRecipe_t ISchemaClass<AnimGraph2SerializedPoseRecipe_t>.From(nint handle) => new AnimGraph2SerializedPoseRecipe_tImpl(handle);
    static int ISchemaClass<AnimGraph2SerializedPoseRecipe_t>.Size => 72;
    static string? ISchemaClass<AnimGraph2SerializedPoseRecipe_t>.ClassName => null;


    public ref CUtlBinaryBlock SerializedStatic { get; }

    public void SerializedStaticUpdated();
}