// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface AnimGraph2SerializedPoseRecipeSlot_t : ISchemaClass<AnimGraph2SerializedPoseRecipeSlot_t>
{
    static AnimGraph2SerializedPoseRecipeSlot_t ISchemaClass<AnimGraph2SerializedPoseRecipeSlot_t>.From(nint handle) => new AnimGraph2SerializedPoseRecipeSlot_tImpl(handle);
    static int ISchemaClass<AnimGraph2SerializedPoseRecipeSlot_t>.Size => 64;
    static string? ISchemaClass<AnimGraph2SerializedPoseRecipeSlot_t>.ClassName => null;


    public ref CUtlBinaryBlock Topology { get; }

    public void TopologyUpdated();
}