// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimationLayer : ISchemaClass<CAnimationLayer>
{
    static CAnimationLayer ISchemaClass<CAnimationLayer>.From(nint handle) => new CAnimationLayerImpl(handle);
    static int ISchemaClass<CAnimationLayer>.Size => 76;
    static string? ISchemaClass<CAnimationLayer>.ClassName => null;


    // CAnimNetVar< int32 >
    public SchemaUntypedField Sequence { get; }

    public ref float PrevCycle { get; }

    // CAnimNetVar< float32 >
    public SchemaUntypedField Cycle { get; }

    // CAnimNetVar< float32 >
    public SchemaUntypedField Weight { get; }

    // CAnimNetVar< int32 >
    public SchemaUntypedField Order { get; }

    public ref bool Looping { get; }

    public ref int Flags { get; }

    public ref bool SequenceFinished { get; }

    public ref float KillRate { get; }

    public ref float KillDelay { get; }

    public ref int Priority { get; }


}