// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimationGraphInstance : ISchemaClass<CAnimationGraphInstance>
{
    static CAnimationGraphInstance ISchemaClass<CAnimationGraphInstance>.From(nint handle) => new CAnimationGraphInstanceImpl(handle);
    static int ISchemaClass<CAnimationGraphInstance>.Size => 832;
    static string? ISchemaClass<CAnimationGraphInstance>.ClassName => null;


    public ref bool TagDispatchDirty { get; }


}