// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CBaseModelEntity__OnDamageLevelChangedArgs_t : ISchemaClass<CBaseModelEntity__OnDamageLevelChangedArgs_t>
{
    static CBaseModelEntity__OnDamageLevelChangedArgs_t ISchemaClass<CBaseModelEntity__OnDamageLevelChangedArgs_t>.From(nint handle) => new CBaseModelEntity__OnDamageLevelChangedArgs_tImpl(handle);
    static int ISchemaClass<CBaseModelEntity__OnDamageLevelChangedArgs_t>.Size => 16;
    static string? ISchemaClass<CBaseModelEntity__OnDamageLevelChangedArgs_t>.ClassName => null;


    public ref HitGroup_t HitGroup { get; }

    public ref int DamageLevel { get; }

    public ref int DamageLevelsRemaining { get; }

    public ref int PrevDamageLevel { get; }


}