// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CBaseMoveBehavior : CPathKeyFrame, ISchemaClass<CBaseMoveBehavior>
{
    static CBaseMoveBehavior ISchemaClass<CBaseMoveBehavior>.From(nint handle) => new CBaseMoveBehaviorImpl(handle);
    static int ISchemaClass<CBaseMoveBehavior>.Size => 1312;
    static string? ISchemaClass<CBaseMoveBehavior>.ClassName => "move_keyframed";


    public ref int PositionInterpolator { get; }

    public ref int RotationInterpolator { get; }

    public ref float AnimStartTime { get; }

    public ref float AnimEndTime { get; }

    public ref float AverageSpeedAcrossFrame { get; }

    public ref CHandle<CPathKeyFrame> CurrentKeyFrame { get; }

    public ref CHandle<CPathKeyFrame> TargetKeyFrame { get; }

    public ref CHandle<CPathKeyFrame> PreKeyFrame { get; }

    public ref CHandle<CPathKeyFrame> PostKeyFrame { get; }

    public ref float TimeIntoFrame { get; }

    public ref int Direction { get; }


}