// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CBlendNodeInstanceData : ISchemaClass<CBlendNodeInstanceData>
{
    static CBlendNodeInstanceData ISchemaClass<CBlendNodeInstanceData>.From(nint handle) => new CBlendNodeInstanceDataImpl(handle);
    static int ISchemaClass<CBlendNodeInstanceData>.Size => 48;
    static string? ISchemaClass<CBlendNodeInstanceData>.ClassName => null;


    public ref float DampedValue { get; }

    public ref float Cycle { get; }

    public ref float CycleZeroTime { get; }

    public ref float PlaybackRate { get; }

    // CAnimNetVar< float32 >
    public SchemaUntypedField BlendValue { get; }

    public ref float Duration { get; }

    // CAnimNetVar< uint8 >
    public SchemaUntypedField ResetCount { get; }


}