// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CBlend2DInstanceData : ISchemaClass<CBlend2DInstanceData>
{
    static CBlend2DInstanceData ISchemaClass<CBlend2DInstanceData>.From(nint handle) => new CBlend2DInstanceDataImpl(handle);
    static int ISchemaClass<CBlend2DInstanceData>.Size => 160;
    static string? ISchemaClass<CBlend2DInstanceData>.ClassName => null;


    public ref Vector2D DampedValue { get; }

    public ref float Cycle { get; }

    public ref float PrevCycle { get; }


}