// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CChoiceInstanceData : ISchemaClass<CChoiceInstanceData>
{
    static CChoiceInstanceData ISchemaClass<CChoiceInstanceData>.From(nint handle) => new CChoiceInstanceDataImpl(handle);
    static int ISchemaClass<CChoiceInstanceData>.Size => 52;
    static string? ISchemaClass<CChoiceInstanceData>.ClassName => null;


    // CAnimNetVar< int32 >
    public SchemaUntypedField CurrentChoice { get; }

    public ref int PreviousChoice { get; }

    // CAnimNetVar< float32 >
    public SchemaUntypedField ClipStartTime { get; }

    public ref float ChoicePreviousCycle { get; }


}