// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CChoreoInstanceData : ISchemaClass<CChoreoInstanceData>
{
    static CChoreoInstanceData ISchemaClass<CChoreoInstanceData>.From(nint handle) => new CChoreoInstanceDataImpl(handle);
    static int ISchemaClass<CChoreoInstanceData>.Size => 920;
    static string? ISchemaClass<CChoreoInstanceData>.ClassName => null;


    public ISchemaClassFixedArray<CAnimationLayer> AnimOverlay { get; }


}