// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CChoreoComponent : ISchemaClass<CChoreoComponent>
{
    static CChoreoComponent ISchemaClass<CChoreoComponent>.From(nint handle) => new CChoreoComponentImpl(handle);
    static int ISchemaClass<CChoreoComponent>.Size => 128;
    static string? ISchemaClass<CChoreoComponent>.ClassName => null;


    public ref CNetworkVarChainer __m_pChainEntity { get; }

    public ref CHandle<CBaseModelEntity> Owner { get; }

    public SceneEventId_t NextSceneEventId { get; }

    public ref bool UpdateLayerPriorities { get; }

    public GameTime_t AllowResponsesEndTime { get; }


}