// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CCS2PawnGraphController : CCS2WeaponGraphController, ISchemaClass<CCS2PawnGraphController>
{
    static CCS2PawnGraphController ISchemaClass<CCS2PawnGraphController>.From(nint handle) => new CCS2PawnGraphControllerImpl(handle);
    static int ISchemaClass<CCS2PawnGraphController>.Size => 2112;
    static string? ISchemaClass<CCS2PawnGraphController>.ClassName => null;


    // CAnimGraph2ParamOptionalRef< bool >
    public SchemaUntypedField IsDefusing { get; }

    // CAnimGraph2ParamOptionalRef< CGlobalSymbol >
    public SchemaUntypedField MoveType { get; }

    // CAnimGraph2ParamOptionalRef< CGlobalSymbol >
    public SchemaUntypedField MoveDirectionID { get; }

    // CAnimGraph2ParamOptionalRef< float32 >
    public SchemaUntypedField MoveSpeedX { get; }

    // CAnimGraph2ParamOptionalRef< float32 >
    public SchemaUntypedField MoveSpeedY { get; }

    // CAnimGraph2ParamOptionalRef< float32 >
    public SchemaUntypedField MoveSpeedHorizontal { get; }

    // CAnimGraph2ParamOptionalRef< float32 >
    public SchemaUntypedField PreviousMoveSpeedHorizontal { get; }

    // CAnimGraph2ParamOptionalRef< float32 >
    public SchemaUntypedField CrouchAmount { get; }

    // CAnimGraph2ParamOptionalRef< bool >
    public SchemaUntypedField IsWalking { get; }

    // CAnimGraph2ParamOptionalRef< bool >
    public SchemaUntypedField IsStutterStep { get; }

    // CAnimGraph2ParamOptionalRef< float32 >
    public SchemaUntypedField WeaponDropAmount { get; }

    // CAnimGraph2ParamOptionalRef< CGlobalSymbol >
    public SchemaUntypedField GroundAction { get; }

    // CAnimGraph2ParamOptionalRef< CGlobalSymbol >
    public SchemaUntypedField GroundActionDirectionID { get; }

    // CAnimGraph2ParamOptionalRef< float32 >
    public SchemaUntypedField GroundTurnAngleOrVelocity { get; }

    // CAnimGraph2ParamOptionalRef< float32 >
    public SchemaUntypedField LadderCycle { get; }

    // CAnimGraph2ParamOptionalRef< float32 >
    public SchemaUntypedField LadderYaw { get; }

    // CAnimGraph2ParamOptionalRef< float32 >
    public SchemaUntypedField LadderYawBackwards { get; }

    // CAnimGraph2ParamOptionalRef< CGlobalSymbol >
    public SchemaUntypedField AirAction { get; }

    // CAnimGraph2ParamOptionalRef< float32 >
    public SchemaUntypedField AirHeightAboveGround { get; }

    // CAnimGraph2ParamOptionalRef< CNmTarget >
    public SchemaUntypedField LeftFootTarget { get; }

    // CAnimGraph2ParamOptionalRef< CNmTarget >
    public SchemaUntypedField RightFootTarget { get; }

    // CAnimGraph2ParamOptionalRef< float32 >
    public SchemaUntypedField FlashedAmount { get; }

    // CAnimGraph2ParamOptionalRef< float32 >
    public SchemaUntypedField AimPitchAngle { get; }

    // CAnimGraph2ParamOptionalRef< float32 >
    public SchemaUntypedField AimYawAngle { get; }

    // CAnimGraph2ParamOptionalRef< CGlobalSymbol >
    public SchemaUntypedField FlinchHead { get; }

    // CAnimGraph2ParamOptionalRef< bool >
    public SchemaUntypedField FlinchHeadRestart { get; }

    // CAnimGraph2ParamOptionalRef< CGlobalSymbol >
    public SchemaUntypedField FlinchBody { get; }

    // CAnimGraph2ParamOptionalRef< bool >
    public SchemaUntypedField FlinchBodyRestart { get; }

    // CAnimGraph2ParamOptionalRef< bool >
    public SchemaUntypedField FlinchIsOnFire { get; }


}