// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CCS2ChickenGraphController : CAnimGraphControllerBase, ISchemaClass<CCS2ChickenGraphController>
{
    static CCS2ChickenGraphController ISchemaClass<CCS2ChickenGraphController>.From(nint handle) => new CCS2ChickenGraphControllerImpl(handle);
    static int ISchemaClass<CCS2ChickenGraphController>.Size => 344;
    static string? ISchemaClass<CCS2ChickenGraphController>.ClassName => null;


    public ref CAnimGraph2ParamOptionalRefCGlobalSymbol Action { get; }

    public ref CAnimGraph2ParamOptionalRefCGlobalSymbol ActionSubtype { get; }

    // CAnimGraph2ParamAutoResetOptionalRef
    public SchemaUntypedField ActionReset { get; }

    public ref CAnimGraph2ParamOptionalRefFloat IdleVariation { get; }

    public ref CAnimGraph2ParamOptionalRefFloat RunVariation { get; }

    public ref CAnimGraph2ParamOptionalRefFloat PanicVariation { get; }

    public ref CAnimGraph2ParamOptionalRefFloat SquatVariation { get; }

    public ref CAnimGraph2ParamOptionalRefBool InWater { get; }

    public ref bool HasActionCompletedEvent { get; }

    public ref bool WaitingForCompletedEvent { get; }


}