// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CCSGO_EndOfMatchLineupStart : CCSGO_EndOfMatchLineupEndpoint, ISchemaClass<CCSGO_EndOfMatchLineupStart>
{
    static CCSGO_EndOfMatchLineupStart ISchemaClass<CCSGO_EndOfMatchLineupStart>.From(nint handle) => new CCSGO_EndOfMatchLineupStartImpl(handle);
    static int ISchemaClass<CCSGO_EndOfMatchLineupStart>.Size => 1192;
    static string? ISchemaClass<CCSGO_EndOfMatchLineupStart>.ClassName => "end_of_match_lineup_start";

}