// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CCSGO_EndOfMatchLineupEndpoint : CBaseEntity, ISchemaClass<CCSGO_EndOfMatchLineupEndpoint>
{
    static CCSGO_EndOfMatchLineupEndpoint ISchemaClass<CCSGO_EndOfMatchLineupEndpoint>.From(nint handle) => new CCSGO_EndOfMatchLineupEndpointImpl(handle);
    static int ISchemaClass<CCSGO_EndOfMatchLineupEndpoint>.Size => 1192;
    static string? ISchemaClass<CCSGO_EndOfMatchLineupEndpoint>.ClassName => null;

}