// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CCSGO_EndOfMatchLineupEnd : CCSGO_EndOfMatchLineupEndpoint, ISchemaClass<CCSGO_EndOfMatchLineupEnd>
{
    static CCSGO_EndOfMatchLineupEnd ISchemaClass<CCSGO_EndOfMatchLineupEnd>.From(nint handle) => new CCSGO_EndOfMatchLineupEndImpl(handle);
    static int ISchemaClass<CCSGO_EndOfMatchLineupEnd>.Size => 1192;
    static string? ISchemaClass<CCSGO_EndOfMatchLineupEnd>.ClassName => "end_of_match_lineup_end";

}