// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CCSPlayer_AimPunchServices : CPlayerPawnComponent, ISchemaClass<CCSPlayer_AimPunchServices>
{
    static CCSPlayer_AimPunchServices ISchemaClass<CCSPlayer_AimPunchServices>.From(nint handle) => new CCSPlayer_AimPunchServicesImpl(handle);
    static int ISchemaClass<CCSPlayer_AimPunchServices>.Size => 232;
    static string? ISchemaClass<CCSPlayer_AimPunchServices>.ClassName => null;


    public GameTick_t PredictableBaseTick { get; }

    public ref float PredictableBaseTickInterpAmount { get; }

    public ref QAngle PredictableBaseAngle { get; }

    public ref QAngle PredictableBaseAngleVel { get; }

    public GameTick_t UnpredictableBaseTick { get; }

    public ref QAngle UnpredictableBaseAngle { get; }

    public void PredictableBaseTickUpdated();
    public void PredictableBaseTickInterpAmountUpdated();
    public void PredictableBaseAngleUpdated();
    public void PredictableBaseAngleVelUpdated();
    public void UnpredictableBaseTickUpdated();
    public void UnpredictableBaseAngleUpdated();
}