// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CCSPlayerAnimationState : ISchemaClass<CCSPlayerAnimationState>
{
    static CCSPlayerAnimationState ISchemaClass<CCSPlayerAnimationState>.From(nint handle) => new CCSPlayerAnimationStateImpl(handle);
    static int ISchemaClass<CCSPlayerAnimationState>.Size => 240;
    static string? ISchemaClass<CCSPlayerAnimationState>.ClassName => null;


    public ref CCSPlayerAnimationState__MoveType_t CurrentMoveType { get; }

    public ref CCSPlayerAnimationState__GroundMoveState_t GroundMoveState { get; }

    public ref CCSPlayerAnimationState__Direction_t GroundActionDirection { get; }

    public ref CCSPlayerAnimationState__AirAction_t AirAction { get; }

    public ref bool WasOnGroundLastUpdate { get; }

    public ref bool WasStationaryLastUpdate { get; }

    public GameTick_t ActionStartTick { get; }

    public GameTick_t StaticAimTimerStartTick { get; }

    public GameTick_t StutterStepStartTick { get; }

    public GameTick_t PlantAndTurnStartTick { get; }

    public ref bool IsStutterStep { get; }

    public ref float TurnOnSpotAngle { get; }

    public ref float PreviousAimYaw { get; }

    public ref float PreviousHorizontalSpeed { get; }

    public ref float FootIKOffsetLeft { get; }

    public ref float FootIKOffsetRight { get; }

    public ref float WeaponDropPercentageDueToMovement { get; }

    public ref float WeaponDropSmoothDampVelocity { get; }


}