// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CCycleClipInstanceData : ISchemaClass<CCycleClipInstanceData>
{
    static CCycleClipInstanceData ISchemaClass<CCycleClipInstanceData>.From(nint handle) => new CCycleClipInstanceDataImpl(handle);
    static int ISchemaClass<CCycleClipInstanceData>.Size => 28;
    static string? ISchemaClass<CCycleClipInstanceData>.ClassName => null;


    // CAnimNetVar< float32 >
    public SchemaUntypedField Cycle { get; }

    // CAnimNetVar< float32 >
    public SchemaUntypedField PrevCycle { get; }


}