// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CDebugDrawHistoryData : ISchemaClass<CDebugDrawHistoryData>
{
    static CDebugDrawHistoryData ISchemaClass<CDebugDrawHistoryData>.From(nint handle) => new CDebugDrawHistoryDataImpl(handle);
    static int ISchemaClass<CDebugDrawHistoryData>.Size => 120;
    static string? ISchemaClass<CDebugDrawHistoryData>.ClassName => null;


    public ref CHandle<CBaseEntity> Entity { get; }

    public ref ESceneViewDebugOverlaysListenerDataType_t Etype { get; }

    public ref CUtlLeanVector<Vector4D, int> Vectors { get; }

    public ref CUtlLeanVector<Color, int> Colors { get; }

    public ref CUtlLeanVector<float, int> Dimensions { get; }

    public ref CUtlLeanVector<double, int> Times { get; }

    public ref CUtlLeanVector<ulong, int> Uint64s { get; }

    public ref CUtlLeanVector<bool, int> Bools { get; }

    public ref CUtlLeanVector<CUtlString, int> Strings { get; }


}