// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CDebugSnapshotData_t : ISchemaClass<CDebugSnapshotData_t>
{
    static CDebugSnapshotData_t ISchemaClass<CDebugSnapshotData_t>.From(nint handle) => new CDebugSnapshotData_tImpl(handle);
    static int ISchemaClass<CDebugSnapshotData_t>.Size => 304;
    static string? ISchemaClass<CDebugSnapshotData_t>.ClassName => null;


    public string Text { get; set; }

    public ref uint DataType { get; }

    public ref uint UserFlags { get; }

    public ref uint UserData { get; }

    public ref Vector UserVector { get; }

    public ref CTransform UserTransform { get; }

    public CGenericShapeProxy UserShape { get; }

    public ref Color DrawColor { get; }

    public ref CUtlVector<PointerTo<CDebugDrawHistoryData>> DebugOverlayData { get; }

    public DebugSnapshotBaseStructuredData_t? StructuredData { get; }

    public ref CHandle<CBaseEntity> Entity { get; }

    public string EntityName { get; set; }

    public ref uint EntityIndex { get; }

    public ref CUtlLeanVector<CDebugSnapshotData_t, int> Children { get; }


}