// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CDirectPlaybackInstanceData : ISchemaClass<CDirectPlaybackInstanceData>
{
    static CDirectPlaybackInstanceData ISchemaClass<CDirectPlaybackInstanceData>.From(nint handle) => new CDirectPlaybackInstanceDataImpl(handle);
    static int ISchemaClass<CDirectPlaybackInstanceData>.Size => 328;
    static string? ISchemaClass<CDirectPlaybackInstanceData>.ClassName => null;


    public ref Vector TargetPosition { get; }

    public ref float TargetFacing { get; }

    public ref float InterpEndTime { get; }

    public ISchemaFixedArray<float> Weights { get; }

    public ISchemaClassFixedArray<SequenceData> Sequences { get; }

    public ref uint CurrentSequenceIndex { get; }

    // CAnimNetVar< uint64 >
    public SchemaUntypedField CurrentSequenceData { get; }

    public ref float FadeInTime { get; }

    public ref float FadeOutTime { get; }

    // CAnimNetVar< float32 >
    public SchemaUntypedField ForcedCycle { get; }

    public ref bool ResetPending { get; }

    // CAnimNetVar< float32 >
    public SchemaUntypedField SequenceCycleZeroTime { get; }


}