// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CDirectionalBlendInstanceData : ISchemaClass<CDirectionalBlendInstanceData>
{
    static CDirectionalBlendInstanceData ISchemaClass<CDirectionalBlendInstanceData>.From(nint handle) => new CDirectionalBlendInstanceDataImpl(handle);
    static int ISchemaClass<CDirectionalBlendInstanceData>.Size => 80;
    static string? ISchemaClass<CDirectionalBlendInstanceData>.ClassName => null;


    public ref float DampedValue { get; }

    public ref float Cycle { get; }

    public ref float PrevCycle { get; }

    // CAnimNetVar< float32 >
    public SchemaUntypedField PlaybackRate { get; }

    // CAnimNetVar< float32 >
    public SchemaUntypedField CycleZeroTime { get; }

    // CAnimNetVar< float32 >
    public SchemaUntypedField ResetCycleValue { get; }

    // CAnimNetVar< float32 >
    public SchemaUntypedField ResetCount { get; }


}