// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CExplosionTypeData : ISchemaClass<CExplosionTypeData>
{
    static CExplosionTypeData ISchemaClass<CExplosionTypeData>.From(nint handle) => new CExplosionTypeDataImpl(handle);
    static int ISchemaClass<CExplosionTypeData>.Size => 256;
    static string? ISchemaClass<CExplosionTypeData>.ClassName => null;


    // CSoundEventName
    public SchemaUntypedField SoundName { get; }

    // CResourceNameTyped< CWeakHandle< InfoForResourceTypeIParticleSystemDefinition > >
    public SchemaUntypedField ParticleEffect { get; }

    public ref bool IsIncindiary { get; }

    public ref bool HasForces { get; }

    public ref CGlobalSymbol DecalType { get; }


}