// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CFollowPathInstanceData : ISchemaClass<CFollowPathInstanceData>
{
    static CFollowPathInstanceData ISchemaClass<CFollowPathInstanceData>.From(nint handle) => new CFollowPathInstanceDataImpl(handle);
    static int ISchemaClass<CFollowPathInstanceData>.Size => 36;
    static string? ISchemaClass<CFollowPathInstanceData>.ClassName => null;


    // CRelativeArray< CMotionTransform >
    public SchemaUntypedField XLastPredictedTransformsDeltas { get; }

    public ref float DampedTurnValue { get; }

    public ref float TurnAmount { get; }

    // CAnimNetVar< float32 >
    public SchemaUntypedField PredictionScale { get; }

    public ref float LastPathTime { get; }


}