// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CFootAdjustmentInstanceData : ISchemaClass<CFootAdjustmentInstanceData>
{
    static CFootAdjustmentInstanceData ISchemaClass<CFootAdjustmentInstanceData>.From(nint handle) => new CFootAdjustmentInstanceDataImpl(handle);
    static int ISchemaClass<CFootAdjustmentInstanceData>.Size => 72;
    static string? ISchemaClass<CFootAdjustmentInstanceData>.ClassName => null;


    // CAnimNetVar< float32 >
    public SchemaUntypedField StartTime { get; }

    // CAnimNetVar< float32 >
    public SchemaUntypedField Duration { get; }

    public ref float StartHeadingWS { get; }


}