// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CGenericShapeProxy : ISchemaClass<CGenericShapeProxy>
{
    static CGenericShapeProxy ISchemaClass<CGenericShapeProxy>.From(nint handle) => new CGenericShapeProxyImpl(handle);
    static int ISchemaClass<CGenericShapeProxy>.Size => 152;
    static string? ISchemaClass<CGenericShapeProxy>.ClassName => null;


    // CUtlLeanVectorFixedGrowable< Vector, 8 >
    public SchemaUntypedField Verts { get; }


}