// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CInfoChoreoAnchor : CPointEntity, ISchemaClass<CInfoChoreoAnchor>
{
    static CInfoChoreoAnchor ISchemaClass<CInfoChoreoAnchor>.From(nint handle) => new CInfoChoreoAnchorImpl(handle);
    static int ISchemaClass<CInfoChoreoAnchor>.Size => 1240;
    static string? ISchemaClass<CInfoChoreoAnchor>.ClassName => "info_choreo_anchor";


    public ref CUtlVector<CInfoChoreoAnchorPosition> TargetEntries { get; }

    public ref CUtlVector<CInfoChoreoAnchorPosition> TargetWarps { get; }


}