// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CInfoChoreoAnchorPosition : ISchemaClass<CInfoChoreoAnchorPosition>
{
    static CInfoChoreoAnchorPosition ISchemaClass<CInfoChoreoAnchorPosition>.From(nint handle) => new CInfoChoreoAnchorPositionImpl(handle);
    static int ISchemaClass<CInfoChoreoAnchorPosition>.Size => 56;
    static string? ISchemaClass<CInfoChoreoAnchorPosition>.ClassName => null;


    public ref Vector Origin { get; }

    public ref QAngle Angles { get; }

    public ref Vector ExtentsMin { get; }

    public ref Vector ExtentsMax { get; }

    public ref float Radius { get; }

    public ref CInfoChoreoLocatorShapeType_t ShapeType { get; }


}