// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CLogicRelay : CLogicalEntity, ISchemaClass<CLogicRelay>
{
    static CLogicRelay ISchemaClass<CLogicRelay>.From(nint handle) => new CLogicRelayImpl(handle);
    static int ISchemaClass<CLogicRelay>.Size => 1248;
    static string? ISchemaClass<CLogicRelay>.ClassName => "logic_relay";


    public ref CEntityIOOutput OnSpawn { get; }

    public ref CEntityIOOutput OnTrigger { get; }

    public ref bool Disabled { get; }

    public ref bool WaitForRefire { get; }

    public ref bool TriggerOnce { get; }

    public ref bool FastRetrigger { get; }

    public ref bool PassthoughCaller { get; }


}