// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CModelState : ISchemaClass<CModelState>
{
    static CModelState ISchemaClass<CModelState>.From(nint handle) => new CModelStateImpl(handle);
    static int ISchemaClass<CModelState>.Size => 592;
    static string? ISchemaClass<CModelState>.ClassName => null;


    public ref CStrongHandle<InfoForResourceTypeCModel> Model { get; }

    public string ModelName { get; set; }

    public IPhysAggregateInstance? VPhysicsAggregate { get; }

    public ref float RootBoneOffset_x { get; }

    public ref float RootBoneOffset_y { get; }

    public ref float RootBoneOffset_z { get; }

    public ref byte RootBoneOffsetResetSerialNumber { get; }

    public ref bool ClientClothCreationSuppressed { get; }

    public ref byte AnimStateNoInterpSerialNumber { get; }

    public ref ulong MeshGroupMask { get; }

    public ref CUtlVector<int> BodyGroupChoices { get; }

    public ref byte IdealMotionType { get; }

    public ref byte ForceLOD { get; }

    public ref byte ClothUpdateFlags { get; }

    public void ModelUpdated();
    public void RootBoneOffset_xUpdated();
    public void RootBoneOffset_yUpdated();
    public void RootBoneOffset_zUpdated();
    public void RootBoneOffsetResetSerialNumberUpdated();
    public void ClientClothCreationSuppressedUpdated();
    public void AnimStateNoInterpSerialNumberUpdated();
    public void MeshGroupMaskUpdated();
    public void BodyGroupChoicesUpdated();
    public void IdealMotionTypeUpdated();
}