// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CMoverInstanceData : ISchemaClass<CMoverInstanceData>
{
    static CMoverInstanceData ISchemaClass<CMoverInstanceData>.From(nint handle) => new CMoverInstanceDataImpl(handle);
    static int ISchemaClass<CMoverInstanceData>.Size => 44;
    static string? ISchemaClass<CMoverInstanceData>.ClassName => null;


    public ref float DampedValue { get; }

    public ref Vector Movement { get; }

    // CRotation
    public SchemaUntypedField Rotation { get; }

    // CRotation
    public SchemaUntypedField TargetOrientation { get; }


}