// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNetworkedCycle : ISchemaClass<CNetworkedCycle>
{
    static CNetworkedCycle ISchemaClass<CNetworkedCycle>.From(nint handle) => new CNetworkedCycleImpl(handle);
    static int ISchemaClass<CNetworkedCycle>.Size => 52;
    static string? ISchemaClass<CNetworkedCycle>.ClassName => null;


    public ref float CycleUnclamped { get; }

    public ref float PrevCycleUnclamped { get; }

    // CAnimNetVar< float32 >
    public SchemaUntypedField CyclesPerSecond { get; }

    // CAnimNetVar< float32 >
    public SchemaUntypedField CycleZeroTime { get; }

    // CAnimNetVar< uint8 >
    public SchemaUntypedField ResetCount { get; }


}