// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmFootIKNode__CDefinition : CNmPassthroughNode__CDefinition, ISchemaClass<CNmFootIKNode__CDefinition>
{
    static CNmFootIKNode__CDefinition ISchemaClass<CNmFootIKNode__CDefinition>.From(nint handle) => new CNmFootIKNode__CDefinitionImpl(handle);
    static int ISchemaClass<CNmFootIKNode__CDefinition>.Size => 56;
    static string? ISchemaClass<CNmFootIKNode__CDefinition>.ClassName => null;


    public ref CGlobalSymbol LeftEffectorBoneID { get; }

    public ref CGlobalSymbol RightEffectorBoneID { get; }

    public ref short LeftTargetNodeIdx { get; }

    public ref short RightTargetNodeIdx { get; }

    public ref short EnabledNodeIdx { get; }

    public ref float BlendTimeSeconds { get; }

    public ref NmIKBlendMode_t BlendMode { get; }

    public ref bool IsTargetInWorldSpace { get; }


}