// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmFootIKTask : CNmPoseTask, ISchemaClass<CNmFootIKTask>
{
    static CNmFootIKTask ISchemaClass<CNmFootIKTask>.From(nint handle) => new CNmFootIKTaskImpl(handle);
    static int ISchemaClass<CNmFootIKTask>.Size => 272;
    static string? ISchemaClass<CNmFootIKTask>.ClassName => null;


    public ref int LeftEffectorBoneIdx { get; }

    public ref int RightEffectorBoneIdx { get; }

    public ref CTransform LeftTargetTransform { get; }

    public ref CTransform RightTargetTransform { get; }

    public ref int LeftTargetBoneIdx { get; }

    public ref int RightTargetBoneIdx { get; }

    public CNmTarget LeftTarget { get; }

    public CNmTarget RightTarget { get; }

    public ref NmIKBlendMode_t BlendMode { get; }

    public ref float BlendWeight { get; }

    public ref bool IsTargetInWorldSpace { get; }

    public ref bool IsRunningFromDeserializedData { get; }


}