// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmFloatSpringNode__CDefinition : CNmFloatValueNode__CDefinition, ISchemaClass<CNmFloatSpringNode__CDefinition>
{
    static CNmFloatSpringNode__CDefinition ISchemaClass<CNmFloatSpringNode__CDefinition>.From(nint handle) => new CNmFloatSpringNode__CDefinitionImpl(handle);
    static int ISchemaClass<CNmFloatSpringNode__CDefinition>.Size => 32;
    static string? ISchemaClass<CNmFloatSpringNode__CDefinition>.ClassName => null;


    public ref float StartValue { get; }

    public ref float Hertz { get; }

    public ref float DampingRatio { get; }

    public ref short InputValueNodeIdx { get; }

    public ref bool UseStartValue { get; }


}