// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmIDBasedSelectorNode__CDefinition : CNmPoseNode__CDefinition, ISchemaClass<CNmIDBasedSelectorNode__CDefinition>
{
    static CNmIDBasedSelectorNode__CDefinition ISchemaClass<CNmIDBasedSelectorNode__CDefinition>.From(nint handle) => new CNmIDBasedSelectorNode__CDefinitionImpl(handle);
    static int ISchemaClass<CNmIDBasedSelectorNode__CDefinition>.Size => 96;
    static string? ISchemaClass<CNmIDBasedSelectorNode__CDefinition>.ClassName => null;


    // CUtlLeanVectorFixedGrowable< int16, 5 >
    public SchemaUntypedField OptionNodeIndices { get; }

    // CUtlLeanVectorFixedGrowable< CGlobalSymbol, 5 >
    public SchemaUntypedField OptionIDs { get; }

    public ref short ParameterNodeIdx { get; }

    public ref short FallbackNodeIdx { get; }

    public ref bool IgnoreInvalidOptions { get; }


}