// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmIDBasedClipSelectorNode__CDefinition : CNmClipReferenceNode__CDefinition, ISchemaClass<CNmIDBasedClipSelectorNode__CDefinition>
{
    static CNmIDBasedClipSelectorNode__CDefinition ISchemaClass<CNmIDBasedClipSelectorNode__CDefinition>.From(nint handle) => new CNmIDBasedClipSelectorNode__CDefinitionImpl(handle);
    static int ISchemaClass<CNmIDBasedClipSelectorNode__CDefinition>.Size => 96;
    static string? ISchemaClass<CNmIDBasedClipSelectorNode__CDefinition>.ClassName => null;


    // CUtlLeanVectorFixedGrowable< int16, 5 >
    public SchemaUntypedField OptionNodeIndices { get; }

    // CUtlLeanVectorFixedGrowable< CGlobalSymbol, 5 >
    public SchemaUntypedField OptionIDs { get; }

    public ref short ParameterNodeIdx { get; }

    public ref short FallbackNodeIdx { get; }

    public ref bool IgnoreInvalidOptions { get; }


}