// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPulseCell_Outflow_PlayVOLine : CPulseCell_BaseYieldingInflow, ISchemaClass<CPulseCell_Outflow_PlayVOLine>
{
    static CPulseCell_Outflow_PlayVOLine ISchemaClass<CPulseCell_Outflow_PlayVOLine>.From(nint handle) => new CPulseCell_Outflow_PlayVOLineImpl(handle);
    static int ISchemaClass<CPulseCell_Outflow_PlayVOLine>.Size => 144;
    static string? ISchemaClass<CPulseCell_Outflow_PlayVOLine>.ClassName => null;


    public CPulse_ResumePoint OnFinished { get; }


}