// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPulseCell_Outflow_PlayVCD__VCDRequirementInfo_t : ISchemaClass<CPulseCell_Outflow_PlayVCD__VCDRequirementInfo_t>
{
    static CPulseCell_Outflow_PlayVCD__VCDRequirementInfo_t ISchemaClass<CPulseCell_Outflow_PlayVCD__VCDRequirementInfo_t>.From(nint handle) => new CPulseCell_Outflow_PlayVCD__VCDRequirementInfo_tImpl(handle);
    static int ISchemaClass<CPulseCell_Outflow_PlayVCD__VCDRequirementInfo_t>.Size => 80;
    static string? ISchemaClass<CPulseCell_Outflow_PlayVCD__VCDRequirementInfo_t>.ClassName => null;


    public ref int EventID { get; }

    public CPulse_OutflowConnection Outflow { get; }


}