// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CRelativeTransform : ISchemaClass<CRelativeTransform>
{
    static CRelativeTransform ISchemaClass<CRelativeTransform>.From(nint handle) => new CRelativeTransformImpl(handle);
    static int ISchemaClass<CRelativeTransform>.Size => 96;
    static string? ISchemaClass<CRelativeTransform>.ClassName => null;


    public ref bool TransformIsWorldSpace { get; }

    public ref CTransform Transform { get; }

    public ref CTransform TransformWS { get; }

    public ref CHandle<CBaseEntity> Entity { get; }


}