// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CRootMotion : ISchemaClass<CRootMotion>
{
    static CRootMotion ISchemaClass<CRootMotion>.From(nint handle) => new CRootMotionImpl(handle);
    static int ISchemaClass<CRootMotion>.Size => 40;
    static string? ISchemaClass<CRootMotion>.ClassName => null;


    // CMotionTransform
    public SchemaUntypedField DeltaTransform { get; }

    public ref Vector VelocityMS { get; }

    public ref Vector UpOverride { get; }


}