// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSceneCriteria : ISchemaClass<CSceneCriteria>
{
    static CSceneCriteria ISchemaClass<CSceneCriteria>.From(nint handle) => new CSceneCriteriaImpl(handle);
    static int ISchemaClass<CSceneCriteria>.Size => 56;
    static string? ISchemaClass<CSceneCriteria>.ClassName => null;


    public ref CHandle<CBaseEntity> Owner { get; }

    public ref InteractionPriority_t Priority { get; }

    public SceneInterestTags_t InterestReqTags { get; }

    public SceneInterestTags_t InterestOptTags { get; }


}