// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CScenePayloadVData : ISchemaClass<CScenePayloadVData>
{
    static CScenePayloadVData ISchemaClass<CScenePayloadVData>.From(nint handle) => new CScenePayloadVDataImpl(handle);
    static int ISchemaClass<CScenePayloadVData>.Size => 464;
    static string? ISchemaClass<CScenePayloadVData>.ClassName => null;


    public ref ENPCBehaviorOverride_t NPCBehavior { get; }

    // CResourceNameTyped< CWeakHandle< InfoForResourceTypeIPulseGraphDef > >
    public SchemaUntypedField PulseFile { get; }

    // CResourceNameTyped< CWeakHandle< InfoForResourceTypeCChoreoSceneResource > >
    public SchemaUntypedField SceneFile { get; }

    public ref InteractionPriority_t Priority { get; }


}