// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSceneOpportunity : ISchemaClass<CSceneOpportunity>
{
    static CSceneOpportunity ISchemaClass<CSceneOpportunity>.From(nint handle) => new CSceneOpportunityImpl(handle);
    static int ISchemaClass<CSceneOpportunity>.Size => 144;
    static string? ISchemaClass<CSceneOpportunity>.ClassName => null;


    public ref CHandle<CBaseEntity> Owner { get; }

    public SceneOpportunityHandle_t Handle { get; }

    public string StrInteractVDataName { get; set; }

    public ref bool Enabled { get; }

    public ref bool Active { get; }

    public ref InteractionPriority_t Priority { get; }

    public ref float Radius { get; }

    public SceneInterestTags_t LocalInterestReqTags { get; }

    public SceneInterestTags_t LocalInterestOptTags { get; }

    public ref float OwnerFOV { get; }

    public ref CUtlVector<SceneOpportunityActor_t> ActorList { get; }

    public ref CHandle<CBaseEntity> LookTarget { get; }

    public ref float Duration { get; }

    public GameTime_t TStartTime { get; }

    public ref float Cooldown { get; }

    public GameTime_t TCooldownTime { get; }

    public ref int RepeatCount { get; }

    public ref bool DisableOnExit { get; }


}