// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSndSeqInstMidiSampler : CSndSeqInstBaseSchema, ISchemaClass<CSndSeqInstMidiSampler>
{
    static CSndSeqInstMidiSampler ISchemaClass<CSndSeqInstMidiSampler>.From(nint handle) => new CSndSeqInstMidiSamplerImpl(handle);
    static int ISchemaClass<CSndSeqInstMidiSampler>.Size => 224;
    static string? ISchemaClass<CSndSeqInstMidiSampler>.ClassName => null;


    public ref bool IsSoundEvent { get; }

    public ref bool StopPrevious { get; }

    public ref byte MinNote { get; }

    public ref byte MaxNote { get; }

    public ref float MinVelocityAtten { get; }

    public ref float MaxVelocityAtten { get; }

    public ref float Attack { get; }

    public ref float Release { get; }

    public ref bool BeatEnvelopes { get; }

    public ref byte NextVoiceSlot { get; }

    public ref uint SoundEventHash { get; }


}