// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSndSeqInstBaseSchema : ISchemaClass<CSndSeqInstBaseSchema>
{
    static CSndSeqInstBaseSchema ISchemaClass<CSndSeqInstBaseSchema>.From(nint handle) => new CSndSeqInstBaseSchemaImpl(handle);
    static int ISchemaClass<CSndSeqInstBaseSchema>.Size => 32;
    static string? ISchemaClass<CSndSeqInstBaseSchema>.ClassName => null;


    public ref SndSeqInstrumentType_t Type { get; }

    public ref SndSeqPlayerType_t PlayerType { get; }

    public ref bool StopCurrentEvents { get; }

    public ref float BPM { get; }

    public ref float BPMFactor { get; }

    public ref float BPMInvFactor { get; }


}