// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSndSeqInstruments : ISndSeqInstruments, ISchemaClass<CSndSeqInstruments>
{
    static CSndSeqInstruments ISchemaClass<CSndSeqInstruments>.From(nint handle) => new CSndSeqInstrumentsImpl(handle);
    static int ISchemaClass<CSndSeqInstruments>.Size => 40;
    static string? ISchemaClass<CSndSeqInstruments>.ClassName => null;

}