// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSosGroupActionOcclusionSchema : CSosGroupActionSchema, ISchemaClass<CSosGroupActionOcclusionSchema>
{
    static CSosGroupActionOcclusionSchema ISchemaClass<CSosGroupActionOcclusionSchema>.From(nint handle) => new CSosGroupActionOcclusionSchemaImpl(handle);
    static int ISchemaClass<CSosGroupActionOcclusionSchema>.Size => 32;
    static string? ISchemaClass<CSosGroupActionOcclusionSchema>.ClassName => null;


    public ref float CalculationInterval { get; }

    public ref float Radius { get; }

    public ref float OcclusionScale { get; }

    public ref float OcclusionMin { get; }

    public ref float OcclusionMax { get; }

    public ref float TestDepth { get; }


}