// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CStateMachineInstanceData : ISchemaClass<CStateMachineInstanceData>
{
    static CStateMachineInstanceData ISchemaClass<CStateMachineInstanceData>.From(nint handle) => new CStateMachineInstanceDataImpl(handle);
    static int ISchemaClass<CStateMachineInstanceData>.Size => 28;
    static string? ISchemaClass<CStateMachineInstanceData>.ClassName => null;


    public ref float TimeInState { get; }

    // CAnimNetVar< int32 >
    public SchemaUntypedField CurrentTransitionIndex { get; }

    public ref int PrevStateIndex { get; }

    public ref int ScheduledTransitionIndex { get; }


}