// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CStateNodeInstanceData : ISchemaClass<CStateNodeInstanceData>
{
    static CStateNodeInstanceData ISchemaClass<CStateNodeInstanceData>.From(nint handle) => new CStateNodeInstanceDataImpl(handle);
    static int ISchemaClass<CStateNodeInstanceData>.Size => 76;
    static string? ISchemaClass<CStateNodeInstanceData>.ClassName => null;


    // CRelativeArray< float32 >
    public SchemaUntypedField StateWeights { get; }

    public ref Vector TransitionVelocityDeltaWS { get; }

    // CAnimNetVar< float32 >
    public SchemaUntypedField CurrentStateStartTime { get; }

    // CAnimNetVar< uint8 >
    public SchemaUntypedField ResetCount { get; }


}