// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CTakeDamageResultAPI : ISchemaClass<CTakeDamageResultAPI>
{
    static CTakeDamageResultAPI ISchemaClass<CTakeDamageResultAPI>.From(nint handle) => new CTakeDamageResultAPIImpl(handle);
    static int ISchemaClass<CTakeDamageResultAPI>.Size => 8;
    static string? ISchemaClass<CTakeDamageResultAPI>.ClassName => null;

}