// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CTestPulseIO__ThreeStringArgs_t : ISchemaClass<CTestPulseIO__ThreeStringArgs_t>
{
    static CTestPulseIO__ThreeStringArgs_t ISchemaClass<CTestPulseIO__ThreeStringArgs_t>.From(nint handle) => new CTestPulseIO__ThreeStringArgs_tImpl(handle);
    static int ISchemaClass<CTestPulseIO__ThreeStringArgs_t>.Size => 24;
    static string? ISchemaClass<CTestPulseIO__ThreeStringArgs_t>.ClassName => null;


    public string StrArg1 { get; set; }

    public string StrArg2 { get; set; }

    public string StrArg3 { get; set; }


}