// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CTestPulseIOComponent_Derived : CTestPulseIOComponent, ISchemaClass<CTestPulseIOComponent_Derived>
{
    static CTestPulseIOComponent_Derived ISchemaClass<CTestPulseIOComponent_Derived>.From(nint handle) => new CTestPulseIOComponent_DerivedImpl(handle);
    static int ISchemaClass<CTestPulseIOComponent_Derived>.Size => 48;
    static string? ISchemaClass<CTestPulseIOComponent_Derived>.ClassName => null;

}