// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CTestPulseIO__EntityHandleIntArgs_t : ISchemaClass<CTestPulseIO__EntityHandleIntArgs_t>
{
    static CTestPulseIO__EntityHandleIntArgs_t ISchemaClass<CTestPulseIO__EntityHandleIntArgs_t>.From(nint handle) => new CTestPulseIO__EntityHandleIntArgs_tImpl(handle);
    static int ISchemaClass<CTestPulseIO__EntityHandleIntArgs_t>.Size => 8;
    static string? ISchemaClass<CTestPulseIO__EntityHandleIntArgs_t>.ClassName => null;


    public ref CHandle<CEntityInstance> HandleA { get; }

    public ref int ValueB { get; }


}