// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CTestPulseIO__EntityNameStringArgs_t : ISchemaClass<CTestPulseIO__EntityNameStringArgs_t>
{
    static CTestPulseIO__EntityNameStringArgs_t ISchemaClass<CTestPulseIO__EntityNameStringArgs_t>.From(nint handle) => new CTestPulseIO__EntityNameStringArgs_tImpl(handle);
    static int ISchemaClass<CTestPulseIO__EntityNameStringArgs_t>.Size => 16;
    static string? ISchemaClass<CTestPulseIO__EntityNameStringArgs_t>.ClassName => null;


    // CEntityNameString
    public SchemaUntypedField NameA { get; }

    public string StrValueB { get; set; }


}