// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CTestPulseIO : CLogicalEntity, ISchemaClass<CTestPulseIO>
{
    static CTestPulseIO ISchemaClass<CTestPulseIO>.From(nint handle) => new CTestPulseIOImpl(handle);
    static int ISchemaClass<CTestPulseIO>.Size => 1952;
    static string? ISchemaClass<CTestPulseIO>.ClassName => "test_io_combinations";


    public ref CEntityIOOutput OnVariantVoid { get; }

    // CEntityOutputTemplate< bool >
    public SchemaUntypedField OnVariantBool { get; }

    // CEntityOutputTemplate< int32 >
    public SchemaUntypedField OnVariantInt { get; }

    // CEntityOutputTemplate< float32 >
    public SchemaUntypedField OnVariantFloat { get; }

    // CEntityOutputTemplate< CUtlSymbolLarge >
    public SchemaUntypedField OnVariantString { get; }

    // CEntityOutputTemplate< Color >
    public SchemaUntypedField OnVariantColor { get; }

    // CEntityOutputTemplate< Vector >
    public SchemaUntypedField OnVariantVector { get; }

    public ref bool AllowEmptyInputs { get; }

    public CTestPulseIOComponent_Derived TestComponent { get; }

    public ref CEntityIOOutput OnInternalTestVoid { get; }

    // CEntityOutputTemplate< bool >
    public SchemaUntypedField OnInternalTestBool { get; }

    // CEntityOutputTemplate< int32 >
    public SchemaUntypedField OnInternalTestInt { get; }

    // CEntityOutputTemplate< float32 >
    public SchemaUntypedField OnInternalTestFloat { get; }

    // CEntityOutputTemplate< CUtlSymbolLarge >
    public SchemaUntypedField OnInternalTestString { get; }

    // CEntityOutputTemplate< Color >
    public SchemaUntypedField OnInternalTestColor { get; }

    // CEntityOutputTemplate< Vector >
    public SchemaUntypedField OnInternalTestVector { get; }

    // CEntityOutputTemplate< CEntityNameString >
    public SchemaUntypedField OnInternalTestEntityName { get; }

    // CEntityOutputTemplate< CHandle< CBaseEntity > >
    public SchemaUntypedField OnInternalTestEntityHandle { get; }

    // CEntityOutputTemplate< TestInputOutputCombinationsEnum_t >
    public SchemaUntypedField OnInternalTestSchemaEnum { get; }

    // CEntityOutputTemplate< CTestPulseIO::FloatStringArgs_t >
    public SchemaUntypedField OnInternalTestFloatString { get; }

    // CEntityOutputTemplate< CTestPulseIO::EntityNameStringArgs_t >
    public SchemaUntypedField OnInternalTestEntityNameString { get; }

    // CEntityOutputTemplate< CTestPulseIO::EntityHandleIntArgs_t >
    public SchemaUntypedField OnInternalTestEntityHandleInt { get; }

    // CEntityOutputTemplate< CTestPulseIO::ThreeStringArgs_t >
    public SchemaUntypedField OnInternalTestStringStringString { get; }


}