// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CTestPulseIOComponent_API : ISchemaClass<CTestPulseIOComponent_API>
{
    static CTestPulseIOComponent_API ISchemaClass<CTestPulseIOComponent_API>.From(nint handle) => new CTestPulseIOComponent_APIImpl(handle);
    static int ISchemaClass<CTestPulseIOComponent_API>.Size => 8;
    static string? ISchemaClass<CTestPulseIOComponent_API>.ClassName => null;

}