// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CTestPulseIOComponent : ISchemaClass<CTestPulseIOComponent>
{
    static CTestPulseIOComponent ISchemaClass<CTestPulseIOComponent>.From(nint handle) => new CTestPulseIOComponentImpl(handle);
    static int ISchemaClass<CTestPulseIOComponent>.Size => 48;
    static string? ISchemaClass<CTestPulseIOComponent>.ClassName => null;


    public string ComponentData { get; set; }

    // CEntityOutputTemplate< CUtlSymbolLarge >
    public SchemaUntypedField OnComponentTestFunc { get; }


}