// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CTestPulseIOComponent_DerivedAPI : ISchemaClass<CTestPulseIOComponent_DerivedAPI>
{
    static CTestPulseIOComponent_DerivedAPI ISchemaClass<CTestPulseIOComponent_DerivedAPI>.From(nint handle) => new CTestPulseIOComponent_DerivedAPIImpl(handle);
    static int ISchemaClass<CTestPulseIOComponent_DerivedAPI>.Size => 8;
    static string? ISchemaClass<CTestPulseIOComponent_DerivedAPI>.ClassName => null;

}