// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CTestPulseIO__FloatStringArgs_t : ISchemaClass<CTestPulseIO__FloatStringArgs_t>
{
    static CTestPulseIO__FloatStringArgs_t ISchemaClass<CTestPulseIO__FloatStringArgs_t>.From(nint handle) => new CTestPulseIO__FloatStringArgs_tImpl(handle);
    static int ISchemaClass<CTestPulseIO__FloatStringArgs_t>.Size => 16;
    static string? ISchemaClass<CTestPulseIO__FloatStringArgs_t>.ClassName => null;


    public ref float OutFloat { get; }

    public string StrOutString { get; set; }


}