// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CTurnHelperInstanceData : ISchemaClass<CTurnHelperInstanceData>
{
    static CTurnHelperInstanceData ISchemaClass<CTurnHelperInstanceData>.From(nint handle) => new CTurnHelperInstanceDataImpl(handle);
    static int ISchemaClass<CTurnHelperInstanceData>.Size => 12;
    static string? ISchemaClass<CTurnHelperInstanceData>.ClassName => null;


    public ref float TurnAmount { get; }

    public ref float TurnStartTime { get; }

    public ref float Duration { get; }


}