// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CWayPointHelperInstanceData : ISchemaClass<CWayPointHelperInstanceData>
{
    static CWayPointHelperInstanceData ISchemaClass<CWayPointHelperInstanceData>.From(nint handle) => new CWayPointHelperInstanceDataImpl(handle);
    static int ISchemaClass<CWayPointHelperInstanceData>.Size => 40;
    static string? ISchemaClass<CWayPointHelperInstanceData>.ClassName => null;


    public ref Vector Movement { get; }

    public ref QAngle Rotation { get; }

    public ref Vector WaypointPosWS { get; }

    public ref bool StopUpdatingWaypointPos { get; }


}