// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface DampedPathMotorInstanceData_t : ISchemaClass<DampedPathMotorInstanceData_t>
{
    static DampedPathMotorInstanceData_t ISchemaClass<DampedPathMotorInstanceData_t>.From(nint handle) => new DampedPathMotorInstanceData_tImpl(handle);
    static int ISchemaClass<DampedPathMotorInstanceData_t>.Size => 40;
    static string? ISchemaClass<DampedPathMotorInstanceData_t>.ClassName => null;


    public ref Vector Velocity { get; }

    public ref Vector Acceleration { get; }

    public ref bool Stopping { get; }


}