// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface DebugSnapshotBaseStructuredData_t : ISchemaClass<DebugSnapshotBaseStructuredData_t>
{
    static DebugSnapshotBaseStructuredData_t ISchemaClass<DebugSnapshotBaseStructuredData_t>.From(nint handle) => new DebugSnapshotBaseStructuredData_tImpl(handle);
    static int ISchemaClass<DebugSnapshotBaseStructuredData_t>.Size => 8;
    static string? ISchemaClass<DebugSnapshotBaseStructuredData_t>.ClassName => null;

}