// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface DebugDrawBoneTransforms_t : DebugSnapshotBaseStructuredData_t, ISchemaClass<DebugDrawBoneTransforms_t>
{
    static DebugDrawBoneTransforms_t ISchemaClass<DebugDrawBoneTransforms_t>.From(nint handle) => new DebugDrawBoneTransforms_tImpl(handle);
    static int ISchemaClass<DebugDrawBoneTransforms_t>.Size => 4144;
    static string? ISchemaClass<DebugDrawBoneTransforms_t>.ClassName => null;


    // CUtlVectorFixedGrowable< CTransform, 128 >
    public SchemaUntypedField Bones { get; }


}