// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface DestructiblePartDamageRequestAPI : ISchemaClass<DestructiblePartDamageRequestAPI>
{
    static DestructiblePartDamageRequestAPI ISchemaClass<DestructiblePartDamageRequestAPI>.From(nint handle) => new DestructiblePartDamageRequestAPIImpl(handle);
    static int ISchemaClass<DestructiblePartDamageRequestAPI>.Size => 8;
    static string? ISchemaClass<DestructiblePartDamageRequestAPI>.ClassName => null;

}