// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface DestructiblePartDamageRequest_t : ISchemaClass<DestructiblePartDamageRequest_t>
{
    static DestructiblePartDamageRequest_t ISchemaClass<DestructiblePartDamageRequest_t>.From(nint handle) => new DestructiblePartDamageRequest_tImpl(handle);
    static int ISchemaClass<DestructiblePartDamageRequest_t>.Size => 56;
    static string? ISchemaClass<DestructiblePartDamageRequest_t>.ClassName => null;


    public ref HitGroup_t HitGroup { get; }

    public ref int DamageLevel { get; }

    public ref ushort DesiredHealth { get; }

    public ref EDestructibleParts_DestroyParameterFlags DestroyFlags { get; }

    public ref DamageTypes_t DamageType { get; }

    public ref float BreakDamage { get; }

    public ref float BreakDamageRadius { get; }

    public ref Vector WsBreakDamageOrigin { get; }

    public ref Vector WsBreakDamageForce { get; }


}