// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface entitytable_t : ISchemaClass<entitytable_t>
{
    static entitytable_t ISchemaClass<entitytable_t>.From(nint handle) => new entitytable_tImpl(handle);
    static int ISchemaClass<entitytable_t>.Size => 80;
    static string? ISchemaClass<entitytable_t>.ClassName => null;


    public ref int Id { get; }

    public ref uint Edictindex { get; }

    public ref uint Saveentityindex { get; }

    public ref bool WasSaved { get; }

    public ref SaveRestoreTableFlags_t Flags { get; }

    public string Classname { get; set; }

    public string Globalname { get; set; }

    public string Entityname { get; set; }

    public ref Vector LandmarkModelSpace { get; }

    // CEntityKeyValues
    public SchemaUntypedField PrecacheEntityKeys { get; }


}