// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface FuncMoverMovementSummary_t : ISchemaClass<FuncMoverMovementSummary_t>
{
    static FuncMoverMovementSummary_t ISchemaClass<FuncMoverMovementSummary_t>.From(nint handle) => new FuncMoverMovementSummary_tImpl(handle);
    static int ISchemaClass<FuncMoverMovementSummary_t>.Size => 32;
    static string? ISchemaClass<FuncMoverMovementSummary_t>.ClassName => null;


    public ref float StartT { get; }

    public ref float EndT { get; }

    public ref int StartNodeIndex { get; }

    public ref int StopNodeIndex { get; }

    public ref int MovementMode { get; }

    public ref FuncMoverMovementSummaryFlags_t Flags { get; }

    public GameTick_t Tick { get; }

    public ref CHandle<CPathMover> PathMover { get; }


}