// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface GAME_HEADER : ISchemaClass<GAME_HEADER>
{
    static GAME_HEADER ISchemaClass<GAME_HEADER>.From(nint handle) => new GAME_HEADERImpl(handle);
    static int ISchemaClass<GAME_HEADER>.Size => 32;
    static string? ISchemaClass<GAME_HEADER>.ClassName => null;


    public string Comment { get; set; }

    public ref int SpawnGroupCount { get; }

    public string Landmark { get; set; }

    public string RequiredAddons { get; set; }


}