// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface globalentity_t : ISchemaClass<globalentity_t>
{
    static globalentity_t ISchemaClass<globalentity_t>.From(nint handle) => new globalentity_tImpl(handle);
    static int ISchemaClass<globalentity_t>.Size => 12;
    static string? ISchemaClass<globalentity_t>.ClassName => null;


    // CUtlSymbol
    public SchemaUntypedField Name { get; }

    // CUtlSymbol
    public SchemaUntypedField LevelName { get; }

    public ref GLOBALESTATE State { get; }

    public ref int Counter { get; }


}