// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface INavObstacle : ISchemaClass<INavObstacle>
{
    static INavObstacle ISchemaClass<INavObstacle>.From(nint handle) => new INavObstacleImpl(handle);
    static int ISchemaClass<INavObstacle>.Size => 16;
    static string? ISchemaClass<INavObstacle>.ClassName => null;


    public ref ulong Id { get; }


}