// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface InfoForResourceTypeCVDataItemDefs : ISchemaClass<InfoForResourceTypeCVDataItemDefs>
{
    static InfoForResourceTypeCVDataItemDefs ISchemaClass<InfoForResourceTypeCVDataItemDefs>.From(nint handle) => new InfoForResourceTypeCVDataItemDefsImpl(handle);
    static int ISchemaClass<InfoForResourceTypeCVDataItemDefs>.Size => 1;
    static string? ISchemaClass<InfoForResourceTypeCVDataItemDefs>.ClassName => null;

}