// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface IPhysicsMotionController : ISchemaClass<IPhysicsMotionController>
{
    static IPhysicsMotionController ISchemaClass<IPhysicsMotionController>.From(nint handle) => new IPhysicsMotionControllerImpl(handle);
    static int ISchemaClass<IPhysicsMotionController>.Size => 8;
    static string? ISchemaClass<IPhysicsMotionController>.ClassName => null;

}