// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface IPhysicsBodyList : ISchemaClass<IPhysicsBodyList>
{
    static IPhysicsBodyList ISchemaClass<IPhysicsBodyList>.From(nint handle) => new IPhysicsBodyListImpl(handle);
    static int ISchemaClass<IPhysicsBodyList>.Size => 8;
    static string? ISchemaClass<IPhysicsBodyList>.ClassName => null;

}