// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface IPhysicsParticleRope : ISchemaClass<IPhysicsParticleRope>
{
    static IPhysicsParticleRope ISchemaClass<IPhysicsParticleRope>.From(nint handle) => new IPhysicsParticleRopeImpl(handle);
    static int ISchemaClass<IPhysicsParticleRope>.Size => 8;
    static string? ISchemaClass<IPhysicsParticleRope>.ClassName => null;

}