// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface IPhysAggregateInstance : IPhysicsBodyList, ISchemaClass<IPhysAggregateInstance>
{
    static IPhysAggregateInstance ISchemaClass<IPhysAggregateInstance>.From(nint handle) => new IPhysAggregateInstanceImpl(handle);
    static int ISchemaClass<IPhysAggregateInstance>.Size => 24;
    static string? ISchemaClass<IPhysAggregateInstance>.ClassName => null;


    // void
    public SchemaUntypedField Skeleton { get; }

    public ref bool IsAxisAligned { get; }


}