// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface IPhysicsBody : ISchemaClass<IPhysicsBody>
{
    static IPhysicsBody ISchemaClass<IPhysicsBody>.From(nint handle) => new IPhysicsBodyImpl(handle);
    static int ISchemaClass<IPhysicsBody>.Size => 8;
    static string? ISchemaClass<IPhysicsBody>.ClassName => null;

}