// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface IPhysicsRagdollControl : ISchemaClass<IPhysicsRagdollControl>
{
    static IPhysicsRagdollControl ISchemaClass<IPhysicsRagdollControl>.From(nint handle) => new IPhysicsRagdollControlImpl(handle);
    static int ISchemaClass<IPhysicsRagdollControl>.Size => 8;
    static string? ISchemaClass<IPhysicsRagdollControl>.ClassName => null;

}