// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface IPhysicsJoint : ISchemaClass<IPhysicsJoint>
{
    static IPhysicsJoint ISchemaClass<IPhysicsJoint>.From(nint handle) => new IPhysicsJointImpl(handle);
    static int ISchemaClass<IPhysicsJoint>.Size => 8;
    static string? ISchemaClass<IPhysicsJoint>.ClassName => null;

}