// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface ISndSeqInstruments : ISchemaClass<ISndSeqInstruments>
{
    static ISndSeqInstruments ISchemaClass<ISndSeqInstruments>.From(nint handle) => new ISndSeqInstrumentsImpl(handle);
    static int ISchemaClass<ISndSeqInstruments>.Size => 8;
    static string? ISchemaClass<ISndSeqInstruments>.ClassName => null;

}