// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface KeyGroup_t : ISchemaClass<KeyGroup_t>
{
    static KeyGroup_t ISchemaClass<KeyGroup_t>.From(nint handle) => new KeyGroup_tImpl(handle);
    static int ISchemaClass<KeyGroup_t>.Size => 16;
    static string? ISchemaClass<KeyGroup_t>.ClassName => null;


    public ref byte CenterNote { get; }

    public ref byte MinNote { get; }

    public ref byte MaxNote { get; }

    public ref byte NumVelocityZones { get; }

    public VelocityZone_t? VelocityZones { get; }


}