// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface levellist_t : ISchemaClass<levellist_t>
{
    static levellist_t ISchemaClass<levellist_t>.From(nint handle) => new levellist_tImpl(handle);
    static int ISchemaClass<levellist_t>.Size => 48;
    static string? ISchemaClass<levellist_t>.ClassName => null;


    public string MapName { get; set; }

    public string LandmarkName { get; set; }

    public ref CHandle<CEntityInstance> EntLandmark { get; }

    public ref Vector LandmarkOrigin { get; }

    public ref QAngle LandmarkAngles { get; }


}