// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface LookData : ISchemaClass<LookData>
{
    static LookData ISchemaClass<LookData>.From(nint handle) => new LookDataImpl(handle);
    static int ISchemaClass<LookData>.Size => 24;
    static string? ISchemaClass<LookData>.ClassName => null;


    // CAnimNetVar< Vector >
    public SchemaUntypedField LookTarget { get; }


}