// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface modifiedconvars_t : ISchemaClass<modifiedconvars_t>
{
    static modifiedconvars_t ISchemaClass<modifiedconvars_t>.From(nint handle) => new modifiedconvars_tImpl(handle);
    static int ISchemaClass<modifiedconvars_t>.Size => 384;
    static string? ISchemaClass<modifiedconvars_t>.ClassName => null;


    public string Convar { get; set; }

    public string CurrentValue { get; set; }

    public string OrgValue { get; set; }


}