// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface MotionMatchingInstanceData : ISchemaClass<MotionMatchingInstanceData>
{
    static MotionMatchingInstanceData ISchemaClass<MotionMatchingInstanceData>.From(nint handle) => new MotionMatchingInstanceDataImpl(handle);
    static int ISchemaClass<MotionMatchingInstanceData>.Size => 288;
    static string? ISchemaClass<MotionMatchingInstanceData>.ClassName => null;


    public MotionSelection CurrentSelection { get; }

    public MotionSelection PreviousSelection { get; }


}