// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface MotionSelection : ISchemaClass<MotionSelection>
{
    static MotionSelection ISchemaClass<MotionSelection>.From(nint handle) => new MotionSelectionImpl(handle);
    static int ISchemaClass<MotionSelection>.Size => 88;
    static string? ISchemaClass<MotionSelection>.ClassName => null;


    public NetVarConfigIndex ConfigIndex { get; }

    // CAnimNetVar< float32 >
    public SchemaUntypedField CycleZeroTime { get; }

    // CAnimNetVar< float32 >
    public SchemaUntypedField PlaybackSpeed { get; }

    // CAnimNetVar< float32 >
    public SchemaUntypedField StartTime { get; }

    public ref int Sample { get; }


}