// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface MovementData : ISchemaClass<MovementData>
{
    static MovementData ISchemaClass<MovementData>.From(nint handle) => new MovementDataImpl(handle);
    static int ISchemaClass<MovementData>.Size => 232;
    static string? ISchemaClass<MovementData>.ClassName => null;


    public ref Vector GoalWayPointPos { get; }

    // CAnimNetVar< Vector >
    public SchemaUntypedField MoveDir { get; }

    // CAnimNetVar< Vector >
    public SchemaUntypedField Acceleration { get; }

    // CAnimNetVar< float32 >
    public SchemaUntypedField CurrentMoveSpeed { get; }

    // CAnimNetVar< float32 >
    public SchemaUntypedField TargetMoveSpeed { get; }

    // CAnimNetVar< float32 >
    public SchemaUntypedField GoalDistance { get; }

    // CAnimNetVar< float32 >
    public SchemaUntypedField BoundaryRadius { get; }

    public ref bool GoalChanged { get; }

    // CAnimNetVar< bool >
    public SchemaUntypedField HasPath { get; }

    // CAnimNetVar< float32 >
    public SchemaUntypedField FacingHeading { get; }

    public ref Vector ManualFacingDirection { get; }

    public ref Vector ManualFacingTarget { get; }

    // CAnimNetVar< uint8 >
    public SchemaUntypedField FacingMode { get; }

    // CAnimNetVar< bool >
    public SchemaUntypedField ForceFacing { get; }

    // CAnimNetVar< int32 >
    public SchemaUntypedField ActiveMotorIndex { get; }

    // CAnimNetVar< bool >
    public SchemaUntypedField OnGround { get; }

    // CAnimNetVar< Vector >
    public SchemaUntypedField FacingPosition { get; }

    public ref Vector PrevFacingPosition { get; }


}