// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface NavHull_t : ISchemaClass<NavHull_t>
{
    static NavHull_t ISchemaClass<NavHull_t>.From(nint handle) => new NavHull_tImpl(handle);
    static int ISchemaClass<NavHull_t>.Size => 4;
    static string? ISchemaClass<NavHull_t>.ClassName => null;


    public ref int HullIdx { get; }


}