// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface NetVarConfigIndex : ISchemaClass<NetVarConfigIndex>
{
    static NetVarConfigIndex ISchemaClass<NetVarConfigIndex>.From(nint handle) => new NetVarConfigIndexImpl(handle);
    static int ISchemaClass<NetVarConfigIndex>.Size => 12;
    static string? ISchemaClass<NetVarConfigIndex>.ClassName => null;


    // CAnimNetVar< uint32 >
    public SchemaUntypedField Index { get; }


}