// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface PairedSequenceData : ISchemaClass<PairedSequenceData>
{
    static PairedSequenceData ISchemaClass<PairedSequenceData>.From(nint handle) => new PairedSequenceDataImpl(handle);
    static int ISchemaClass<PairedSequenceData>.Size => 256;
    static string? ISchemaClass<PairedSequenceData>.ClassName => null;


    public ISchemaClassFixedArray<PairedSequence_t> PairedSequences { get; }


}