// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface PairedSequence_t : ISchemaClass<PairedSequence_t>
{
    static PairedSequence_t ISchemaClass<PairedSequence_t>.From(nint handle) => new PairedSequence_tImpl(handle);
    static int ISchemaClass<PairedSequence_t>.Size => 32;
    static string? ISchemaClass<PairedSequence_t>.ClassName => null;


    public ref CGlobalSymbol Role { get; }

    public ref CGlobalSymbol SequenceName { get; }

    // CAnimNetVar< uint32 >
    public SchemaUntypedField Sequence { get; }


}