// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface PerTickSettings_t : ISchemaClass<PerTickSettings_t>
{
    static PerTickSettings_t ISchemaClass<PerTickSettings_t>.From(nint handle) => new PerTickSettings_tImpl(handle);
    static int ISchemaClass<PerTickSettings_t>.Size => 1728;
    static string? ISchemaClass<PerTickSettings_t>.ClassName => null;


    public ref CTransform StartingLocalToWorld { get; }

    public ref CTransform PrevLocalToWorld { get; }

    public ref CTransform FinalLocalToWorld { get; }

    public CRootMotion RootMotion { get; }

    public ref int UpdateID { get; }

    public ref float LastTimeStep { get; }

    public ref float PrevAnimTime { get; }

    public ref float NextAnimTime { get; }

    public ref bool Awaken { get; }

    public ref bool Teleported { get; }

    public ref bool IsClient { get; }

    public ref bool IsPredicted { get; }


}