// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface physics_save_sphere_t : ISchemaClass<physics_save_sphere_t>
{
    static physics_save_sphere_t ISchemaClass<physics_save_sphere_t>.From(nint handle) => new physics_save_sphere_tImpl(handle);
    static int ISchemaClass<physics_save_sphere_t>.Size => 4;
    static string? ISchemaClass<physics_save_sphere_t>.ClassName => null;


    public ref float Radius { get; }


}