// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface PhysObjectHeader_t : ISchemaClass<PhysObjectHeader_t>
{
    static PhysObjectHeader_t ISchemaClass<PhysObjectHeader_t>.From(nint handle) => new PhysObjectHeader_tImpl(handle);
    static int ISchemaClass<PhysObjectHeader_t>.Size => 64;
    static string? ISchemaClass<PhysObjectHeader_t>.ClassName => null;


    public ref PhysInterfaceId_t Type { get; }

    public ref CHandle<CBaseEntity> Entity { get; }

    public string FieldName { get; set; }

    public ref int Objects { get; }

    public string ModelName { get; set; }

    public AABB_t Bbox { get; }

    public physics_save_sphere_t Sphere { get; }

    public ref int Collide { get; }


}