// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface PhysBlockHeader_t : ISchemaClass<PhysBlockHeader_t>
{
    static PhysBlockHeader_t ISchemaClass<PhysBlockHeader_t>.From(nint handle) => new PhysBlockHeader_tImpl(handle);
    static int ISchemaClass<PhysBlockHeader_t>.Size => 16;
    static string? ISchemaClass<PhysBlockHeader_t>.ClassName => null;


    public ref int Saved { get; }

    public ref ulong WorldObject { get; }


}