// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface PlayerInputMotorInstanceData_t : ISchemaClass<PlayerInputMotorInstanceData_t>
{
    static PlayerInputMotorInstanceData_t ISchemaClass<PlayerInputMotorInstanceData_t>.From(nint handle) => new PlayerInputMotorInstanceData_tImpl(handle);
    static int ISchemaClass<PlayerInputMotorInstanceData_t>.Size => 40;
    static string? ISchemaClass<PlayerInputMotorInstanceData_t>.ClassName => null;


    public ref Vector InputVectorWS { get; }

    public ref Vector VelocityWS { get; }

    public ref Vector AccelerationWS { get; }


}