// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface PrecipitationFilter_t : ISchemaClass<PrecipitationFilter_t>
{
    static PrecipitationFilter_t ISchemaClass<PrecipitationFilter_t>.From(nint handle) => new PrecipitationFilter_tImpl(handle);
    static int ISchemaClass<PrecipitationFilter_t>.Size => 4;
    static string? ISchemaClass<PrecipitationFilter_t>.ClassName => null;


    public ref float MaxRadius { get; }


}