// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface SamplerVoice_t : ISchemaClass<SamplerVoice_t>
{
    static SamplerVoice_t ISchemaClass<SamplerVoice_t>.From(nint handle) => new SamplerVoice_tImpl(handle);
    static int ISchemaClass<SamplerVoice_t>.Size => 8;
    static string? ISchemaClass<SamplerVoice_t>.ClassName => null;


    public ref byte NoteNum { get; }


}