// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface SAVE_HEADER : ISchemaClass<SAVE_HEADER>
{
    static SAVE_HEADER ISchemaClass<SAVE_HEADER>.From(nint handle) => new SAVE_HEADERImpl(handle);
    static int ISchemaClass<SAVE_HEADER>.Size => 96;
    static string? ISchemaClass<SAVE_HEADER>.ClassName => null;


    public ref int SaveId { get; }

    public ref int Version { get; }

    public ref int ConnectionCount { get; }

    public ref int MapVersion { get; }

    public string SpawnGroupName { get; set; }

    public ref matrix3x4_t WorldOffset { get; }

    public ref float SaveTime { get; }


}