// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface SceneInterestTags_t : ISchemaClass<SceneInterestTags_t>
{
    static SceneInterestTags_t ISchemaClass<SceneInterestTags_t>.From(nint handle) => new SceneInterestTags_tImpl(handle);
    static int ISchemaClass<SceneInterestTags_t>.Size => 24;
    static string? ISchemaClass<SceneInterestTags_t>.ClassName => null;


    public ref CUtlVector<CUtlString> Tags { get; }


}