// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface SceneOpportunityActor_t : ISchemaClass<SceneOpportunityActor_t>
{
    static SceneOpportunityActor_t ISchemaClass<SceneOpportunityActor_t>.From(nint handle) => new SceneOpportunityActor_tImpl(handle);
    static int ISchemaClass<SceneOpportunityActor_t>.Size => 48;
    static string? ISchemaClass<SceneOpportunityActor_t>.ClassName => null;


    public ref CHandle<CBaseModelEntity> Actor { get; }

    public ref bool DynamicActor { get; }

    public ref bool Anchor { get; }

    public string StrActorName { get; set; }

    public string StrEntityName { get; set; }

    public SceneInterestTags_t InterestTags { get; }


}