// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface SceneRequestTargetMapPair_t : ISchemaClass<SceneRequestTargetMapPair_t>
{
    static SceneRequestTargetMapPair_t ISchemaClass<SceneRequestTargetMapPair_t>.From(nint handle) => new SceneRequestTargetMapPair_tImpl(handle);
    static int ISchemaClass<SceneRequestTargetMapPair_t>.Size => 16;
    static string? ISchemaClass<SceneRequestTargetMapPair_t>.ClassName => null;


    public string ActorName { get; set; }

    public string TargetName { get; set; }


}