// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface SceneOpportunityHandle_t : ISchemaClass<SceneOpportunityHandle_t>
{
    static SceneOpportunityHandle_t ISchemaClass<SceneOpportunityHandle_t>.From(nint handle) => new SceneOpportunityHandle_tImpl(handle);
    static int ISchemaClass<SceneOpportunityHandle_t>.Size => 4;
    static string? ISchemaClass<SceneOpportunityHandle_t>.ClassName => null;


    public ref int Value { get; }


}