// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface SelectorInstanceData_t : ISchemaClass<SelectorInstanceData_t>
{
    static SelectorInstanceData_t ISchemaClass<SelectorInstanceData_t>.From(nint handle) => new SelectorInstanceData_tImpl(handle);
    static int ISchemaClass<SelectorInstanceData_t>.Size => 44;
    static string? ISchemaClass<SelectorInstanceData_t>.ClassName => null;


    // CRelativeArray< float32 >
    public SchemaUntypedField Weights { get; }

    // CAnimNetVar< float32 >
    public SchemaUntypedField CurrentIndexStartTime { get; }

    public ref int CurrentIndex { get; }

    public ref int PreviousIndex { get; }


}