// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface SequenceData : ISchemaClass<SequenceData>
{
    static SequenceData ISchemaClass<SequenceData>.From(nint handle) => new SequenceDataImpl(handle);
    static int ISchemaClass<SequenceData>.Size => 56;
    static string? ISchemaClass<SequenceData>.ClassName => null;


    public HSequence Sequence { get; }

    public CNetworkedCycle Cycle { get; }


}