// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface SlopeData : ISchemaClass<SlopeData>
{
    static SlopeData ISchemaClass<SlopeData>.From(nint handle) => new SlopeDataImpl(handle);
    static int ISchemaClass<SlopeData>.Size => 12;
    static string? ISchemaClass<SlopeData>.ClassName => null;


    public ref Vector SlopeNormal { get; }


}