// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface SoundCommand_t : ISchemaClass<SoundCommand_t>
{
    static SoundCommand_t ISchemaClass<SoundCommand_t>.From(nint handle) => new SoundCommand_tImpl(handle);
    static int ISchemaClass<SoundCommand_t>.Size => 32;
    static string? ISchemaClass<SoundCommand_t>.ClassName => null;


    public ref float Time { get; }

    public ref float DeltaTime { get; }

    public ref soundcommands_t Command { get; }

    public ref float Value { get; }


}