// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface SPAWNGROUP_HEADER : ISchemaClass<SPAWNGROUP_HEADER>
{
    static SPAWNGROUP_HEADER ISchemaClass<SPAWNGROUP_HEADER>.From(nint handle) => new SPAWNGROUP_HEADERImpl(handle);
    static int ISchemaClass<SPAWNGROUP_HEADER>.Size => 80;
    static string? ISchemaClass<SPAWNGROUP_HEADER>.ClassName => null;


    public string GroupName { get; set; }

    public string EntityLumpName { get; set; }

    public ref matrix3x4_t WorldOffset { get; }

    public ref bool ClientSpawnGroup { get; }

    public ref bool SuppressAllEntities { get; }


}