// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface TargetSelectorInstanceData_t : ISchemaClass<TargetSelectorInstanceData_t>
{
    static TargetSelectorInstanceData_t ISchemaClass<TargetSelectorInstanceData_t>.From(nint handle) => new TargetSelectorInstanceData_tImpl(handle);
    static int ISchemaClass<TargetSelectorInstanceData_t>.Size => 48;
    static string? ISchemaClass<TargetSelectorInstanceData_t>.ClassName => null;


    // CAnimNetVar< int32 >
    public SchemaUntypedField CurrentIndex { get; }

    // CAnimNetVar< Vector >
    public SchemaUntypedField MSRootMotionAnlyzerTarget { get; }


}