// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface TestComponent_t : ISchemaClass<TestComponent_t>
{
    static TestComponent_t ISchemaClass<TestComponent_t>.From(nint handle) => new TestComponent_tImpl(handle);
    static int ISchemaClass<TestComponent_t>.Size => 16;
    static string? ISchemaClass<TestComponent_t>.ClassName => null;


    public string ComponentData { get; set; }


}