// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface TestComponent_tAPI : ISchemaClass<TestComponent_tAPI>
{
    static TestComponent_tAPI ISchemaClass<TestComponent_tAPI>.From(nint handle) => new TestComponent_tAPIImpl(handle);
    static int ISchemaClass<TestComponent_tAPI>.Size => 8;
    static string? ISchemaClass<TestComponent_tAPI>.ClassName => null;

}