// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface VelocityZone_t : ISchemaClass<VelocityZone_t>
{
    static VelocityZone_t ISchemaClass<VelocityZone_t>.From(nint handle) => new VelocityZone_tImpl(handle);
    static int ISchemaClass<VelocityZone_t>.Size => 20;
    static string? ISchemaClass<VelocityZone_t>.ClassName => null;


    public ref byte MaxVel { get; }

    public ref byte NextSelection { get; }

    public ref byte NumSamples { get; }

    public ISchemaFixedArray<uint> Samples { get; }


}