// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface vphysics_save_ragdoll_control_t : ISchemaClass<vphysics_save_ragdoll_control_t>
{
    static vphysics_save_ragdoll_control_t ISchemaClass<vphysics_save_ragdoll_control_t>.From(nint handle) => new vphysics_save_ragdoll_control_tImpl(handle);
    static int ISchemaClass<vphysics_save_ragdoll_control_t>.Size => 56;
    static string? ISchemaClass<vphysics_save_ragdoll_control_t>.ClassName => null;


    public ref float MinSpringFrequency { get; }

    public ref float MaxSpringFrequency { get; }

    public ref float MaxStretch { get; }

    public ref bool SolidCollisionAtZeroWeight { get; }

    public ref bool RequiresDynamicBodies { get; }

    public ref bool IgnoreTeleport { get; }

    public ref Vector LinearVelocityAccumulator { get; }

    // RotationVector
    public SchemaUntypedField AngularVelocityAccumulator { get; }

    public ref Vector ForceAccumulator { get; }

    public ref int BodyCount { get; }


}