// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class AI_BaseNPCAnimGraph_DebugSnapshotData_tImpl : DebugSnapshotBaseStructuredData_tImpl, AI_BaseNPCAnimGraph_DebugSnapshotData_t
{
    public AI_BaseNPCAnimGraph_DebugSnapshotData_tImpl(nint handle) : base(handle) { }

    private static nint? _E_action_desiredOffset;

    public ref CGlobalSymbol E_action_desired
    {
        get
        {
            _E_action_desiredOffset = _E_action_desiredOffset ?? Schema.GetOffset(0xC191B83C18A816AA);
            return ref _Handle.AsRef<CGlobalSymbol>(_E_action_desiredOffset!.Value);
        }
    }
    private static nint? _B_action_restartOffset;

    public ref bool B_action_restart
    {
        get
        {
            _B_action_restartOffset = _B_action_restartOffset ?? Schema.GetOffset(0xC191B83C8FAD0708);
            return ref _Handle.AsRef<bool>(_B_action_restartOffset!.Value);
        }
    }
    private static nint? _E_movement_type_desiredOffset;

    public ref CGlobalSymbol E_movement_type_desired
    {
        get
        {
            _E_movement_type_desiredOffset = _E_movement_type_desiredOffset ?? Schema.GetOffset(0xC191B83C3F404754);
            return ref _Handle.AsRef<CGlobalSymbol>(_E_movement_type_desiredOffset!.Value);
        }
    }
    private static nint? _B_movement_type_restartOffset;

    public ref bool B_movement_type_restart
    {
        get
        {
            _B_movement_type_restartOffset = _B_movement_type_restartOffset ?? Schema.GetOffset(0xC191B83C5C9C443C);
            return ref _Handle.AsRef<bool>(_B_movement_type_restartOffset!.Value);
        }
    }

}