// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class AI_BaseNPC_DebugSnapshotData_tImpl : DebugSnapshotBaseStructuredData_tImpl, AI_BaseNPC_DebugSnapshotData_t
{
    public AI_BaseNPC_DebugSnapshotData_tImpl(nint handle) : base(handle) { }

    private static nint? _Npc_stateOffset;

    public ref CGlobalSymbol Npc_state
    {
        get
        {
            _Npc_stateOffset = _Npc_stateOffset ?? Schema.GetOffset(0x92164B5757DA063E);
            return ref _Handle.AsRef<CGlobalSymbol>(_Npc_stateOffset!.Value);
        }
    }
    private static nint? _Current_enemyOffset;

    public ref CHandle<CBaseEntity> Current_enemy
    {
        get
        {
            _Current_enemyOffset = _Current_enemyOffset ?? Schema.GetOffset(0x92164B573B77EA5D);
            return ref _Handle.AsRef<CHandle<CBaseEntity>>(_Current_enemyOffset!.Value);
        }
    }
    private static nint? _S_current_scheduleOffset;

    public string S_current_schedule
    {
        get
        {
            _S_current_scheduleOffset = _S_current_scheduleOffset ?? Schema.GetOffset(0x92164B577C36272C);
            return Schema.GetCUtlString(_Handle.Read<nint>(_S_current_scheduleOffset!.Value));
        }
        set
        {
            _S_current_scheduleOffset = _S_current_scheduleOffset ?? Schema.GetOffset(0x92164B577C36272C);
            Schema.SetCUtlString(_Handle, _S_current_scheduleOffset!.Value, value);
        }
    }
    private static nint? _S_current_taskOffset;

    public ref CGlobalSymbol S_current_task
    {
        get
        {
            _S_current_taskOffset = _S_current_taskOffset ?? Schema.GetOffset(0x92164B573CBAABCC);
            return ref _Handle.AsRef<CGlobalSymbol>(_S_current_taskOffset!.Value);
        }
    }
    private static nint? _S_schedule_interrupt_reasonOffset;

    public string S_schedule_interrupt_reason
    {
        get
        {
            _S_schedule_interrupt_reasonOffset = _S_schedule_interrupt_reasonOffset ?? Schema.GetOffset(0x92164B577BAA861F);
            return Schema.GetCUtlString(_Handle.Read<nint>(_S_schedule_interrupt_reasonOffset!.Value));
        }
        set
        {
            _S_schedule_interrupt_reasonOffset = _S_schedule_interrupt_reasonOffset ?? Schema.GetOffset(0x92164B577BAA861F);
            Schema.SetCUtlString(_Handle, _S_schedule_interrupt_reasonOffset!.Value, value);
        }
    }
    private static nint? _S_schedule_fail_reasonOffset;

    public string S_schedule_fail_reason
    {
        get
        {
            _S_schedule_fail_reasonOffset = _S_schedule_fail_reasonOffset ?? Schema.GetOffset(0x92164B575216E5D4);
            return Schema.GetCUtlString(_Handle.Read<nint>(_S_schedule_fail_reasonOffset!.Value));
        }
        set
        {
            _S_schedule_fail_reasonOffset = _S_schedule_fail_reasonOffset ?? Schema.GetOffset(0x92164B575216E5D4);
            Schema.SetCUtlString(_Handle, _S_schedule_fail_reasonOffset!.Value, value);
        }
    }
    private static nint? _ConditionsOffset;

    public ref CUtlVector<CGlobalSymbol> Conditions
    {
        get
        {
            _ConditionsOffset = _ConditionsOffset ?? Schema.GetOffset(0x92164B5780E0D0B7);
            return ref _Handle.AsRef<CUtlVector<CGlobalSymbol>>(_ConditionsOffset!.Value);
        }
    }
    private static nint? _Anim_eventsOffset;

    public ref CUtlVector<CGlobalSymbol> Anim_events
    {
        get
        {
            _Anim_eventsOffset = _Anim_eventsOffset ?? Schema.GetOffset(0x92164B5772C71F2C);
            return ref _Handle.AsRef<CUtlVector<CGlobalSymbol>>(_Anim_eventsOffset!.Value);
        }
    }
    private static nint? _E_action_body_sectionOffset;

    public ref CGlobalSymbol E_action_body_section
    {
        get
        {
            _E_action_body_sectionOffset = _E_action_body_sectionOffset ?? Schema.GetOffset(0x92164B577B8FC620);
            return ref _Handle.AsRef<CGlobalSymbol>(_E_action_body_sectionOffset!.Value);
        }
    }
    private static nint? _E_movement_body_sectionOffset;

    public ref CGlobalSymbol E_movement_body_section
    {
        get
        {
            _E_movement_body_sectionOffset = _E_movement_body_sectionOffset ?? Schema.GetOffset(0x92164B5725F85AA9);
            return ref _Handle.AsRef<CGlobalSymbol>(_E_movement_body_sectionOffset!.Value);
        }
    }

}