// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class AI_DefaultNPC_DebugSnapshotData_tImpl : DebugSnapshotBaseStructuredData_tImpl, AI_DefaultNPC_DebugSnapshotData_t
{
    public AI_DefaultNPC_DebugSnapshotData_tImpl(nint handle) : base(handle) { }

    private static nint? _S_npc_current_abilityOffset;

    public ref CGlobalSymbol S_npc_current_ability
    {
        get
        {
            _S_npc_current_abilityOffset = _S_npc_current_abilityOffset ?? Schema.GetOffset(0xADB6DBDFA91835E5);
            return ref _Handle.AsRef<CGlobalSymbol>(_S_npc_current_abilityOffset!.Value);
        }
    }
    private static nint? _S_npc_tactic_currentOffset;

    public ref CGlobalSymbol S_npc_tactic_current
    {
        get
        {
            _S_npc_tactic_currentOffset = _S_npc_tactic_currentOffset ?? Schema.GetOffset(0xADB6DBDF4382C35D);
            return ref _Handle.AsRef<CGlobalSymbol>(_S_npc_tactic_currentOffset!.Value);
        }
    }
    private static nint? _S_npc_tactic_phaseOffset;

    public ref CGlobalSymbol S_npc_tactic_phase
    {
        get
        {
            _S_npc_tactic_phaseOffset = _S_npc_tactic_phaseOffset ?? Schema.GetOffset(0xADB6DBDFC96C15CF);
            return ref _Handle.AsRef<CGlobalSymbol>(_S_npc_tactic_phaseOffset!.Value);
        }
    }
    private static nint? _Tactic_interrupt_conditionsOffset;

    public ref CUtlVector<CGlobalSymbol> Tactic_interrupt_conditions
    {
        get
        {
            _Tactic_interrupt_conditionsOffset = _Tactic_interrupt_conditionsOffset ?? Schema.GetOffset(0xADB6DBDFDC108AB0);
            return ref _Handle.AsRef<CUtlVector<CGlobalSymbol>>(_Tactic_interrupt_conditionsOffset!.Value);
        }
    }
    private static nint? _S_npc_current_movementOffset;

    public string S_npc_current_movement
    {
        get
        {
            _S_npc_current_movementOffset = _S_npc_current_movementOffset ?? Schema.GetOffset(0xADB6DBDF40D0BBF4);
            return Schema.GetCUtlString(_Handle.Read<nint>(_S_npc_current_movementOffset!.Value));
        }
        set
        {
            _S_npc_current_movementOffset = _S_npc_current_movementOffset ?? Schema.GetOffset(0xADB6DBDF40D0BBF4);
            Schema.SetCUtlString(_Handle, _S_npc_current_movementOffset!.Value, value);
        }
    }
    private static nint? _Path_query_scheduleOffset;

    public AI_DefaultNPC_DebugSnapshotData_t__PathQuery_t Path_query_schedule
    {
        get
        {
            _Path_query_scheduleOffset = _Path_query_scheduleOffset ?? Schema.GetOffset(0xADB6DBDFF5614F37);
            return new AI_DefaultNPC_DebugSnapshotData_t__PathQuery_tImpl(_Handle + _Path_query_scheduleOffset!.Value);
        }
    }
    private static nint? _Path_query_tacticOffset;

    public AI_DefaultNPC_DebugSnapshotData_t__PathQuery_t Path_query_tactic
    {
        get
        {
            _Path_query_tacticOffset = _Path_query_tacticOffset ?? Schema.GetOffset(0xADB6DBDF929182E2);
            return new AI_DefaultNPC_DebugSnapshotData_t__PathQuery_tImpl(_Handle + _Path_query_tacticOffset!.Value);
        }
    }
    private static nint? _Path_queries_speculativeOffset;

    public ref CUtlVector<AI_DefaultNPC_DebugSnapshotData_t__PathQuery_t> Path_queries_speculative
    {
        get
        {
            _Path_queries_speculativeOffset = _Path_queries_speculativeOffset ?? Schema.GetOffset(0xADB6DBDF3CB0DFA1);
            return ref _Handle.AsRef<CUtlVector<AI_DefaultNPC_DebugSnapshotData_t__PathQuery_t>>(_Path_queries_speculativeOffset!.Value);
        }
    }

}