// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class AI_DefaultNPC_DebugSnapshotData_t__PathQuery_tImpl : SchemaClass, AI_DefaultNPC_DebugSnapshotData_t__PathQuery_t
{
    public AI_DefaultNPC_DebugSnapshotData_t__PathQuery_tImpl(nint handle) : base(handle) { }

    private static nint? _InitialQueryNameOffset;

    public ref CGlobalSymbol InitialQueryName
    {
        get
        {
            _InitialQueryNameOffset = _InitialQueryNameOffset ?? Schema.GetOffset(0x694C69B77F206BB9);
            return ref _Handle.AsRef<CGlobalSymbol>(_InitialQueryNameOffset!.Value);
        }
    }
    private static nint? _CurrentQueryNameOffset;

    public ref CGlobalSymbol CurrentQueryName
    {
        get
        {
            _CurrentQueryNameOffset = _CurrentQueryNameOffset ?? Schema.GetOffset(0x694C69B78AF41ACA);
            return ref _Handle.AsRef<CGlobalSymbol>(_CurrentQueryNameOffset!.Value);
        }
    }
    private static nint? _ModeOffset;

    public ref CGlobalSymbol Mode
    {
        get
        {
            _ModeOffset = _ModeOffset ?? Schema.GetOffset(0x694C69B7137F1E0E);
            return ref _Handle.AsRef<CGlobalSymbol>(_ModeOffset!.Value);
        }
    }
    private static nint? _TypeOffset;

    public ref CGlobalSymbol Type
    {
        get
        {
            _TypeOffset = _TypeOffset ?? Schema.GetOffset(0x694C69B718853D59);
            return ref _Handle.AsRef<CGlobalSymbol>(_TypeOffset!.Value);
        }
    }
    private static nint? _StateOffset;

    public ref CGlobalSymbol State
    {
        get
        {
            _StateOffset = _StateOffset ?? Schema.GetOffset(0x694C69B77C824322);
            return ref _Handle.AsRef<CGlobalSymbol>(_StateOffset!.Value);
        }
    }

}