// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class AI_MotorGroundAnimgraph_DebugSnapshotData_t__Event_tImpl : SchemaClass, AI_MotorGroundAnimgraph_DebugSnapshotData_t__Event_t
{
    public AI_MotorGroundAnimgraph_DebugSnapshotData_t__Event_tImpl(nint handle) : base(handle) { }

    private static nint? _DescriptionOffset;

    public string Description
    {
        get
        {
            _DescriptionOffset = _DescriptionOffset ?? Schema.GetOffset(0xD95822E5346F3B69);
            return Schema.GetCUtlString(_Handle.Read<nint>(_DescriptionOffset!.Value));
        }
        set
        {
            _DescriptionOffset = _DescriptionOffset ?? Schema.GetOffset(0xD95822E5346F3B69);
            Schema.SetCUtlString(_Handle, _DescriptionOffset!.Value, value);
        }
    }
    private static nint? _LocationOffset;

    public ref Vector Location
    {
        get
        {
            _LocationOffset = _LocationOffset ?? Schema.GetOffset(0xD95822E50BF5A9A6);
            return ref _Handle.AsRef<Vector>(_LocationOffset!.Value);
        }
    }

}