// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class AI_MotorGroundAnimgraph_DebugSnapshotData_tImpl : DebugSnapshotBaseStructuredData_tImpl, AI_MotorGroundAnimgraph_DebugSnapshotData_t
{
    public AI_MotorGroundAnimgraph_DebugSnapshotData_tImpl(nint handle) : base(handle) { }

    private static nint? _StateOffset;

    public ref CGlobalSymbol State
    {
        get
        {
            _StateOffset = _StateOffset ?? Schema.GetOffset(0x9A188ABE783132F6);
            return ref _Handle.AsRef<CGlobalSymbol>(_StateOffset!.Value);
        }
    }
    private static nint? _B_has_pathOffset;

    public ref bool B_has_path
    {
        get
        {
            _B_has_pathOffset = _B_has_pathOffset ?? Schema.GetOffset(0x9A188ABE3D2AEA64);
            return ref _Handle.AsRef<bool>(_B_has_pathOffset!.Value);
        }
    }
    private static nint? _F_remaining_ground_path_lengthOffset;

    public ref float F_remaining_ground_path_length
    {
        get
        {
            _F_remaining_ground_path_lengthOffset = _F_remaining_ground_path_lengthOffset ?? Schema.GetOffset(0x9A188ABE55E02803);
            return ref _Handle.AsRef<float>(_F_remaining_ground_path_lengthOffset!.Value);
        }
    }
    private static nint? _F_current_speedOffset;

    public ref float F_current_speed
    {
        get
        {
            _F_current_speedOffset = _F_current_speedOffset ?? Schema.GetOffset(0x9A188ABE5E56C26F);
            return ref _Handle.AsRef<float>(_F_current_speedOffset!.Value);
        }
    }
    private static nint? _Move_typeOffset;

    public ref CGlobalSymbol Move_type
    {
        get
        {
            _Move_typeOffset = _Move_typeOffset ?? Schema.GetOffset(0x9A188ABE108798F9);
            return ref _Handle.AsRef<CGlobalSymbol>(_Move_typeOffset!.Value);
        }
    }
    private static nint? _F_move_heading_actualOffset;

    public ref float F_move_heading_actual
    {
        get
        {
            _F_move_heading_actualOffset = _F_move_heading_actualOffset ?? Schema.GetOffset(0x9A188ABE96B98761);
            return ref _Handle.AsRef<float>(_F_move_heading_actualOffset!.Value);
        }
    }
    private static nint? _F_move_heading_desiredOffset;

    public ref float F_move_heading_desired
    {
        get
        {
            _F_move_heading_desiredOffset = _F_move_heading_desiredOffset ?? Schema.GetOffset(0x9A188ABE093AF1B7);
            return ref _Handle.AsRef<float>(_F_move_heading_desiredOffset!.Value);
        }
    }
    private static nint? _F_current_leanOffset;

    public ref float F_current_lean
    {
        get
        {
            _F_current_leanOffset = _F_current_leanOffset ?? Schema.GetOffset(0x9A188ABE1067BC54);
            return ref _Handle.AsRef<float>(_F_current_leanOffset!.Value);
        }
    }
    private static nint? _F_target_leanOffset;

    public ref float F_target_lean
    {
        get
        {
            _F_target_leanOffset = _F_target_leanOffset ?? Schema.GetOffset(0x9A188ABE9AB8C214);
            return ref _Handle.AsRef<float>(_F_target_leanOffset!.Value);
        }
    }
    private static nint? _Vec_eventsOffset;

    public ref CUtlVector<AI_MotorGroundAnimgraph_DebugSnapshotData_t__Event_t> Vec_events
    {
        get
        {
            _Vec_eventsOffset = _Vec_eventsOffset ?? Schema.GetOffset(0x9A188ABEC197E10B);
            return ref _Handle.AsRef<CUtlVector<AI_MotorGroundAnimgraph_DebugSnapshotData_t__Event_t>>(_Vec_eventsOffset!.Value);
        }
    }

}