// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class AI_Motor_DebugSnapshotData_tImpl : DebugSnapshotBaseStructuredData_tImpl, AI_Motor_DebugSnapshotData_t
{
    public AI_Motor_DebugSnapshotData_tImpl(nint handle) : base(handle) { }

    private static nint? _Current_movement_gait_setOffset;

    public ref CGlobalSymbol Current_movement_gait_set
    {
        get
        {
            _Current_movement_gait_setOffset = _Current_movement_gait_setOffset ?? Schema.GetOffset(0x62A2E126A785FDBD);
            return ref _Handle.AsRef<CGlobalSymbol>(_Current_movement_gait_setOffset!.Value);
        }
    }
    private static nint? _Current_movement_gaitOffset;

    public ref CGlobalSymbol Current_movement_gait
    {
        get
        {
            _Current_movement_gaitOffset = _Current_movement_gaitOffset ?? Schema.GetOffset(0x62A2E126F92ACAC2);
            return ref _Handle.AsRef<CGlobalSymbol>(_Current_movement_gaitOffset!.Value);
        }
    }
    private static nint? _Movement_setting_idOffset;

    public ref CGlobalSymbol Movement_setting_id
    {
        get
        {
            _Movement_setting_idOffset = _Movement_setting_idOffset ?? Schema.GetOffset(0x62A2E126E024CE51);
            return ref _Handle.AsRef<CGlobalSymbol>(_Movement_setting_idOffset!.Value);
        }
    }

}