// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class AI_Navigator_DebugSnapshotData_t__Waypoint_tImpl : SchemaClass, AI_Navigator_DebugSnapshotData_t__Waypoint_t
{
    public AI_Navigator_DebugSnapshotData_t__Waypoint_tImpl(nint handle) : base(handle) { }

    private static nint? _PositionOffset;

    public ref Vector Position
    {
        get
        {
            _PositionOffset = _PositionOffset ?? Schema.GetOffset(0x891DD4E6934F4E0A);
            return ref _Handle.AsRef<Vector>(_PositionOffset!.Value);
        }
    }
    private static nint? _Nav_typeOffset;

    public ref uint Nav_type
    {
        get
        {
            _Nav_typeOffset = _Nav_typeOffset ?? Schema.GetOffset(0x891DD4E6DE1A548F);
            return ref _Handle.AsRef<uint>(_Nav_typeOffset!.Value);
        }
    }
    private static nint? _FlagsOffset;

    public ref uint Flags
    {
        get
        {
            _FlagsOffset = _FlagsOffset ?? Schema.GetOffset(0x891DD4E69C677A2C);
            return ref _Handle.AsRef<uint>(_FlagsOffset!.Value);
        }
    }

}