// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class AI_Navigator_DebugSnapshotData_tImpl : DebugSnapshotBaseStructuredData_tImpl, AI_Navigator_DebugSnapshotData_t
{
    public AI_Navigator_DebugSnapshotData_tImpl(nint handle) : base(handle) { }

    private static nint? _S_npc_nav_authorityOffset;

    public ref CGlobalSymbol S_npc_nav_authority
    {
        get
        {
            _S_npc_nav_authorityOffset = _S_npc_nav_authorityOffset ?? Schema.GetOffset(0x48159FC64E3BA80A);
            return ref _Handle.AsRef<CGlobalSymbol>(_S_npc_nav_authorityOffset!.Value);
        }
    }
    private static nint? _S_goal_nav_search_idOffset;

    public ref CGlobalSymbol S_goal_nav_search_id
    {
        get
        {
            _S_goal_nav_search_idOffset = _S_goal_nav_search_idOffset ?? Schema.GetOffset(0x48159FC61EBF3C55);
            return ref _Handle.AsRef<CGlobalSymbol>(_S_goal_nav_search_idOffset!.Value);
        }
    }
    private static nint? _S_goal_source_locationOffset;

    public string S_goal_source_location
    {
        get
        {
            _S_goal_source_locationOffset = _S_goal_source_locationOffset ?? Schema.GetOffset(0x48159FC660679B76);
            return Schema.GetCUtlString(_Handle.Read<nint>(_S_goal_source_locationOffset!.Value));
        }
        set
        {
            _S_goal_source_locationOffset = _S_goal_source_locationOffset ?? Schema.GetOffset(0x48159FC660679B76);
            Schema.SetCUtlString(_Handle, _S_goal_source_locationOffset!.Value, value);
        }
    }
    private static nint? _Goal_actual_posOffset;

    public ref Vector Goal_actual_pos
    {
        get
        {
            _Goal_actual_posOffset = _Goal_actual_posOffset ?? Schema.GetOffset(0x48159FC68DB5A388);
            return ref _Handle.AsRef<Vector>(_Goal_actual_posOffset!.Value);
        }
    }
    private static nint? _Goal_base_posOffset;

    public ref Vector Goal_base_pos
    {
        get
        {
            _Goal_base_posOffset = _Goal_base_posOffset ?? Schema.GetOffset(0x48159FC6FA337B3B);
            return ref _Handle.AsRef<Vector>(_Goal_base_posOffset!.Value);
        }
    }
    private static nint? _WaypointsOffset;

    public ref CUtlVector<AI_Navigator_DebugSnapshotData_t__Waypoint_t> Waypoints
    {
        get
        {
            _WaypointsOffset = _WaypointsOffset ?? Schema.GetOffset(0x48159FC67A0ABB2B);
            return ref _Handle.AsRef<CUtlVector<AI_Navigator_DebugSnapshotData_t__Waypoint_t>>(_WaypointsOffset!.Value);
        }
    }

}