// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class AnimGraph2SerializedPoseRecipe_tImpl : SchemaClass, AnimGraph2SerializedPoseRecipe_t
{
    public AnimGraph2SerializedPoseRecipe_tImpl(nint handle) : base(handle) { }

    private static nint? _SerializedStaticOffset;

    public ref CUtlBinaryBlock SerializedStatic
    {
        get
        {
            _SerializedStaticOffset = _SerializedStaticOffset ?? Schema.GetOffset(0x1B43DAB033C711F5);
            return ref _Handle.AsRef<CUtlBinaryBlock>(_SerializedStaticOffset!.Value);
        }
    }

    public void SerializedStaticUpdated() => Schema.Update(_Handle, 0x1B43DAB033C711F5);
}