// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class AnimGraph2SerializedPoseRecipeSlot_tImpl : SchemaClass, AnimGraph2SerializedPoseRecipeSlot_t
{
    public AnimGraph2SerializedPoseRecipeSlot_tImpl(nint handle) : base(handle) { }

    private static nint? _TopologyOffset;

    public ref CUtlBinaryBlock Topology
    {
        get
        {
            _TopologyOffset = _TopologyOffset ?? Schema.GetOffset(0x53900E1C0A5A1224);
            return ref _Handle.AsRef<CUtlBinaryBlock>(_TopologyOffset!.Value);
        }
    }

    public void TopologyUpdated() => Schema.Update(_Handle, 0x53900E1C0A5A1224);
}