// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_INIT_CreateSpiralSphereImpl : CParticleFunctionInitializerImpl, C_INIT_CreateSpiralSphere
{
    public C_INIT_CreateSpiralSphereImpl(nint handle) : base(handle) { }

    private static nint? _TransformInputOffset;

    public CParticleTransformInput TransformInput
    {
        get
        {
            _TransformInputOffset = _TransformInputOffset ?? Schema.GetOffset(0x97C2018AB3FDC289);
            return new CParticleTransformInputImpl(_Handle + _TransformInputOffset!.Value);
        }
    }
    private static nint? _DensityOffset;

    public CPerParticleFloatInput Density
    {
        get
        {
            _DensityOffset = _DensityOffset ?? Schema.GetOffset(0x97C2018AA7E7CAA1);
            return new CPerParticleFloatInputImpl(_Handle + _DensityOffset!.Value);
        }
    }
    private static nint? _InitialRadiusOffset;

    public CPerParticleFloatInput InitialRadius
    {
        get
        {
            _InitialRadiusOffset = _InitialRadiusOffset ?? Schema.GetOffset(0x97C2018A8B8AAB8B);
            return new CPerParticleFloatInputImpl(_Handle + _InitialRadiusOffset!.Value);
        }
    }
    private static nint? _InitialSpeedMinOffset;

    public CPerParticleFloatInput InitialSpeedMin
    {
        get
        {
            _InitialSpeedMinOffset = _InitialSpeedMinOffset ?? Schema.GetOffset(0x97C2018AE36FD694);
            return new CPerParticleFloatInputImpl(_Handle + _InitialSpeedMinOffset!.Value);
        }
    }
    private static nint? _InitialSpeedMaxOffset;

    public CPerParticleFloatInput InitialSpeedMax
    {
        get
        {
            _InitialSpeedMaxOffset = _InitialSpeedMaxOffset ?? Schema.GetOffset(0x97C2018AD184D4F6);
            return new CPerParticleFloatInputImpl(_Handle + _InitialSpeedMaxOffset!.Value);
        }
    }
    private static nint? _UseParticleCountOffset;

    public ref bool UseParticleCount
    {
        get
        {
            _UseParticleCountOffset = _UseParticleCountOffset ?? Schema.GetOffset(0x97C2018AD4DA0515);
            return ref _Handle.AsRef<bool>(_UseParticleCountOffset!.Value);
        }
    }

}