// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_RenderVolumetricEmitterImpl : CParticleFunctionRendererImpl, C_OP_RenderVolumetricEmitter
{
    public C_OP_RenderVolumetricEmitterImpl(nint handle) : base(handle) { }

    private static nint? _StrChannelTypeOffset;

    public string StrChannelType
    {
        get
        {
            _StrChannelTypeOffset = _StrChannelTypeOffset ?? Schema.GetOffset(0x93EEEB29445B3CA3);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrChannelTypeOffset!.Value));
        }
        set
        {
            _StrChannelTypeOffset = _StrChannelTypeOffset ?? Schema.GetOffset(0x93EEEB29445B3CA3);
            Schema.SetCUtlString(_Handle, _StrChannelTypeOffset!.Value, value);
        }
    }
    private static nint? _TypeOffset;

    public ref ParticleVolumetricSmokeType_t Type
    {
        get
        {
            _TypeOffset = _TypeOffset ?? Schema.GetOffset(0x93EEEB2918853D59);
            return ref _Handle.AsRef<ParticleVolumetricSmokeType_t>(_TypeOffset!.Value);
        }
    }
    private static nint? _CreationTypeOffset;

    public ref ParticleVolumetricSmokeCreationType_t CreationType
    {
        get
        {
            _CreationTypeOffset = _CreationTypeOffset ?? Schema.GetOffset(0x93EEEB29608F8648);
            return ref _Handle.AsRef<ParticleVolumetricSmokeCreationType_t>(_CreationTypeOffset!.Value);
        }
    }
    private static nint? _EventTypeOffset;

    public ref EventTypeSelection_t EventType
    {
        get
        {
            _EventTypeOffset = _EventTypeOffset ?? Schema.GetOffset(0x93EEEB29E1F9AA93);
            return ref _Handle.AsRef<EventTypeSelection_t>(_EventTypeOffset!.Value);
        }
    }
    private static nint? _PosOffset;

    public CPerParticleVecInput Pos
    {
        get
        {
            _PosOffset = _PosOffset ?? Schema.GetOffset(0x93EEEB293B18EB69);
            return new CPerParticleVecInputImpl(_Handle + _PosOffset!.Value);
        }
    }
    private static nint? _VelocityOffset;

    public CPerParticleVecInput Velocity
    {
        get
        {
            _VelocityOffset = _VelocityOffset ?? Schema.GetOffset(0x93EEEB297CF77892);
            return new CPerParticleVecInputImpl(_Handle + _VelocityOffset!.Value);
        }
    }
    private static nint? _RadiusOffset;

    public CPerParticleFloatInput Radius
    {
        get
        {
            _RadiusOffset = _RadiusOffset ?? Schema.GetOffset(0x93EEEB295ACFC08D);
            return new CPerParticleFloatInputImpl(_Handle + _RadiusOffset!.Value);
        }
    }
    private static nint? _DensityOffset;

    public CPerParticleFloatInput Density
    {
        get
        {
            _DensityOffset = _DensityOffset ?? Schema.GetOffset(0x93EEEB29A7E7CAA1);
            return new CPerParticleFloatInputImpl(_Handle + _DensityOffset!.Value);
        }
    }
    private static nint? _TemperatureOffset;

    public CPerParticleFloatInput Temperature
    {
        get
        {
            _TemperatureOffset = _TemperatureOffset ?? Schema.GetOffset(0x93EEEB294EBF15AB);
            return new CPerParticleFloatInputImpl(_Handle + _TemperatureOffset!.Value);
        }
    }
    private static nint? _MagnitudeOffset;

    public CPerParticleFloatInput Magnitude
    {
        get
        {
            _MagnitudeOffset = _MagnitudeOffset ?? Schema.GetOffset(0x93EEEB29ED0A1D8B);
            return new CPerParticleFloatInputImpl(_Handle + _MagnitudeOffset!.Value);
        }
    }
    private static nint? _KillRadiusOffset;

    public CPerParticleFloatInput KillRadius
    {
        get
        {
            _KillRadiusOffset = _KillRadiusOffset ?? Schema.GetOffset(0x93EEEB29A0D462BD);
            return new CPerParticleFloatInputImpl(_Handle + _KillRadiusOffset!.Value);
        }
    }
    private static nint? _FalloffOffset;

    public CPerParticleFloatInput Falloff
    {
        get
        {
            _FalloffOffset = _FalloffOffset ?? Schema.GetOffset(0x93EEEB29FA143DCB);
            return new CPerParticleFloatInputImpl(_Handle + _FalloffOffset!.Value);
        }
    }

}