// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_RemapVectorToRotationsImpl : CParticleFunctionOperatorImpl, C_OP_RemapVectorToRotations
{
    public C_OP_RemapVectorToRotationsImpl(nint handle) : base(handle) { }

    private static nint? _InputOffset;

    public CPerParticleVecInput Input
    {
        get
        {
            _InputOffset = _InputOffset ?? Schema.GetOffset(0x2587C21B1EA0ED5B);
            return new CPerParticleVecInputImpl(_Handle + _InputOffset!.Value);
        }
    }
    private static nint? _RotationOffset;

    public CPerParticleVecInput Rotation
    {
        get
        {
            _RotationOffset = _RotationOffset ?? Schema.GetOffset(0x2587C21B1992E6BF);
            return new CPerParticleVecInputImpl(_Handle + _RotationOffset!.Value);
        }
    }

}