// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_MultiSegmentDisplaySnapshotGeneratorImpl : CParticleFunctionPreEmissionImpl, C_OP_MultiSegmentDisplaySnapshotGenerator
{
    public C_OP_MultiSegmentDisplaySnapshotGeneratorImpl(nint handle) : base(handle) { }

    private static nint? _CPSnapshotOffset;

    public ref int CPSnapshot
    {
        get
        {
            _CPSnapshotOffset = _CPSnapshotOffset ?? Schema.GetOffset(0xAF1E9A2886FAC63E);
            return ref _Handle.AsRef<int>(_CPSnapshotOffset!.Value);
        }
    }
    private static nint? _SegCountOffset;

    public ref ParticleMultiSegmentCountSelection_t SegCount
    {
        get
        {
            _SegCountOffset = _SegCountOffset ?? Schema.GetOffset(0xAF1E9A283D8D04F1);
            return ref _Handle.AsRef<ParticleMultiSegmentCountSelection_t>(_SegCountOffset!.Value);
        }
    }
    private static nint? _InputTypeOffset;

    public ref ParticleMultiSegmentInputSelection_t InputType
    {
        get
        {
            _InputTypeOffset = _InputTypeOffset ?? Schema.GetOffset(0xAF1E9A28BFD8A33F);
            return ref _Handle.AsRef<ParticleMultiSegmentInputSelection_t>(_InputTypeOffset!.Value);
        }
    }
    private static nint? _StrDefaultStringOffset;

    public string StrDefaultString
    {
        get
        {
            _StrDefaultStringOffset = _StrDefaultStringOffset ?? Schema.GetOffset(0xAF1E9A2888A41380);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrDefaultStringOffset!.Value));
        }
        set
        {
            _StrDefaultStringOffset = _StrDefaultStringOffset ?? Schema.GetOffset(0xAF1E9A2888A41380);
            Schema.SetCUtlString(_Handle, _StrDefaultStringOffset!.Value, value);
        }
    }
    private static nint? _ValueOffset;

    public CParticleCollectionFloatInput Value
    {
        get
        {
            _ValueOffset = _ValueOffset ?? Schema.GetOffset(0xAF1E9A288DFCB984);
            return new CParticleCollectionFloatInputImpl(_Handle + _ValueOffset!.Value);
        }
    }
    private static nint? _SpecialCharListOffset;

    public ref CUtlVector<ParticleMultiSegmentSpecialCharacter_t> SpecialCharList
    {
        get
        {
            _SpecialCharListOffset = _SpecialCharListOffset ?? Schema.GetOffset(0xAF1E9A28B0B2C0B4);
            return ref _Handle.AsRef<CUtlVector<ParticleMultiSegmentSpecialCharacter_t>>(_SpecialCharListOffset!.Value);
        }
    }
    private static nint? _ColorUnlitOffset;

    public CParticleCollectionVecInput ColorUnlit
    {
        get
        {
            _ColorUnlitOffset = _ColorUnlitOffset ?? Schema.GetOffset(0xAF1E9A28C4809660);
            return new CParticleCollectionVecInputImpl(_Handle + _ColorUnlitOffset!.Value);
        }
    }
    private static nint? _ColorLitOffset;

    public CParticleCollectionVecInput ColorLit
    {
        get
        {
            _ColorLitOffset = _ColorLitOffset ?? Schema.GetOffset(0xAF1E9A28A908C2C1);
            return new CParticleCollectionVecInputImpl(_Handle + _ColorLitOffset!.Value);
        }
    }
    private static nint? _RadiusOffset;

    public CParticleCollectionFloatInput Radius
    {
        get
        {
            _RadiusOffset = _RadiusOffset ?? Schema.GetOffset(0xAF1E9A285ACFC08D);
            return new CParticleCollectionFloatInputImpl(_Handle + _RadiusOffset!.Value);
        }
    }
    private static nint? _SpacingOffset;

    public CParticleCollectionFloatInput Spacing
    {
        get
        {
            _SpacingOffset = _SpacingOffset ?? Schema.GetOffset(0xAF1E9A282B86F1BC);
            return new CParticleCollectionFloatInputImpl(_Handle + _SpacingOffset!.Value);
        }
    }
    private static nint? _MinCountOffset;

    public CParticleCollectionFloatInput MinCount
    {
        get
        {
            _MinCountOffset = _MinCountOffset ?? Schema.GetOffset(0xAF1E9A280C26E410);
            return new CParticleCollectionFloatInputImpl(_Handle + _MinCountOffset!.Value);
        }
    }
    private static nint? _MaxCountOffset;

    public CParticleCollectionFloatInput MaxCount
    {
        get
        {
            _MaxCountOffset = _MaxCountOffset ?? Schema.GetOffset(0xAF1E9A28E9750CDE);
            return new CParticleCollectionFloatInputImpl(_Handle + _MaxCountOffset!.Value);
        }
    }
    private static nint? _PrependEmptyOffset;

    public ref bool PrependEmpty
    {
        get
        {
            _PrependEmptyOffset = _PrependEmptyOffset ?? Schema.GetOffset(0xAF1E9A28162B1D2C);
            return ref _Handle.AsRef<bool>(_PrependEmptyOffset!.Value);
        }
    }
    private static nint? _DigitsAfterDecimalOffset;

    public CParticleCollectionFloatInput DigitsAfterDecimal
    {
        get
        {
            _DigitsAfterDecimalOffset = _DigitsAfterDecimalOffset ?? Schema.GetOffset(0xAF1E9A2806E992DC);
            return new CParticleCollectionFloatInputImpl(_Handle + _DigitsAfterDecimalOffset!.Value);
        }
    }

}