// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAnimationGraphInstanceImpl : SchemaClass, CAnimationGraphInstance
{
    public CAnimationGraphInstanceImpl(nint handle) : base(handle) { }

    private static nint? _TagDispatchDirtyOffset;

    public ref bool TagDispatchDirty
    {
        get
        {
            _TagDispatchDirtyOffset = _TagDispatchDirtyOffset ?? Schema.GetOffset(0xA355E9FFD2F48627);
            return ref _Handle.AsRef<bool>(_TagDispatchDirtyOffset!.Value);
        }
    }

}