// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CBaseModelEntity__OnDamageLevelChangedArgs_tImpl : SchemaClass, CBaseModelEntity__OnDamageLevelChangedArgs_t
{
    public CBaseModelEntity__OnDamageLevelChangedArgs_tImpl(nint handle) : base(handle) { }

    private static nint? _HitGroupOffset;

    public ref HitGroup_t HitGroup
    {
        get
        {
            _HitGroupOffset = _HitGroupOffset ?? Schema.GetOffset(0xA9864F6FB0AC5DF9);
            return ref _Handle.AsRef<HitGroup_t>(_HitGroupOffset!.Value);
        }
    }
    private static nint? _DamageLevelOffset;

    public ref int DamageLevel
    {
        get
        {
            _DamageLevelOffset = _DamageLevelOffset ?? Schema.GetOffset(0xA9864F6F08DA2442);
            return ref _Handle.AsRef<int>(_DamageLevelOffset!.Value);
        }
    }
    private static nint? _DamageLevelsRemainingOffset;

    public ref int DamageLevelsRemaining
    {
        get
        {
            _DamageLevelsRemainingOffset = _DamageLevelsRemainingOffset ?? Schema.GetOffset(0xA9864F6F66EF701D);
            return ref _Handle.AsRef<int>(_DamageLevelsRemainingOffset!.Value);
        }
    }
    private static nint? _PrevDamageLevelOffset;

    public ref int PrevDamageLevel
    {
        get
        {
            _PrevDamageLevelOffset = _PrevDamageLevelOffset ?? Schema.GetOffset(0xA9864F6F54282245);
            return ref _Handle.AsRef<int>(_PrevDamageLevelOffset!.Value);
        }
    }

}