// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CBlendNodeInstanceDataImpl : SchemaClass, CBlendNodeInstanceData
{
    public CBlendNodeInstanceDataImpl(nint handle) : base(handle) { }

    private static nint? _DampedValueOffset;

    public ref float DampedValue
    {
        get
        {
            _DampedValueOffset = _DampedValueOffset ?? Schema.GetOffset(0xCAC3ECE0EAD75CB);
            return ref _Handle.AsRef<float>(_DampedValueOffset!.Value);
        }
    }
    private static nint? _CycleOffset;

    public ref float Cycle
    {
        get
        {
            _CycleOffset = _CycleOffset ?? Schema.GetOffset(0xCAC3ECE0C77829F);
            return ref _Handle.AsRef<float>(_CycleOffset!.Value);
        }
    }
    private static nint? _CycleZeroTimeOffset;

    public ref float CycleZeroTime
    {
        get
        {
            _CycleZeroTimeOffset = _CycleZeroTimeOffset ?? Schema.GetOffset(0xCAC3ECE40321698);
            return ref _Handle.AsRef<float>(_CycleZeroTimeOffset!.Value);
        }
    }
    private static nint? _PlaybackRateOffset;

    public ref float PlaybackRate
    {
        get
        {
            _PlaybackRateOffset = _PlaybackRateOffset ?? Schema.GetOffset(0xCAC3ECEC396F9D8);
            return ref _Handle.AsRef<float>(_PlaybackRateOffset!.Value);
        }
    }
    private static nint? _BlendValueOffset;

    public SchemaUntypedField BlendValue
    {
        get
        {
            _BlendValueOffset = _BlendValueOffset ?? Schema.GetOffset(0xCAC3ECEE14CD067);
            return new SchemaUntypedField(_Handle + _BlendValueOffset!.Value);
        }
    }
    private static nint? _DurationOffset;

    public ref float Duration
    {
        get
        {
            _DurationOffset = _DurationOffset ?? Schema.GetOffset(0xCAC3ECEBC5E3BAB);
            return ref _Handle.AsRef<float>(_DurationOffset!.Value);
        }
    }
    private static nint? _ResetCountOffset;

    public SchemaUntypedField ResetCount
    {
        get
        {
            _ResetCountOffset = _ResetCountOffset ?? Schema.GetOffset(0xCAC3ECE89B18BCF);
            return new SchemaUntypedField(_Handle + _ResetCountOffset!.Value);
        }
    }

}