// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CBlend2DInstanceDataImpl : SchemaClass, CBlend2DInstanceData
{
    public CBlend2DInstanceDataImpl(nint handle) : base(handle) { }

    private static nint? _DampedValueOffset;

    public ref Vector2D DampedValue
    {
        get
        {
            _DampedValueOffset = _DampedValueOffset ?? Schema.GetOffset(0x479D67640EAD75CB);
            return ref _Handle.AsRef<Vector2D>(_DampedValueOffset!.Value);
        }
    }
    private static nint? _CycleOffset;

    public ref float Cycle
    {
        get
        {
            _CycleOffset = _CycleOffset ?? Schema.GetOffset(0x479D67640C77829F);
            return ref _Handle.AsRef<float>(_CycleOffset!.Value);
        }
    }
    private static nint? _PrevCycleOffset;

    public ref float PrevCycle
    {
        get
        {
            _PrevCycleOffset = _PrevCycleOffset ?? Schema.GetOffset(0x479D6764AA0F5CF4);
            return ref _Handle.AsRef<float>(_PrevCycleOffset!.Value);
        }
    }

}