// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CCashStackImpl : CBaseModelEntityImpl, CCashStack
{
    public CCashStackImpl(nint handle) : base(handle) { }

    private static nint? _CashStackValueOffset;

    public ref int CashStackValue
    {
        get
        {
            _CashStackValueOffset = _CashStackValueOffset ?? Schema.GetOffset(0x2BB7B63FABAA051F);
            return ref _Handle.AsRef<int>(_CashStackValueOffset!.Value);
        }
    }

}