// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CChoreoInstanceDataImpl : SchemaClass, CChoreoInstanceData
{
    public CChoreoInstanceDataImpl(nint handle) : base(handle) { }

    public ISchemaClassFixedArray<CAnimationLayer> AnimOverlay
    {
        get => new SchemaClassFixedArray<CAnimationLayer>(_Handle, 0xD3B066AB24E8AAA0, 12, 76, 4);
    }

}