// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CChoiceInstanceDataImpl : SchemaClass, CChoiceInstanceData
{
    public CChoiceInstanceDataImpl(nint handle) : base(handle) { }

    private static nint? _CurrentChoiceOffset;

    public SchemaUntypedField CurrentChoice
    {
        get
        {
            _CurrentChoiceOffset = _CurrentChoiceOffset ?? Schema.GetOffset(0x5F93659E47121CD9);
            return new SchemaUntypedField(_Handle + _CurrentChoiceOffset!.Value);
        }
    }
    private static nint? _PreviousChoiceOffset;

    public ref int PreviousChoice
    {
        get
        {
            _PreviousChoiceOffset = _PreviousChoiceOffset ?? Schema.GetOffset(0x5F93659E819F1073);
            return ref _Handle.AsRef<int>(_PreviousChoiceOffset!.Value);
        }
    }
    private static nint? _ClipStartTimeOffset;

    public SchemaUntypedField ClipStartTime
    {
        get
        {
            _ClipStartTimeOffset = _ClipStartTimeOffset ?? Schema.GetOffset(0x5F93659E5BAB4702);
            return new SchemaUntypedField(_Handle + _ClipStartTimeOffset!.Value);
        }
    }
    private static nint? _ChoicePreviousCycleOffset;

    public ref float ChoicePreviousCycle
    {
        get
        {
            _ChoicePreviousCycleOffset = _ChoicePreviousCycleOffset ?? Schema.GetOffset(0x5F93659E46D3DF23);
            return ref _Handle.AsRef<float>(_ChoicePreviousCycleOffset!.Value);
        }
    }

}