// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CChoreoComponentImpl : SchemaClass, CChoreoComponent
{
    public CChoreoComponentImpl(nint handle) : base(handle) { }

    private static nint? ___m_pChainEntityOffset;

    public ref CNetworkVarChainer __m_pChainEntity
    {
        get
        {
            ___m_pChainEntityOffset = ___m_pChainEntityOffset ?? Schema.GetOffset(0x1CE3A87F63F0E7D);
            return ref _Handle.AsRef<CNetworkVarChainer>(___m_pChainEntityOffset!.Value);
        }
    }
    private static nint? _OwnerOffset;

    public ref CHandle<CBaseModelEntity> Owner
    {
        get
        {
            _OwnerOffset = _OwnerOffset ?? Schema.GetOffset(0x1CE3A87F6D89572);
            return ref _Handle.AsRef<CHandle<CBaseModelEntity>>(_OwnerOffset!.Value);
        }
    }
    private static nint? _NextSceneEventIdOffset;

    public SceneEventId_t NextSceneEventId
    {
        get
        {
            _NextSceneEventIdOffset = _NextSceneEventIdOffset ?? Schema.GetOffset(0x1CE3A873756F461);
            return new SceneEventId_tImpl(_Handle + _NextSceneEventIdOffset!.Value);
        }
    }
    private static nint? _UpdateLayerPrioritiesOffset;

    public ref bool UpdateLayerPriorities
    {
        get
        {
            _UpdateLayerPrioritiesOffset = _UpdateLayerPrioritiesOffset ?? Schema.GetOffset(0x1CE3A87446AC3B9);
            return ref _Handle.AsRef<bool>(_UpdateLayerPrioritiesOffset!.Value);
        }
    }
    private static nint? _AllowResponsesEndTimeOffset;

    public GameTime_t AllowResponsesEndTime
    {
        get
        {
            _AllowResponsesEndTimeOffset = _AllowResponsesEndTimeOffset ?? Schema.GetOffset(0x1CE3A8758EB0248);
            return new GameTime_tImpl(_Handle + _AllowResponsesEndTimeOffset!.Value);
        }
    }

}