// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CCS2PawnGraphControllerImpl : CCS2WeaponGraphControllerImpl, CCS2PawnGraphController
{
    public CCS2PawnGraphControllerImpl(nint handle) : base(handle) { }

    private static nint? _IsDefusingOffset;

    public SchemaUntypedField IsDefusing
    {
        get
        {
            _IsDefusingOffset = _IsDefusingOffset ?? Schema.GetOffset(0x716A0F885BDAECC0);
            return new SchemaUntypedField(_Handle + _IsDefusingOffset!.Value);
        }
    }
    private static nint? _MoveTypeOffset;

    public SchemaUntypedField MoveType
    {
        get
        {
            _MoveTypeOffset = _MoveTypeOffset ?? Schema.GetOffset(0x716A0F8886D8B6FC);
            return new SchemaUntypedField(_Handle + _MoveTypeOffset!.Value);
        }
    }
    private static nint? _MoveDirectionIDOffset;

    public SchemaUntypedField MoveDirectionID
    {
        get
        {
            _MoveDirectionIDOffset = _MoveDirectionIDOffset ?? Schema.GetOffset(0x716A0F88518E4530);
            return new SchemaUntypedField(_Handle + _MoveDirectionIDOffset!.Value);
        }
    }
    private static nint? _MoveSpeedXOffset;

    public SchemaUntypedField MoveSpeedX
    {
        get
        {
            _MoveSpeedXOffset = _MoveSpeedXOffset ?? Schema.GetOffset(0x716A0F88FCCFD9F3);
            return new SchemaUntypedField(_Handle + _MoveSpeedXOffset!.Value);
        }
    }
    private static nint? _MoveSpeedYOffset;

    public SchemaUntypedField MoveSpeedY
    {
        get
        {
            _MoveSpeedYOffset = _MoveSpeedYOffset ?? Schema.GetOffset(0x716A0F88FBCFD860);
            return new SchemaUntypedField(_Handle + _MoveSpeedYOffset!.Value);
        }
    }
    private static nint? _MoveSpeedHorizontalOffset;

    public SchemaUntypedField MoveSpeedHorizontal
    {
        get
        {
            _MoveSpeedHorizontalOffset = _MoveSpeedHorizontalOffset ?? Schema.GetOffset(0x716A0F8854A92035);
            return new SchemaUntypedField(_Handle + _MoveSpeedHorizontalOffset!.Value);
        }
    }
    private static nint? _PreviousMoveSpeedHorizontalOffset;

    public SchemaUntypedField PreviousMoveSpeedHorizontal
    {
        get
        {
            _PreviousMoveSpeedHorizontalOffset = _PreviousMoveSpeedHorizontalOffset ?? Schema.GetOffset(0x716A0F882894FBA6);
            return new SchemaUntypedField(_Handle + _PreviousMoveSpeedHorizontalOffset!.Value);
        }
    }
    private static nint? _CrouchAmountOffset;

    public SchemaUntypedField CrouchAmount
    {
        get
        {
            _CrouchAmountOffset = _CrouchAmountOffset ?? Schema.GetOffset(0x716A0F8829DCF639);
            return new SchemaUntypedField(_Handle + _CrouchAmountOffset!.Value);
        }
    }
    private static nint? _IsWalkingOffset;

    public SchemaUntypedField IsWalking
    {
        get
        {
            _IsWalkingOffset = _IsWalkingOffset ?? Schema.GetOffset(0x716A0F889441C788);
            return new SchemaUntypedField(_Handle + _IsWalkingOffset!.Value);
        }
    }
    private static nint? _IsStutterStepOffset;

    public SchemaUntypedField IsStutterStep
    {
        get
        {
            _IsStutterStepOffset = _IsStutterStepOffset ?? Schema.GetOffset(0x716A0F8862C8FFF4);
            return new SchemaUntypedField(_Handle + _IsStutterStepOffset!.Value);
        }
    }
    private static nint? _WeaponDropAmountOffset;

    public SchemaUntypedField WeaponDropAmount
    {
        get
        {
            _WeaponDropAmountOffset = _WeaponDropAmountOffset ?? Schema.GetOffset(0x716A0F88E0BE7D8A);
            return new SchemaUntypedField(_Handle + _WeaponDropAmountOffset!.Value);
        }
    }
    private static nint? _GroundActionOffset;

    public SchemaUntypedField GroundAction
    {
        get
        {
            _GroundActionOffset = _GroundActionOffset ?? Schema.GetOffset(0x716A0F886D542E94);
            return new SchemaUntypedField(_Handle + _GroundActionOffset!.Value);
        }
    }
    private static nint? _GroundActionDirectionIDOffset;

    public SchemaUntypedField GroundActionDirectionID
    {
        get
        {
            _GroundActionDirectionIDOffset = _GroundActionDirectionIDOffset ?? Schema.GetOffset(0x716A0F88DEFCEE50);
            return new SchemaUntypedField(_Handle + _GroundActionDirectionIDOffset!.Value);
        }
    }
    private static nint? _GroundTurnAngleOrVelocityOffset;

    public SchemaUntypedField GroundTurnAngleOrVelocity
    {
        get
        {
            _GroundTurnAngleOrVelocityOffset = _GroundTurnAngleOrVelocityOffset ?? Schema.GetOffset(0x716A0F88AC54B0AC);
            return new SchemaUntypedField(_Handle + _GroundTurnAngleOrVelocityOffset!.Value);
        }
    }
    private static nint? _LadderCycleOffset;

    public SchemaUntypedField LadderCycle
    {
        get
        {
            _LadderCycleOffset = _LadderCycleOffset ?? Schema.GetOffset(0x716A0F88C2EB3497);
            return new SchemaUntypedField(_Handle + _LadderCycleOffset!.Value);
        }
    }
    private static nint? _LadderYawOffset;

    public SchemaUntypedField LadderYaw
    {
        get
        {
            _LadderYawOffset = _LadderYawOffset ?? Schema.GetOffset(0x716A0F883BC18032);
            return new SchemaUntypedField(_Handle + _LadderYawOffset!.Value);
        }
    }
    private static nint? _LadderYawBackwardsOffset;

    public SchemaUntypedField LadderYawBackwards
    {
        get
        {
            _LadderYawBackwardsOffset = _LadderYawBackwardsOffset ?? Schema.GetOffset(0x716A0F88A38B5024);
            return new SchemaUntypedField(_Handle + _LadderYawBackwardsOffset!.Value);
        }
    }
    private static nint? _AirActionOffset;

    public SchemaUntypedField AirAction
    {
        get
        {
            _AirActionOffset = _AirActionOffset ?? Schema.GetOffset(0x716A0F88F817B6CD);
            return new SchemaUntypedField(_Handle + _AirActionOffset!.Value);
        }
    }
    private static nint? _AirHeightAboveGroundOffset;

    public SchemaUntypedField AirHeightAboveGround
    {
        get
        {
            _AirHeightAboveGroundOffset = _AirHeightAboveGroundOffset ?? Schema.GetOffset(0x716A0F88DF312A68);
            return new SchemaUntypedField(_Handle + _AirHeightAboveGroundOffset!.Value);
        }
    }
    private static nint? _LeftFootTargetOffset;

    public SchemaUntypedField LeftFootTarget
    {
        get
        {
            _LeftFootTargetOffset = _LeftFootTargetOffset ?? Schema.GetOffset(0x716A0F88B572843D);
            return new SchemaUntypedField(_Handle + _LeftFootTargetOffset!.Value);
        }
    }
    private static nint? _RightFootTargetOffset;

    public SchemaUntypedField RightFootTarget
    {
        get
        {
            _RightFootTargetOffset = _RightFootTargetOffset ?? Schema.GetOffset(0x716A0F883ABA0A2C);
            return new SchemaUntypedField(_Handle + _RightFootTargetOffset!.Value);
        }
    }
    private static nint? _FlashedAmountOffset;

    public SchemaUntypedField FlashedAmount
    {
        get
        {
            _FlashedAmountOffset = _FlashedAmountOffset ?? Schema.GetOffset(0x716A0F884BF2CBC2);
            return new SchemaUntypedField(_Handle + _FlashedAmountOffset!.Value);
        }
    }
    private static nint? _AimPitchAngleOffset;

    public SchemaUntypedField AimPitchAngle
    {
        get
        {
            _AimPitchAngleOffset = _AimPitchAngleOffset ?? Schema.GetOffset(0x716A0F8898255DC1);
            return new SchemaUntypedField(_Handle + _AimPitchAngleOffset!.Value);
        }
    }
    private static nint? _AimYawAngleOffset;

    public SchemaUntypedField AimYawAngle
    {
        get
        {
            _AimYawAngleOffset = _AimYawAngleOffset ?? Schema.GetOffset(0x716A0F88A22DD11E);
            return new SchemaUntypedField(_Handle + _AimYawAngleOffset!.Value);
        }
    }
    private static nint? _FlinchHeadOffset;

    public SchemaUntypedField FlinchHead
    {
        get
        {
            _FlinchHeadOffset = _FlinchHeadOffset ?? Schema.GetOffset(0x716A0F88075089BD);
            return new SchemaUntypedField(_Handle + _FlinchHeadOffset!.Value);
        }
    }
    private static nint? _FlinchHeadRestartOffset;

    public SchemaUntypedField FlinchHeadRestart
    {
        get
        {
            _FlinchHeadRestartOffset = _FlinchHeadRestartOffset ?? Schema.GetOffset(0x716A0F88C48EEF74);
            return new SchemaUntypedField(_Handle + _FlinchHeadRestartOffset!.Value);
        }
    }
    private static nint? _FlinchBodyOffset;

    public SchemaUntypedField FlinchBody
    {
        get
        {
            _FlinchBodyOffset = _FlinchBodyOffset ?? Schema.GetOffset(0x716A0F88FA5433DF);
            return new SchemaUntypedField(_Handle + _FlinchBodyOffset!.Value);
        }
    }
    private static nint? _FlinchBodyRestartOffset;

    public SchemaUntypedField FlinchBodyRestart
    {
        get
        {
            _FlinchBodyRestartOffset = _FlinchBodyRestartOffset ?? Schema.GetOffset(0x716A0F881234CE76);
            return new SchemaUntypedField(_Handle + _FlinchBodyRestartOffset!.Value);
        }
    }
    private static nint? _FlinchIsOnFireOffset;

    public SchemaUntypedField FlinchIsOnFire
    {
        get
        {
            _FlinchIsOnFireOffset = _FlinchIsOnFireOffset ?? Schema.GetOffset(0x716A0F881A94A5EA);
            return new SchemaUntypedField(_Handle + _FlinchIsOnFireOffset!.Value);
        }
    }

}