// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CCS2WeaponGraphControllerImpl : CAnimGraphControllerBaseImpl, CCS2WeaponGraphController
{
    public CCS2WeaponGraphControllerImpl(nint handle) : base(handle) { }

    private static nint? _ActionOffset;

    public ref CAnimGraph2ParamOptionalRefCGlobalSymbol Action
    {
        get
        {
            _ActionOffset = _ActionOffset ?? Schema.GetOffset(0x8553337E7918619F);
            return ref _Handle.AsRef<CAnimGraph2ParamOptionalRefCGlobalSymbol>(_ActionOffset!.Value);
        }
    }
    private static nint? _ActionResetOffset;

    public ref CAnimGraph2ParamOptionalRefBool ActionReset
    {
        get
        {
            _ActionResetOffset = _ActionResetOffset ?? Schema.GetOffset(0x8553337E580F422E);
            return ref _Handle.AsRef<CAnimGraph2ParamOptionalRefBool>(_ActionResetOffset!.Value);
        }
    }
    private static nint? _WeaponActionSpeedScaleOffset;

    public ref CAnimGraph2ParamOptionalRefFloat WeaponActionSpeedScale
    {
        get
        {
            _WeaponActionSpeedScaleOffset = _WeaponActionSpeedScaleOffset ?? Schema.GetOffset(0x8553337EC667EC52);
            return ref _Handle.AsRef<CAnimGraph2ParamOptionalRefFloat>(_WeaponActionSpeedScaleOffset!.Value);
        }
    }
    private static nint? _WeaponCategoryOffset;

    public ref CAnimGraph2ParamOptionalRefCGlobalSymbol WeaponCategory
    {
        get
        {
            _WeaponCategoryOffset = _WeaponCategoryOffset ?? Schema.GetOffset(0x8553337EE2B7A95D);
            return ref _Handle.AsRef<CAnimGraph2ParamOptionalRefCGlobalSymbol>(_WeaponCategoryOffset!.Value);
        }
    }
    private static nint? _WeaponTypeOffset;

    public ref CAnimGraph2ParamOptionalRefCGlobalSymbol WeaponType
    {
        get
        {
            _WeaponTypeOffset = _WeaponTypeOffset ?? Schema.GetOffset(0x8553337E0C0E3309);
            return ref _Handle.AsRef<CAnimGraph2ParamOptionalRefCGlobalSymbol>(_WeaponTypeOffset!.Value);
        }
    }
    private static nint? _WeaponExtraInfoOffset;

    public ref CAnimGraph2ParamOptionalRefCGlobalSymbol WeaponExtraInfo
    {
        get
        {
            _WeaponExtraInfoOffset = _WeaponExtraInfoOffset ?? Schema.GetOffset(0x8553337EF4004D3D);
            return ref _Handle.AsRef<CAnimGraph2ParamOptionalRefCGlobalSymbol>(_WeaponExtraInfoOffset!.Value);
        }
    }
    private static nint? _WeaponAmmoOffset;

    public ref CAnimGraph2ParamOptionalRefFloat WeaponAmmo
    {
        get
        {
            _WeaponAmmoOffset = _WeaponAmmoOffset ?? Schema.GetOffset(0x8553337ED1A06C75);
            return ref _Handle.AsRef<CAnimGraph2ParamOptionalRefFloat>(_WeaponAmmoOffset!.Value);
        }
    }
    private static nint? _WeaponAmmoMaxOffset;

    public ref CAnimGraph2ParamOptionalRefFloat WeaponAmmoMax
    {
        get
        {
            _WeaponAmmoMaxOffset = _WeaponAmmoMaxOffset ?? Schema.GetOffset(0x8553337EEE4C1969);
            return ref _Handle.AsRef<CAnimGraph2ParamOptionalRefFloat>(_WeaponAmmoMaxOffset!.Value);
        }
    }
    private static nint? _WeaponAmmoReserveOffset;

    public ref CAnimGraph2ParamOptionalRefFloat WeaponAmmoReserve
    {
        get
        {
            _WeaponAmmoReserveOffset = _WeaponAmmoReserveOffset ?? Schema.GetOffset(0x8553337E000AC7BB);
            return ref _Handle.AsRef<CAnimGraph2ParamOptionalRefFloat>(_WeaponAmmoReserveOffset!.Value);
        }
    }
    private static nint? _WeaponIsSilencedOffset;

    public ref CAnimGraph2ParamOptionalRefBool WeaponIsSilenced
    {
        get
        {
            _WeaponIsSilencedOffset = _WeaponIsSilencedOffset ?? Schema.GetOffset(0x8553337EBF4E259C);
            return ref _Handle.AsRef<CAnimGraph2ParamOptionalRefBool>(_WeaponIsSilencedOffset!.Value);
        }
    }
    private static nint? _WeaponIronsightAmountOffset;

    public ref CAnimGraph2ParamOptionalRefFloat WeaponIronsightAmount
    {
        get
        {
            _WeaponIronsightAmountOffset = _WeaponIronsightAmountOffset ?? Schema.GetOffset(0x8553337E4239F6F6);
            return ref _Handle.AsRef<CAnimGraph2ParamOptionalRefFloat>(_WeaponIronsightAmountOffset!.Value);
        }
    }
    private static nint? _IsUsingLegacyModelOffset;

    public ref CAnimGraph2ParamOptionalRefBool IsUsingLegacyModel
    {
        get
        {
            _IsUsingLegacyModelOffset = _IsUsingLegacyModelOffset ?? Schema.GetOffset(0x8553337EBA564E5D);
            return ref _Handle.AsRef<CAnimGraph2ParamOptionalRefBool>(_IsUsingLegacyModelOffset!.Value);
        }
    }
    private static nint? _IdleVariationOffset;

    public ref CAnimGraph2ParamOptionalRefFloat IdleVariation
    {
        get
        {
            _IdleVariationOffset = _IdleVariationOffset ?? Schema.GetOffset(0x8553337ECF0EF118);
            return ref _Handle.AsRef<CAnimGraph2ParamOptionalRefFloat>(_IdleVariationOffset!.Value);
        }
    }
    private static nint? _DeployVariationOffset;

    public ref CAnimGraph2ParamOptionalRefFloat DeployVariation
    {
        get
        {
            _DeployVariationOffset = _DeployVariationOffset ?? Schema.GetOffset(0x8553337E95BD68D7);
            return ref _Handle.AsRef<CAnimGraph2ParamOptionalRefFloat>(_DeployVariationOffset!.Value);
        }
    }
    private static nint? _AttackTypeOffset;

    public ref CAnimGraph2ParamOptionalRefCGlobalSymbol AttackType
    {
        get
        {
            _AttackTypeOffset = _AttackTypeOffset ?? Schema.GetOffset(0x8553337E0CCFAC15);
            return ref _Handle.AsRef<CAnimGraph2ParamOptionalRefCGlobalSymbol>(_AttackTypeOffset!.Value);
        }
    }
    private static nint? _AttackThrowStrengthOffset;

    public ref CAnimGraph2ParamOptionalRefFloat AttackThrowStrength
    {
        get
        {
            _AttackThrowStrengthOffset = _AttackThrowStrengthOffset ?? Schema.GetOffset(0x8553337EB4387222);
            return ref _Handle.AsRef<CAnimGraph2ParamOptionalRefFloat>(_AttackThrowStrengthOffset!.Value);
        }
    }
    private static nint? _AttackVariationOffset;

    public ref CAnimGraph2ParamOptionalRefFloat AttackVariation
    {
        get
        {
            _AttackVariationOffset = _AttackVariationOffset ?? Schema.GetOffset(0x8553337E70A63014);
            return ref _Handle.AsRef<CAnimGraph2ParamOptionalRefFloat>(_AttackVariationOffset!.Value);
        }
    }
    private static nint? _InspectVariationOffset;

    public ref CAnimGraph2ParamOptionalRefFloat InspectVariation
    {
        get
        {
            _InspectVariationOffset = _InspectVariationOffset ?? Schema.GetOffset(0x8553337EBDFCECA4);
            return ref _Handle.AsRef<CAnimGraph2ParamOptionalRefFloat>(_InspectVariationOffset!.Value);
        }
    }
    private static nint? _InspectExtraInfoOffset;

    public ref CAnimGraph2ParamOptionalRefCGlobalSymbol InspectExtraInfo
    {
        get
        {
            _InspectExtraInfoOffset = _InspectExtraInfoOffset ?? Schema.GetOffset(0x8553337EF50D283F);
            return ref _Handle.AsRef<CAnimGraph2ParamOptionalRefCGlobalSymbol>(_InspectExtraInfoOffset!.Value);
        }
    }
    private static nint? _ReloadStageOffset;

    public ref CAnimGraph2ParamOptionalRefCGlobalSymbol ReloadStage
    {
        get
        {
            _ReloadStageOffset = _ReloadStageOffset ?? Schema.GetOffset(0x8553337E7F8E072A);
            return ref _Handle.AsRef<CAnimGraph2ParamOptionalRefCGlobalSymbol>(_ReloadStageOffset!.Value);
        }
    }

}