// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CCycleClipInstanceDataImpl : SchemaClass, CCycleClipInstanceData
{
    public CCycleClipInstanceDataImpl(nint handle) : base(handle) { }

    private static nint? _CycleOffset;

    public SchemaUntypedField Cycle
    {
        get
        {
            _CycleOffset = _CycleOffset ?? Schema.GetOffset(0x2AACBED50C77829F);
            return new SchemaUntypedField(_Handle + _CycleOffset!.Value);
        }
    }
    private static nint? _PrevCycleOffset;

    public SchemaUntypedField PrevCycle
    {
        get
        {
            _PrevCycleOffset = _PrevCycleOffset ?? Schema.GetOffset(0x2AACBED5AA0F5CF4);
            return new SchemaUntypedField(_Handle + _PrevCycleOffset!.Value);
        }
    }

}