// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CDebugDrawHistoryDataImpl : SchemaClass, CDebugDrawHistoryData
{
    public CDebugDrawHistoryDataImpl(nint handle) : base(handle) { }

    private static nint? _EntityOffset;

    public ref CHandle<CBaseEntity> Entity
    {
        get
        {
            _EntityOffset = _EntityOffset ?? Schema.GetOffset(0xC0AC823D6EBADCB0);
            return ref _Handle.AsRef<CHandle<CBaseEntity>>(_EntityOffset!.Value);
        }
    }
    private static nint? _EtypeOffset;

    public ref ESceneViewDebugOverlaysListenerDataType_t Etype
    {
        get
        {
            _EtypeOffset = _EtypeOffset ?? Schema.GetOffset(0xC0AC823D9F0CE368);
            return ref _Handle.AsRef<ESceneViewDebugOverlaysListenerDataType_t>(_EtypeOffset!.Value);
        }
    }
    private static nint? _VectorsOffset;

    public ref CUtlLeanVector<Vector4D, int> Vectors
    {
        get
        {
            _VectorsOffset = _VectorsOffset ?? Schema.GetOffset(0xC0AC823D6B034803);
            return ref _Handle.AsRef<CUtlLeanVector<Vector4D, int>>(_VectorsOffset!.Value);
        }
    }
    private static nint? _ColorsOffset;

    public ref CUtlLeanVector<Color, int> Colors
    {
        get
        {
            _ColorsOffset = _ColorsOffset ?? Schema.GetOffset(0xC0AC823D945C0751);
            return ref _Handle.AsRef<CUtlLeanVector<Color, int>>(_ColorsOffset!.Value);
        }
    }
    private static nint? _DimensionsOffset;

    public ref CUtlLeanVector<float, int> Dimensions
    {
        get
        {
            _DimensionsOffset = _DimensionsOffset ?? Schema.GetOffset(0xC0AC823DF7AB8E50);
            return ref _Handle.AsRef<CUtlLeanVector<float, int>>(_DimensionsOffset!.Value);
        }
    }
    private static nint? _TimesOffset;

    public ref CUtlLeanVector<double, int> Times
    {
        get
        {
            _TimesOffset = _TimesOffset ?? Schema.GetOffset(0xC0AC823D86A55CD5);
            return ref _Handle.AsRef<CUtlLeanVector<double, int>>(_TimesOffset!.Value);
        }
    }
    private static nint? _Uint64sOffset;

    public ref CUtlLeanVector<ulong, int> Uint64s
    {
        get
        {
            _Uint64sOffset = _Uint64sOffset ?? Schema.GetOffset(0xC0AC823D39771940);
            return ref _Handle.AsRef<CUtlLeanVector<ulong, int>>(_Uint64sOffset!.Value);
        }
    }
    private static nint? _BoolsOffset;

    public ref CUtlLeanVector<bool, int> Bools
    {
        get
        {
            _BoolsOffset = _BoolsOffset ?? Schema.GetOffset(0xC0AC823D7C3341EA);
            return ref _Handle.AsRef<CUtlLeanVector<bool, int>>(_BoolsOffset!.Value);
        }
    }
    private static nint? _StringsOffset;

    public ref CUtlLeanVector<CUtlString, int> Strings
    {
        get
        {
            _StringsOffset = _StringsOffset ?? Schema.GetOffset(0xC0AC823D6ED10D31);
            return ref _Handle.AsRef<CUtlLeanVector<CUtlString, int>>(_StringsOffset!.Value);
        }
    }

}