// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CDirectPlaybackInstanceDataImpl : SchemaClass, CDirectPlaybackInstanceData
{
    public CDirectPlaybackInstanceDataImpl(nint handle) : base(handle) { }

    private static nint? _TargetPositionOffset;

    public ref Vector TargetPosition
    {
        get
        {
            _TargetPositionOffset = _TargetPositionOffset ?? Schema.GetOffset(0x280B3A71F028CBBF);
            return ref _Handle.AsRef<Vector>(_TargetPositionOffset!.Value);
        }
    }
    private static nint? _TargetFacingOffset;

    public ref float TargetFacing
    {
        get
        {
            _TargetFacingOffset = _TargetFacingOffset ?? Schema.GetOffset(0x280B3A71F246190C);
            return ref _Handle.AsRef<float>(_TargetFacingOffset!.Value);
        }
    }
    private static nint? _InterpEndTimeOffset;

    public ref float InterpEndTime
    {
        get
        {
            _InterpEndTimeOffset = _InterpEndTimeOffset ?? Schema.GetOffset(0x280B3A71065C232B);
            return ref _Handle.AsRef<float>(_InterpEndTimeOffset!.Value);
        }
    }
    public ISchemaFixedArray<float> Weights
    {
        get => new SchemaFixedArray<float>(_Handle, 0x280B3A7177B2F91E, 4, 4, 4);
    }
    public ISchemaClassFixedArray<SequenceData> Sequences
    {
        get => new SchemaClassFixedArray<SequenceData>(_Handle, 0x280B3A713992EBA1, 4, 56, 4);
    }
    private static nint? _CurrentSequenceIndexOffset;

    public ref uint CurrentSequenceIndex
    {
        get
        {
            _CurrentSequenceIndexOffset = _CurrentSequenceIndexOffset ?? Schema.GetOffset(0x280B3A7195BCA389);
            return ref _Handle.AsRef<uint>(_CurrentSequenceIndexOffset!.Value);
        }
    }
    private static nint? _CurrentSequenceDataOffset;

    public SchemaUntypedField CurrentSequenceData
    {
        get
        {
            _CurrentSequenceDataOffset = _CurrentSequenceDataOffset ?? Schema.GetOffset(0x280B3A71B3502A9B);
            return new SchemaUntypedField(_Handle + _CurrentSequenceDataOffset!.Value);
        }
    }
    private static nint? _FadeInTimeOffset;

    public ref float FadeInTime
    {
        get
        {
            _FadeInTimeOffset = _FadeInTimeOffset ?? Schema.GetOffset(0x280B3A711F0255B3);
            return ref _Handle.AsRef<float>(_FadeInTimeOffset!.Value);
        }
    }
    private static nint? _FadeOutTimeOffset;

    public ref float FadeOutTime
    {
        get
        {
            _FadeOutTimeOffset = _FadeOutTimeOffset ?? Schema.GetOffset(0x280B3A71E86D2FC2);
            return ref _Handle.AsRef<float>(_FadeOutTimeOffset!.Value);
        }
    }
    private static nint? _ForcedCycleOffset;

    public SchemaUntypedField ForcedCycle
    {
        get
        {
            _ForcedCycleOffset = _ForcedCycleOffset ?? Schema.GetOffset(0x280B3A7110FE2984);
            return new SchemaUntypedField(_Handle + _ForcedCycleOffset!.Value);
        }
    }
    private static nint? _ResetPendingOffset;

    public ref bool ResetPending
    {
        get
        {
            _ResetPendingOffset = _ResetPendingOffset ?? Schema.GetOffset(0x280B3A71BECAA4AB);
            return ref _Handle.AsRef<bool>(_ResetPendingOffset!.Value);
        }
    }
    private static nint? _SequenceCycleZeroTimeOffset;

    public SchemaUntypedField SequenceCycleZeroTime
    {
        get
        {
            _SequenceCycleZeroTimeOffset = _SequenceCycleZeroTimeOffset ?? Schema.GetOffset(0x280B3A7192A3CA95);
            return new SchemaUntypedField(_Handle + _SequenceCycleZeroTimeOffset!.Value);
        }
    }

}