// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CDirectionalBlendInstanceDataImpl : SchemaClass, CDirectionalBlendInstanceData
{
    public CDirectionalBlendInstanceDataImpl(nint handle) : base(handle) { }

    private static nint? _DampedValueOffset;

    public ref float DampedValue
    {
        get
        {
            _DampedValueOffset = _DampedValueOffset ?? Schema.GetOffset(0x5968C1DE0EAD75CB);
            return ref _Handle.AsRef<float>(_DampedValueOffset!.Value);
        }
    }
    private static nint? _CycleOffset;

    public ref float Cycle
    {
        get
        {
            _CycleOffset = _CycleOffset ?? Schema.GetOffset(0x5968C1DE0C77829F);
            return ref _Handle.AsRef<float>(_CycleOffset!.Value);
        }
    }
    private static nint? _PrevCycleOffset;

    public ref float PrevCycle
    {
        get
        {
            _PrevCycleOffset = _PrevCycleOffset ?? Schema.GetOffset(0x5968C1DEAA0F5CF4);
            return ref _Handle.AsRef<float>(_PrevCycleOffset!.Value);
        }
    }
    private static nint? _PlaybackRateOffset;

    public SchemaUntypedField PlaybackRate
    {
        get
        {
            _PlaybackRateOffset = _PlaybackRateOffset ?? Schema.GetOffset(0x5968C1DEC396F9D8);
            return new SchemaUntypedField(_Handle + _PlaybackRateOffset!.Value);
        }
    }
    private static nint? _CycleZeroTimeOffset;

    public SchemaUntypedField CycleZeroTime
    {
        get
        {
            _CycleZeroTimeOffset = _CycleZeroTimeOffset ?? Schema.GetOffset(0x5968C1DE40321698);
            return new SchemaUntypedField(_Handle + _CycleZeroTimeOffset!.Value);
        }
    }
    private static nint? _ResetCycleValueOffset;

    public SchemaUntypedField ResetCycleValue
    {
        get
        {
            _ResetCycleValueOffset = _ResetCycleValueOffset ?? Schema.GetOffset(0x5968C1DE9897AC3F);
            return new SchemaUntypedField(_Handle + _ResetCycleValueOffset!.Value);
        }
    }
    private static nint? _ResetCountOffset;

    public SchemaUntypedField ResetCount
    {
        get
        {
            _ResetCountOffset = _ResetCountOffset ?? Schema.GetOffset(0x5968C1DE89B18BCF);
            return new SchemaUntypedField(_Handle + _ResetCountOffset!.Value);
        }
    }

}