// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CFollowPathInstanceDataImpl : SchemaClass, CFollowPathInstanceData
{
    public CFollowPathInstanceDataImpl(nint handle) : base(handle) { }

    private static nint? _XLastPredictedTransformsDeltasOffset;

    public SchemaUntypedField XLastPredictedTransformsDeltas
    {
        get
        {
            _XLastPredictedTransformsDeltasOffset = _XLastPredictedTransformsDeltasOffset ?? Schema.GetOffset(0x558B9B8B483A040B);
            return new SchemaUntypedField(_Handle + _XLastPredictedTransformsDeltasOffset!.Value);
        }
    }
    private static nint? _DampedTurnValueOffset;

    public ref float DampedTurnValue
    {
        get
        {
            _DampedTurnValueOffset = _DampedTurnValueOffset ?? Schema.GetOffset(0x558B9B8B36AC933E);
            return ref _Handle.AsRef<float>(_DampedTurnValueOffset!.Value);
        }
    }
    private static nint? _TurnAmountOffset;

    public ref float TurnAmount
    {
        get
        {
            _TurnAmountOffset = _TurnAmountOffset ?? Schema.GetOffset(0x558B9B8B9B677100);
            return ref _Handle.AsRef<float>(_TurnAmountOffset!.Value);
        }
    }
    private static nint? _PredictionScaleOffset;

    public SchemaUntypedField PredictionScale
    {
        get
        {
            _PredictionScaleOffset = _PredictionScaleOffset ?? Schema.GetOffset(0x558B9B8BE91D4B2C);
            return new SchemaUntypedField(_Handle + _PredictionScaleOffset!.Value);
        }
    }
    private static nint? _LastPathTimeOffset;

    public ref float LastPathTime
    {
        get
        {
            _LastPathTimeOffset = _LastPathTimeOffset ?? Schema.GetOffset(0x558B9B8BCA380281);
            return ref _Handle.AsRef<float>(_LastPathTimeOffset!.Value);
        }
    }

}