// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CFootAdjustmentInstanceDataImpl : SchemaClass, CFootAdjustmentInstanceData
{
    public CFootAdjustmentInstanceDataImpl(nint handle) : base(handle) { }

    private static nint? _StartTimeOffset;

    public SchemaUntypedField StartTime
    {
        get
        {
            _StartTimeOffset = _StartTimeOffset ?? Schema.GetOffset(0xB15F962667FE9DC4);
            return new SchemaUntypedField(_Handle + _StartTimeOffset!.Value);
        }
    }
    private static nint? _DurationOffset;

    public SchemaUntypedField Duration
    {
        get
        {
            _DurationOffset = _DurationOffset ?? Schema.GetOffset(0xB15F9626BC5E3BAB);
            return new SchemaUntypedField(_Handle + _DurationOffset!.Value);
        }
    }
    private static nint? _StartHeadingWSOffset;

    public ref float StartHeadingWS
    {
        get
        {
            _StartHeadingWSOffset = _StartHeadingWSOffset ?? Schema.GetOffset(0xB15F9626B3AA4A4F);
            return ref _Handle.AsRef<float>(_StartHeadingWSOffset!.Value);
        }
    }

}