// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CGenericShapeProxyImpl : SchemaClass, CGenericShapeProxy
{
    public CGenericShapeProxyImpl(nint handle) : base(handle) { }

    private static nint? _VertsOffset;

    public SchemaUntypedField Verts
    {
        get
        {
            _VertsOffset = _VertsOffset ?? Schema.GetOffset(0xCEAA54A4FCD95543);
            return new SchemaUntypedField(_Handle + _VertsOffset!.Value);
        }
    }

}