// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CInfoChoreoAnchorPositionImpl : SchemaClass, CInfoChoreoAnchorPosition
{
    public CInfoChoreoAnchorPositionImpl(nint handle) : base(handle) { }

    private static nint? _OriginOffset;

    public ref Vector Origin
    {
        get
        {
            _OriginOffset = _OriginOffset ?? Schema.GetOffset(0xFA471256F26E589B);
            return ref _Handle.AsRef<Vector>(_OriginOffset!.Value);
        }
    }
    private static nint? _AnglesOffset;

    public ref QAngle Angles
    {
        get
        {
            _AnglesOffset = _AnglesOffset ?? Schema.GetOffset(0xFA471256EF3F183C);
            return ref _Handle.AsRef<QAngle>(_AnglesOffset!.Value);
        }
    }
    private static nint? _ExtentsMinOffset;

    public ref Vector ExtentsMin
    {
        get
        {
            _ExtentsMinOffset = _ExtentsMinOffset ?? Schema.GetOffset(0xFA47125608FFBE26);
            return ref _Handle.AsRef<Vector>(_ExtentsMinOffset!.Value);
        }
    }
    private static nint? _ExtentsMaxOffset;

    public ref Vector ExtentsMax
    {
        get
        {
            _ExtentsMaxOffset = _ExtentsMaxOffset ?? Schema.GetOffset(0xFA4712561B14F534);
            return ref _Handle.AsRef<Vector>(_ExtentsMaxOffset!.Value);
        }
    }
    private static nint? _RadiusOffset;

    public ref float Radius
    {
        get
        {
            _RadiusOffset = _RadiusOffset ?? Schema.GetOffset(0xFA4712565ACFC08D);
            return ref _Handle.AsRef<float>(_RadiusOffset!.Value);
        }
    }
    private static nint? _ShapeTypeOffset;

    public ref CInfoChoreoLocatorShapeType_t ShapeType
    {
        get
        {
            _ShapeTypeOffset = _ShapeTypeOffset ?? Schema.GetOffset(0xFA471256AE159B72);
            return ref _Handle.AsRef<CInfoChoreoLocatorShapeType_t>(_ShapeTypeOffset!.Value);
        }
    }

}