// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CInfoInteractionImpl : CPointEntityImpl, CInfoInteraction
{
    public CInfoInteractionImpl(nint handle) : base(handle) { }

    private static nint? _SceneRequestOffset;

    public SceneRequestHandle_t SceneRequest
    {
        get
        {
            _SceneRequestOffset = _SceneRequestOffset ?? Schema.GetOffset(0x2E4169EABB616542);
            return new SceneRequestHandle_tImpl(_Handle + _SceneRequestOffset!.Value);
        }
    }
    private static nint? _SceneOpportunityOffset;

    public SceneOpportunityHandle_t SceneOpportunity
    {
        get
        {
            _SceneOpportunityOffset = _SceneOpportunityOffset ?? Schema.GetOffset(0x2E4169EA27E4CFEA);
            return new SceneOpportunityHandle_tImpl(_Handle + _SceneOpportunityOffset!.Value);
        }
    }
    private static nint? _EnabledOffset;

    public ref bool Enabled
    {
        get
        {
            _EnabledOffset = _EnabledOffset ?? Schema.GetOffset(0x2E4169EA6154EB7E);
            return ref _Handle.AsRef<bool>(_EnabledOffset!.Value);
        }
    }
    private static nint? _StartDisabledOffset;

    public ref bool StartDisabled
    {
        get
        {
            _StartDisabledOffset = _StartDisabledOffset ?? Schema.GetOffset(0x2E4169EA61ED0C4F);
            return ref _Handle.AsRef<bool>(_StartDisabledOffset!.Value);
        }
    }
    private static nint? _StrSceneVDataNameOffset;

    public string StrSceneVDataName
    {
        get
        {
            _StrSceneVDataNameOffset = _StrSceneVDataNameOffset ?? Schema.GetOffset(0x2E4169EA39B43AA1);
            return Schema.GetString(_Handle.Read<nint>(_StrSceneVDataNameOffset!.Value));
        }
        set
        {
            _StrSceneVDataNameOffset = _StrSceneVDataNameOffset ?? Schema.GetOffset(0x2E4169EA39B43AA1);
            Schema.SetString(_Handle, _StrSceneVDataNameOffset!.Value, value);
        }
    }
    private static nint? _StrPulseVDataNameOffset;

    public string StrPulseVDataName
    {
        get
        {
            _StrPulseVDataNameOffset = _StrPulseVDataNameOffset ?? Schema.GetOffset(0x2E4169EA6B636C76);
            return Schema.GetString(_Handle.Read<nint>(_StrPulseVDataNameOffset!.Value));
        }
        set
        {
            _StrPulseVDataNameOffset = _StrPulseVDataNameOffset ?? Schema.GetOffset(0x2E4169EA6B636C76);
            Schema.SetString(_Handle, _StrPulseVDataNameOffset!.Value, value);
        }
    }
    private static nint? _RadiusOffset;

    public ref float Radius
    {
        get
        {
            _RadiusOffset = _RadiusOffset ?? Schema.GetOffset(0x2E4169EA5ACFC08D);
            return ref _Handle.AsRef<float>(_RadiusOffset!.Value);
        }
    }
    private static nint? _OwnerFOVOffset;

    public ref float OwnerFOV
    {
        get
        {
            _OwnerFOVOffset = _OwnerFOVOffset ?? Schema.GetOffset(0x2E4169EA98F908F5);
            return ref _Handle.AsRef<float>(_OwnerFOVOffset!.Value);
        }
    }
    private static nint? _StrLocalInterestReqTagsOffset;

    public string StrLocalInterestReqTags
    {
        get
        {
            _StrLocalInterestReqTagsOffset = _StrLocalInterestReqTagsOffset ?? Schema.GetOffset(0x2E4169EAEDCBAC76);
            return Schema.GetString(_Handle.Read<nint>(_StrLocalInterestReqTagsOffset!.Value));
        }
        set
        {
            _StrLocalInterestReqTagsOffset = _StrLocalInterestReqTagsOffset ?? Schema.GetOffset(0x2E4169EAEDCBAC76);
            Schema.SetString(_Handle, _StrLocalInterestReqTagsOffset!.Value, value);
        }
    }
    private static nint? _StrLocalInterestOptTagsOffset;

    public string StrLocalInterestOptTags
    {
        get
        {
            _StrLocalInterestOptTagsOffset = _StrLocalInterestOptTagsOffset ?? Schema.GetOffset(0x2E4169EADF75CBF3);
            return Schema.GetString(_Handle.Read<nint>(_StrLocalInterestOptTagsOffset!.Value));
        }
        set
        {
            _StrLocalInterestOptTagsOffset = _StrLocalInterestOptTagsOffset ?? Schema.GetOffset(0x2E4169EADF75CBF3);
            Schema.SetString(_Handle, _StrLocalInterestOptTagsOffset!.Value, value);
        }
    }
    private static nint? _StrLookTargetOffset;

    public string StrLookTarget
    {
        get
        {
            _StrLookTargetOffset = _StrLookTargetOffset ?? Schema.GetOffset(0x2E4169EAE5A545D6);
            return Schema.GetString(_Handle.Read<nint>(_StrLookTargetOffset!.Value));
        }
        set
        {
            _StrLookTargetOffset = _StrLookTargetOffset ?? Schema.GetOffset(0x2E4169EAE5A545D6);
            Schema.SetString(_Handle, _StrLookTargetOffset!.Value, value);
        }
    }
    private static nint? _DurationOffset;

    public ref float Duration
    {
        get
        {
            _DurationOffset = _DurationOffset ?? Schema.GetOffset(0x2E4169EABC5E3BAB);
            return ref _Handle.AsRef<float>(_DurationOffset!.Value);
        }
    }
    private static nint? _CooldownOffset;

    public ref float Cooldown
    {
        get
        {
            _CooldownOffset = _CooldownOffset ?? Schema.GetOffset(0x2E4169EA4C29079A);
            return ref _Handle.AsRef<float>(_CooldownOffset!.Value);
        }
    }
    private static nint? _RepeatCountOffset;

    public ref int RepeatCount
    {
        get
        {
            _RepeatCountOffset = _RepeatCountOffset ?? Schema.GetOffset(0x2E4169EA03867CBD);
            return ref _Handle.AsRef<int>(_RepeatCountOffset!.Value);
        }
    }
    private static nint? _DisableOnExitOffset;

    public ref bool DisableOnExit
    {
        get
        {
            _DisableOnExitOffset = _DisableOnExitOffset ?? Schema.GetOffset(0x2E4169EAD85EDBA6);
            return ref _Handle.AsRef<bool>(_DisableOnExitOffset!.Value);
        }
    }

}