// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CInfoChoreoAnchorImpl : CPointEntityImpl, CInfoChoreoAnchor
{
    public CInfoChoreoAnchorImpl(nint handle) : base(handle) { }

    private static nint? _TargetEntriesOffset;

    public ref CUtlVector<CInfoChoreoAnchorPosition> TargetEntries
    {
        get
        {
            _TargetEntriesOffset = _TargetEntriesOffset ?? Schema.GetOffset(0x603945D10AC6A8B8);
            return ref _Handle.AsRef<CUtlVector<CInfoChoreoAnchorPosition>>(_TargetEntriesOffset!.Value);
        }
    }
    private static nint? _TargetWarpsOffset;

    public ref CUtlVector<CInfoChoreoAnchorPosition> TargetWarps
    {
        get
        {
            _TargetWarpsOffset = _TargetWarpsOffset ?? Schema.GetOffset(0x603945D185A293FF);
            return ref _Handle.AsRef<CUtlVector<CInfoChoreoAnchorPosition>>(_TargetWarpsOffset!.Value);
        }
    }

}