// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CLeanMatrixInstanceDataImpl : SchemaClass, CLeanMatrixInstanceData
{
    public CLeanMatrixInstanceDataImpl(nint handle) : base(handle) { }

    private static nint? _ValueYOffset;

    public ref float ValueY
    {
        get
        {
            _ValueYOffset = _ValueYOffset ?? Schema.GetOffset(0x4D3827A061D896E7);
            return ref _Handle.AsRef<float>(_ValueYOffset!.Value);
        }
    }
    private static nint? _ValueXOffset;

    public ref float ValueX
    {
        get
        {
            _ValueXOffset = _ValueXOffset ?? Schema.GetOffset(0x4D3827A060D89554);
            return ref _Handle.AsRef<float>(_ValueXOffset!.Value);
        }
    }

}