// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNetworkedCycleImpl : SchemaClass, CNetworkedCycle
{
    public CNetworkedCycleImpl(nint handle) : base(handle) { }

    private static nint? _CycleUnclampedOffset;

    public ref float CycleUnclamped
    {
        get
        {
            _CycleUnclampedOffset = _CycleUnclampedOffset ?? Schema.GetOffset(0x9B2966A572B8BBBE);
            return ref _Handle.AsRef<float>(_CycleUnclampedOffset!.Value);
        }
    }
    private static nint? _PrevCycleUnclampedOffset;

    public ref float PrevCycleUnclamped
    {
        get
        {
            _PrevCycleUnclampedOffset = _PrevCycleUnclampedOffset ?? Schema.GetOffset(0x9B2966A5BD306BDF);
            return ref _Handle.AsRef<float>(_PrevCycleUnclampedOffset!.Value);
        }
    }
    private static nint? _CyclesPerSecondOffset;

    public SchemaUntypedField CyclesPerSecond
    {
        get
        {
            _CyclesPerSecondOffset = _CyclesPerSecondOffset ?? Schema.GetOffset(0x9B2966A544417193);
            return new SchemaUntypedField(_Handle + _CyclesPerSecondOffset!.Value);
        }
    }
    private static nint? _CycleZeroTimeOffset;

    public SchemaUntypedField CycleZeroTime
    {
        get
        {
            _CycleZeroTimeOffset = _CycleZeroTimeOffset ?? Schema.GetOffset(0x9B2966A540321698);
            return new SchemaUntypedField(_Handle + _CycleZeroTimeOffset!.Value);
        }
    }
    private static nint? _ResetCountOffset;

    public SchemaUntypedField ResetCount
    {
        get
        {
            _ResetCountOffset = _ResetCountOffset ?? Schema.GetOffset(0x9B2966A589B18BCF);
            return new SchemaUntypedField(_Handle + _ResetCountOffset!.Value);
        }
    }

}