// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmAimCSNode__CDefinitionImpl : CNmPassthroughNode__CDefinitionImpl, CNmAimCSNode__CDefinition
{
    public CNmAimCSNode__CDefinitionImpl(nint handle) : base(handle) { }

    private static nint? _VerticalAngleNodeIdxOffset;

    public ref short VerticalAngleNodeIdx
    {
        get
        {
            _VerticalAngleNodeIdxOffset = _VerticalAngleNodeIdxOffset ?? Schema.GetOffset(0xE1CD14C20A1F17AD);
            return ref _Handle.AsRef<short>(_VerticalAngleNodeIdxOffset!.Value);
        }
    }
    private static nint? _HorizontalAngleNodeIdxOffset;

    public ref short HorizontalAngleNodeIdx
    {
        get
        {
            _HorizontalAngleNodeIdxOffset = _HorizontalAngleNodeIdxOffset ?? Schema.GetOffset(0xE1CD14C28E2FD3DB);
            return ref _Handle.AsRef<short>(_HorizontalAngleNodeIdxOffset!.Value);
        }
    }
    private static nint? _WeaponCategoryNodeIdxOffset;

    public ref short WeaponCategoryNodeIdx
    {
        get
        {
            _WeaponCategoryNodeIdxOffset = _WeaponCategoryNodeIdxOffset ?? Schema.GetOffset(0xE1CD14C216D198E4);
            return ref _Handle.AsRef<short>(_WeaponCategoryNodeIdxOffset!.Value);
        }
    }
    private static nint? _WeaponTypeNodeIdxOffset;

    public ref short WeaponTypeNodeIdx
    {
        get
        {
            _WeaponTypeNodeIdxOffset = _WeaponTypeNodeIdxOffset ?? Schema.GetOffset(0xE1CD14C247A17C20);
            return ref _Handle.AsRef<short>(_WeaponTypeNodeIdxOffset!.Value);
        }
    }
    private static nint? _WeaponActionNodeIdxOffset;

    public ref short WeaponActionNodeIdx
    {
        get
        {
            _WeaponActionNodeIdxOffset = _WeaponActionNodeIdxOffset ?? Schema.GetOffset(0xE1CD14C21E89B1E6);
            return ref _Handle.AsRef<short>(_WeaponActionNodeIdxOffset!.Value);
        }
    }
    private static nint? _WeaponDropNodeIdxOffset;

    public ref short WeaponDropNodeIdx
    {
        get
        {
            _WeaponDropNodeIdxOffset = _WeaponDropNodeIdxOffset ?? Schema.GetOffset(0xE1CD14C202143DDF);
            return ref _Handle.AsRef<short>(_WeaponDropNodeIdxOffset!.Value);
        }
    }
    private static nint? _IsDefusingNodeIdxOffset;

    public ref short IsDefusingNodeIdx
    {
        get
        {
            _IsDefusingNodeIdxOffset = _IsDefusingNodeIdxOffset ?? Schema.GetOffset(0xE1CD14C22EF39CB7);
            return ref _Handle.AsRef<short>(_IsDefusingNodeIdxOffset!.Value);
        }
    }
    private static nint? _CrouchWeightNodeIdxOffset;

    public ref short CrouchWeightNodeIdx
    {
        get
        {
            _CrouchWeightNodeIdxOffset = _CrouchWeightNodeIdxOffset ?? Schema.GetOffset(0xE1CD14C2F62E5CC2);
            return ref _Handle.AsRef<short>(_CrouchWeightNodeIdxOffset!.Value);
        }
    }
    private static nint? _HandIKBlendInTimeSecondsOffset;

    public ref float HandIKBlendInTimeSeconds
    {
        get
        {
            _HandIKBlendInTimeSecondsOffset = _HandIKBlendInTimeSecondsOffset ?? Schema.GetOffset(0xE1CD14C2CB9B86F0);
            return ref _Handle.AsRef<float>(_HandIKBlendInTimeSecondsOffset!.Value);
        }
    }
    private static nint? _ActionBlendTimeSecondsOffset;

    public ref float ActionBlendTimeSeconds
    {
        get
        {
            _ActionBlendTimeSecondsOffset = _ActionBlendTimeSecondsOffset ?? Schema.GetOffset(0xE1CD14C2E3226BAE);
            return ref _Handle.AsRef<float>(_ActionBlendTimeSecondsOffset!.Value);
        }
    }
    private static nint? _PlantingBlendTimeSecondsOffset;

    public ref float PlantingBlendTimeSeconds
    {
        get
        {
            _PlantingBlendTimeSecondsOffset = _PlantingBlendTimeSecondsOffset ?? Schema.GetOffset(0xE1CD14C27FD19463);
            return ref _Handle.AsRef<float>(_PlantingBlendTimeSecondsOffset!.Value);
        }
    }

}