// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmFootIKNode__CDefinitionImpl : CNmPassthroughNode__CDefinitionImpl, CNmFootIKNode__CDefinition
{
    public CNmFootIKNode__CDefinitionImpl(nint handle) : base(handle) { }

    private static nint? _LeftEffectorBoneIDOffset;

    public ref CGlobalSymbol LeftEffectorBoneID
    {
        get
        {
            _LeftEffectorBoneIDOffset = _LeftEffectorBoneIDOffset ?? Schema.GetOffset(0xFDCD093DC1B4D76B);
            return ref _Handle.AsRef<CGlobalSymbol>(_LeftEffectorBoneIDOffset!.Value);
        }
    }
    private static nint? _RightEffectorBoneIDOffset;

    public ref CGlobalSymbol RightEffectorBoneID
    {
        get
        {
            _RightEffectorBoneIDOffset = _RightEffectorBoneIDOffset ?? Schema.GetOffset(0xFDCD093D3AB67C76);
            return ref _Handle.AsRef<CGlobalSymbol>(_RightEffectorBoneIDOffset!.Value);
        }
    }
    private static nint? _LeftTargetNodeIdxOffset;

    public ref short LeftTargetNodeIdx
    {
        get
        {
            _LeftTargetNodeIdxOffset = _LeftTargetNodeIdxOffset ?? Schema.GetOffset(0xFDCD093D20236F00);
            return ref _Handle.AsRef<short>(_LeftTargetNodeIdxOffset!.Value);
        }
    }
    private static nint? _RightTargetNodeIdxOffset;

    public ref short RightTargetNodeIdx
    {
        get
        {
            _RightTargetNodeIdxOffset = _RightTargetNodeIdxOffset ?? Schema.GetOffset(0xFDCD093D66AE7DE7);
            return ref _Handle.AsRef<short>(_RightTargetNodeIdxOffset!.Value);
        }
    }
    private static nint? _EnabledNodeIdxOffset;

    public ref short EnabledNodeIdx
    {
        get
        {
            _EnabledNodeIdxOffset = _EnabledNodeIdxOffset ?? Schema.GetOffset(0xFDCD093DF7CDF5E9);
            return ref _Handle.AsRef<short>(_EnabledNodeIdxOffset!.Value);
        }
    }
    private static nint? _BlendTimeSecondsOffset;

    public ref float BlendTimeSeconds
    {
        get
        {
            _BlendTimeSecondsOffset = _BlendTimeSecondsOffset ?? Schema.GetOffset(0xFDCD093D6D3A08FC);
            return ref _Handle.AsRef<float>(_BlendTimeSecondsOffset!.Value);
        }
    }
    private static nint? _BlendModeOffset;

    public ref NmIKBlendMode_t BlendMode
    {
        get
        {
            _BlendModeOffset = _BlendModeOffset ?? Schema.GetOffset(0xFDCD093D8D5006AB);
            return ref _Handle.AsRef<NmIKBlendMode_t>(_BlendModeOffset!.Value);
        }
    }
    private static nint? _IsTargetInWorldSpaceOffset;

    public ref bool IsTargetInWorldSpace
    {
        get
        {
            _IsTargetInWorldSpaceOffset = _IsTargetInWorldSpaceOffset ?? Schema.GetOffset(0xFDCD093D5F56E0C5);
            return ref _Handle.AsRef<bool>(_IsTargetInWorldSpaceOffset!.Value);
        }
    }

}