// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmSnapWeaponNode__CDefinitionImpl : CNmPassthroughNode__CDefinitionImpl, CNmSnapWeaponNode__CDefinition
{
    public CNmSnapWeaponNode__CDefinitionImpl(nint handle) : base(handle) { }

    private static nint? _FlashedAmountNodeIdxOffset;

    public ref short FlashedAmountNodeIdx
    {
        get
        {
            _FlashedAmountNodeIdxOffset = _FlashedAmountNodeIdxOffset ?? Schema.GetOffset(0x60733C8950F53E73);
            return ref _Handle.AsRef<short>(_FlashedAmountNodeIdxOffset!.Value);
        }
    }
    private static nint? _WeaponCategoryNodeIdxOffset;

    public ref short WeaponCategoryNodeIdx
    {
        get
        {
            _WeaponCategoryNodeIdxOffset = _WeaponCategoryNodeIdxOffset ?? Schema.GetOffset(0x60733C8916D198E4);
            return ref _Handle.AsRef<short>(_WeaponCategoryNodeIdxOffset!.Value);
        }
    }
    private static nint? _WeaponTypeNodeIdxOffset;

    public ref short WeaponTypeNodeIdx
    {
        get
        {
            _WeaponTypeNodeIdxOffset = _WeaponTypeNodeIdxOffset ?? Schema.GetOffset(0x60733C8947A17C20);
            return ref _Handle.AsRef<short>(_WeaponTypeNodeIdxOffset!.Value);
        }
    }

}