// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPulseCell_Outflow_PlayVOLine__CursorState_tImpl : SchemaClass, CPulseCell_Outflow_PlayVOLine__CursorState_t
{
    public CPulseCell_Outflow_PlayVOLine__CursorState_tImpl(nint handle) : base(handle) { }

    private static nint? _SceneInstanceOffset;

    public ref CHandle<CBaseEntity> SceneInstance
    {
        get
        {
            _SceneInstanceOffset = _SceneInstanceOffset ?? Schema.GetOffset(0x9C2DCC0EC967C210);
            return ref _Handle.AsRef<CHandle<CBaseEntity>>(_SceneInstanceOffset!.Value);
        }
    }

}