// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPulseCell_BooleanSwitchStateImpl : CPulseCell_BaseStateImpl, CPulseCell_BooleanSwitchState
{
    public CPulseCell_BooleanSwitchStateImpl(nint handle) : base(handle) { }

    private static nint? _ConditionOffset;

    public PulseObservableBoolExpression_t Condition
    {
        get
        {
            _ConditionOffset = _ConditionOffset ?? Schema.GetOffset(0xB0380EFD5F2A883E);
            return new PulseObservableBoolExpression_tImpl(_Handle + _ConditionOffset!.Value);
        }
    }
    private static nint? _AlwaysOffset;

    public CPulse_OutflowConnection Always
    {
        get
        {
            _AlwaysOffset = _AlwaysOffset ?? Schema.GetOffset(0xB0380EFDD5D76864);
            return new CPulse_OutflowConnectionImpl(_Handle + _AlwaysOffset!.Value);
        }
    }
    private static nint? _WhenTrueOffset;

    public CPulse_OutflowConnection WhenTrue
    {
        get
        {
            _WhenTrueOffset = _WhenTrueOffset ?? Schema.GetOffset(0xB0380EFDB329ED61);
            return new CPulse_OutflowConnectionImpl(_Handle + _WhenTrueOffset!.Value);
        }
    }
    private static nint? _WhenFalseOffset;

    public CPulse_OutflowConnection WhenFalse
    {
        get
        {
            _WhenFalseOffset = _WhenFalseOffset ?? Schema.GetOffset(0xB0380EFD4DD1A01C);
            return new CPulse_OutflowConnectionImpl(_Handle + _WhenFalseOffset!.Value);
        }
    }

}