// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPulseCell_Outflow_PlayVCD__VCDRequirementInfo_tImpl : SchemaClass, CPulseCell_Outflow_PlayVCD__VCDRequirementInfo_t
{
    public CPulseCell_Outflow_PlayVCD__VCDRequirementInfo_tImpl(nint handle) : base(handle) { }

    private static nint? _EventIDOffset;

    public ref int EventID
    {
        get
        {
            _EventIDOffset = _EventIDOffset ?? Schema.GetOffset(0xB1E264BFC9E05126);
            return ref _Handle.AsRef<int>(_EventIDOffset!.Value);
        }
    }
    private static nint? _OutflowOffset;

    public CPulse_OutflowConnection Outflow
    {
        get
        {
            _OutflowOffset = _OutflowOffset ?? Schema.GetOffset(0xB1E264BFA23DA55B);
            return new CPulse_OutflowConnectionImpl(_Handle + _OutflowOffset!.Value);
        }
    }

}