// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CRelativeTransformImpl : SchemaClass, CRelativeTransform
{
    public CRelativeTransformImpl(nint handle) : base(handle) { }

    private static nint? _TransformIsWorldSpaceOffset;

    public ref bool TransformIsWorldSpace
    {
        get
        {
            _TransformIsWorldSpaceOffset = _TransformIsWorldSpaceOffset ?? Schema.GetOffset(0xE7D2AACA45DC288D);
            return ref _Handle.AsRef<bool>(_TransformIsWorldSpaceOffset!.Value);
        }
    }
    private static nint? _TransformOffset;

    public ref CTransform Transform
    {
        get
        {
            _TransformOffset = _TransformOffset ?? Schema.GetOffset(0xE7D2AACA3A9A393B);
            return ref _Handle.AsRef<CTransform>(_TransformOffset!.Value);
        }
    }
    private static nint? _TransformWSOffset;

    public ref CTransform TransformWS
    {
        get
        {
            _TransformWSOffset = _TransformWSOffset ?? Schema.GetOffset(0xE7D2AACA567787F5);
            return ref _Handle.AsRef<CTransform>(_TransformWSOffset!.Value);
        }
    }
    private static nint? _EntityOffset;

    public ref CHandle<CBaseEntity> Entity
    {
        get
        {
            _EntityOffset = _EntityOffset ?? Schema.GetOffset(0xE7D2AACA6EBADCB0);
            return ref _Handle.AsRef<CHandle<CBaseEntity>>(_EntityOffset!.Value);
        }
    }

}