// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSceneOpportunityImpl : SchemaClass, CSceneOpportunity
{
    public CSceneOpportunityImpl(nint handle) : base(handle) { }

    private static nint? _OwnerOffset;

    public ref CHandle<CBaseEntity> Owner
    {
        get
        {
            _OwnerOffset = _OwnerOffset ?? Schema.GetOffset(0xB9D0A32BF6D89572);
            return ref _Handle.AsRef<CHandle<CBaseEntity>>(_OwnerOffset!.Value);
        }
    }
    private static nint? _HandleOffset;

    public SceneOpportunityHandle_t Handle
    {
        get
        {
            _HandleOffset = _HandleOffset ?? Schema.GetOffset(0xB9D0A32B3A6ED596);
            return new SceneOpportunityHandle_tImpl(_Handle + _HandleOffset!.Value);
        }
    }
    private static nint? _StrInteractVDataNameOffset;

    public string StrInteractVDataName
    {
        get
        {
            _StrInteractVDataNameOffset = _StrInteractVDataNameOffset ?? Schema.GetOffset(0xB9D0A32B8E2741EB);
            return Schema.GetString(_Handle.Read<nint>(_StrInteractVDataNameOffset!.Value));
        }
        set
        {
            _StrInteractVDataNameOffset = _StrInteractVDataNameOffset ?? Schema.GetOffset(0xB9D0A32B8E2741EB);
            Schema.SetString(_Handle, _StrInteractVDataNameOffset!.Value, value);
        }
    }
    private static nint? _EnabledOffset;

    public ref bool Enabled
    {
        get
        {
            _EnabledOffset = _EnabledOffset ?? Schema.GetOffset(0xB9D0A32B6154EB7E);
            return ref _Handle.AsRef<bool>(_EnabledOffset!.Value);
        }
    }
    private static nint? _ActiveOffset;

    public ref bool Active
    {
        get
        {
            _ActiveOffset = _ActiveOffset ?? Schema.GetOffset(0xB9D0A32B8334208F);
            return ref _Handle.AsRef<bool>(_ActiveOffset!.Value);
        }
    }
    private static nint? _PriorityOffset;

    public ref InteractionPriority_t Priority
    {
        get
        {
            _PriorityOffset = _PriorityOffset ?? Schema.GetOffset(0xB9D0A32B794C8D78);
            return ref _Handle.AsRef<InteractionPriority_t>(_PriorityOffset!.Value);
        }
    }
    private static nint? _RadiusOffset;

    public ref float Radius
    {
        get
        {
            _RadiusOffset = _RadiusOffset ?? Schema.GetOffset(0xB9D0A32B5ACFC08D);
            return ref _Handle.AsRef<float>(_RadiusOffset!.Value);
        }
    }
    private static nint? _LocalInterestReqTagsOffset;

    public SceneInterestTags_t LocalInterestReqTags
    {
        get
        {
            _LocalInterestReqTagsOffset = _LocalInterestReqTagsOffset ?? Schema.GetOffset(0xB9D0A32BB6EC5B63);
            return new SceneInterestTags_tImpl(_Handle + _LocalInterestReqTagsOffset!.Value);
        }
    }
    private static nint? _LocalInterestOptTagsOffset;

    public SceneInterestTags_t LocalInterestOptTags
    {
        get
        {
            _LocalInterestOptTagsOffset = _LocalInterestOptTagsOffset ?? Schema.GetOffset(0xB9D0A32B2DEC4E36);
            return new SceneInterestTags_tImpl(_Handle + _LocalInterestOptTagsOffset!.Value);
        }
    }
    private static nint? _OwnerFOVOffset;

    public ref float OwnerFOV
    {
        get
        {
            _OwnerFOVOffset = _OwnerFOVOffset ?? Schema.GetOffset(0xB9D0A32B98F908F5);
            return ref _Handle.AsRef<float>(_OwnerFOVOffset!.Value);
        }
    }
    private static nint? _ActorListOffset;

    public ref CUtlVector<SceneOpportunityActor_t> ActorList
    {
        get
        {
            _ActorListOffset = _ActorListOffset ?? Schema.GetOffset(0xB9D0A32BB74EEFD6);
            return ref _Handle.AsRef<CUtlVector<SceneOpportunityActor_t>>(_ActorListOffset!.Value);
        }
    }
    private static nint? _LookTargetOffset;

    public ref CHandle<CBaseEntity> LookTarget
    {
        get
        {
            _LookTargetOffset = _LookTargetOffset ?? Schema.GetOffset(0xB9D0A32B3361F745);
            return ref _Handle.AsRef<CHandle<CBaseEntity>>(_LookTargetOffset!.Value);
        }
    }
    private static nint? _DurationOffset;

    public ref float Duration
    {
        get
        {
            _DurationOffset = _DurationOffset ?? Schema.GetOffset(0xB9D0A32BBC5E3BAB);
            return ref _Handle.AsRef<float>(_DurationOffset!.Value);
        }
    }
    private static nint? _TStartTimeOffset;

    public GameTime_t TStartTime
    {
        get
        {
            _TStartTimeOffset = _TStartTimeOffset ?? Schema.GetOffset(0xB9D0A32BA79FCD08);
            return new GameTime_tImpl(_Handle + _TStartTimeOffset!.Value);
        }
    }
    private static nint? _CooldownOffset;

    public ref float Cooldown
    {
        get
        {
            _CooldownOffset = _CooldownOffset ?? Schema.GetOffset(0xB9D0A32B4C29079A);
            return ref _Handle.AsRef<float>(_CooldownOffset!.Value);
        }
    }
    private static nint? _TCooldownTimeOffset;

    public GameTime_t TCooldownTime
    {
        get
        {
            _TCooldownTimeOffset = _TCooldownTimeOffset ?? Schema.GetOffset(0xB9D0A32B6C9AB0EF);
            return new GameTime_tImpl(_Handle + _TCooldownTimeOffset!.Value);
        }
    }
    private static nint? _RepeatCountOffset;

    public ref int RepeatCount
    {
        get
        {
            _RepeatCountOffset = _RepeatCountOffset ?? Schema.GetOffset(0xB9D0A32B03867CBD);
            return ref _Handle.AsRef<int>(_RepeatCountOffset!.Value);
        }
    }
    private static nint? _DisableOnExitOffset;

    public ref bool DisableOnExit
    {
        get
        {
            _DisableOnExitOffset = _DisableOnExitOffset ?? Schema.GetOffset(0xB9D0A32BD85EDBA6);
            return ref _Handle.AsRef<bool>(_DisableOnExitOffset!.Value);
        }
    }

}