// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSceneCriteriaImpl : SchemaClass, CSceneCriteria
{
    public CSceneCriteriaImpl(nint handle) : base(handle) { }

    private static nint? _OwnerOffset;

    public ref CHandle<CBaseEntity> Owner
    {
        get
        {
            _OwnerOffset = _OwnerOffset ?? Schema.GetOffset(0xBA12BB03F6D89572);
            return ref _Handle.AsRef<CHandle<CBaseEntity>>(_OwnerOffset!.Value);
        }
    }
    private static nint? _PriorityOffset;

    public ref InteractionPriority_t Priority
    {
        get
        {
            _PriorityOffset = _PriorityOffset ?? Schema.GetOffset(0xBA12BB03794C8D78);
            return ref _Handle.AsRef<InteractionPriority_t>(_PriorityOffset!.Value);
        }
    }
    private static nint? _InterestReqTagsOffset;

    public SceneInterestTags_t InterestReqTags
    {
        get
        {
            _InterestReqTagsOffset = _InterestReqTagsOffset ?? Schema.GetOffset(0xBA12BB0301581374);
            return new SceneInterestTags_tImpl(_Handle + _InterestReqTagsOffset!.Value);
        }
    }
    private static nint? _InterestOptTagsOffset;

    public SceneInterestTags_t InterestOptTags
    {
        get
        {
            _InterestOptTagsOffset = _InterestOptTagsOffset ?? Schema.GetOffset(0xBA12BB0362426B31);
            return new SceneInterestTags_tImpl(_Handle + _InterestOptTagsOffset!.Value);
        }
    }

}