// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSceneRequestImpl : SchemaClass, CSceneRequest
{
    public CSceneRequestImpl(nint handle) : base(handle) { }

    private static nint? _PayloadVDataNameOffset;

    public string PayloadVDataName
    {
        get
        {
            _PayloadVDataNameOffset = _PayloadVDataNameOffset ?? Schema.GetOffset(0x7171CEFD908DA6B);
            return Schema.GetString(_Handle.Read<nint>(_PayloadVDataNameOffset!.Value));
        }
        set
        {
            _PayloadVDataNameOffset = _PayloadVDataNameOffset ?? Schema.GetOffset(0x7171CEFD908DA6B);
            Schema.SetString(_Handle, _PayloadVDataNameOffset!.Value, value);
        }
    }
    private static nint? _HandleOffset;

    public SceneRequestHandle_t Handle
    {
        get
        {
            _HandleOffset = _HandleOffset ?? Schema.GetOffset(0x7171CEF3A6ED596);
            return new SceneRequestHandle_tImpl(_Handle + _HandleOffset!.Value);
        }
    }
    private static nint? _StateOffset;

    public ref ESceneRequestState_t State
    {
        get
        {
            _StateOffset = _StateOffset ?? Schema.GetOffset(0x7171CEFB83E5A16);
            return ref _Handle.AsRef<ESceneRequestState_t>(_StateOffset!.Value);
        }
    }
    private static nint? _NPCBehaviorOverrideOffset;

    public ref ENPCBehaviorOverride_t NPCBehaviorOverride
    {
        get
        {
            _NPCBehaviorOverrideOffset = _NPCBehaviorOverrideOffset ?? Schema.GetOffset(0x7171CEFEC2B4C7E);
            return ref _Handle.AsRef<ENPCBehaviorOverride_t>(_NPCBehaviorOverrideOffset!.Value);
        }
    }
    private static nint? _ActorMapOffset;

    public ref CUtlVector<SceneRequestTargetMapPair_t> ActorMap
    {
        get
        {
            _ActorMapOffset = _ActorMapOffset ?? Schema.GetOffset(0x7171CEFEA2DAFE4);
            return ref _Handle.AsRef<CUtlVector<SceneRequestTargetMapPair_t>>(_ActorMapOffset!.Value);
        }
    }
    private static nint? _AnchorMapOffset;

    public ref CUtlVector<SceneRequestTargetMapPair_t> AnchorMap
    {
        get
        {
            _AnchorMapOffset = _AnchorMapOffset ?? Schema.GetOffset(0x7171CEFB430D95A);
            return ref _Handle.AsRef<CUtlVector<SceneRequestTargetMapPair_t>>(_AnchorMapOffset!.Value);
        }
    }
    private static nint? _GraphMapOffset;

    public ref CUtlVector<SceneRequestTargetMapPair_t> GraphMap
    {
        get
        {
            _GraphMapOffset = _GraphMapOffset ?? Schema.GetOffset(0x7171CEF1D0F66E7);
            return ref _Handle.AsRef<CUtlVector<SceneRequestTargetMapPair_t>>(_GraphMapOffset!.Value);
        }
    }
    private static nint? _OwnerOffset;

    public ref CHandle<CBaseEntity> Owner
    {
        get
        {
            _OwnerOffset = _OwnerOffset ?? Schema.GetOffset(0x7171CEFF6D89572);
            return ref _Handle.AsRef<CHandle<CBaseEntity>>(_OwnerOffset!.Value);
        }
    }
    private static nint? _NameMapKV3Offset;

    public SchemaUntypedField NameMapKV3
    {
        get
        {
            _NameMapKV3Offset = _NameMapKV3Offset ?? Schema.GetOffset(0x7171CEFD812ABA2);
            return new SchemaUntypedField(_Handle + _NameMapKV3Offset!.Value);
        }
    }

}