// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CScenePayloadVDataImpl : SchemaClass, CScenePayloadVData
{
    public CScenePayloadVDataImpl(nint handle) : base(handle) { }

    private static nint? _NPCBehaviorOffset;

    public ref ENPCBehaviorOverride_t NPCBehavior
    {
        get
        {
            _NPCBehaviorOffset = _NPCBehaviorOffset ?? Schema.GetOffset(0xFFFC06CA0F806B01);
            return ref _Handle.AsRef<ENPCBehaviorOverride_t>(_NPCBehaviorOffset!.Value);
        }
    }
    private static nint? _PulseFileOffset;

    public SchemaUntypedField PulseFile
    {
        get
        {
            _PulseFileOffset = _PulseFileOffset ?? Schema.GetOffset(0xFFFC06CA6C17DEDD);
            return new SchemaUntypedField(_Handle + _PulseFileOffset!.Value);
        }
    }
    private static nint? _SceneFileOffset;

    public SchemaUntypedField SceneFile
    {
        get
        {
            _SceneFileOffset = _SceneFileOffset ?? Schema.GetOffset(0xFFFC06CA9E4FBF74);
            return new SchemaUntypedField(_Handle + _SceneFileOffset!.Value);
        }
    }
    private static nint? _PriorityOffset;

    public ref InteractionPriority_t Priority
    {
        get
        {
            _PriorityOffset = _PriorityOffset ?? Schema.GetOffset(0xFFFC06CA794C8D78);
            return ref _Handle.AsRef<InteractionPriority_t>(_PriorityOffset!.Value);
        }
    }

}