// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSndSeqInstBaseSchemaImpl : SchemaClass, CSndSeqInstBaseSchema
{
    public CSndSeqInstBaseSchemaImpl(nint handle) : base(handle) { }

    private static nint? _TypeOffset;

    public ref SndSeqInstrumentType_t Type
    {
        get
        {
            _TypeOffset = _TypeOffset ?? Schema.GetOffset(0xEEA54D3618853D59);
            return ref _Handle.AsRef<SndSeqInstrumentType_t>(_TypeOffset!.Value);
        }
    }
    private static nint? _PlayerTypeOffset;

    public ref SndSeqPlayerType_t PlayerType
    {
        get
        {
            _PlayerTypeOffset = _PlayerTypeOffset ?? Schema.GetOffset(0xEEA54D3641495B74);
            return ref _Handle.AsRef<SndSeqPlayerType_t>(_PlayerTypeOffset!.Value);
        }
    }
    private static nint? _StopCurrentEventsOffset;

    public ref bool StopCurrentEvents
    {
        get
        {
            _StopCurrentEventsOffset = _StopCurrentEventsOffset ?? Schema.GetOffset(0xEEA54D3613A9CEBF);
            return ref _Handle.AsRef<bool>(_StopCurrentEventsOffset!.Value);
        }
    }
    private static nint? _BPMOffset;

    public ref float BPM
    {
        get
        {
            _BPMOffset = _BPMOffset ?? Schema.GetOffset(0xEEA54D36E4D810F8);
            return ref _Handle.AsRef<float>(_BPMOffset!.Value);
        }
    }
    private static nint? _BPMFactorOffset;

    public ref float BPMFactor
    {
        get
        {
            _BPMFactorOffset = _BPMFactorOffset ?? Schema.GetOffset(0xEEA54D36DC81506B);
            return ref _Handle.AsRef<float>(_BPMFactorOffset!.Value);
        }
    }
    private static nint? _BPMInvFactorOffset;

    public ref float BPMInvFactor
    {
        get
        {
            _BPMInvFactorOffset = _BPMInvFactorOffset ?? Schema.GetOffset(0xEEA54D365569EE9C);
            return ref _Handle.AsRef<float>(_BPMInvFactorOffset!.Value);
        }
    }

}