// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSndSeqInstMidiSamplerImpl : CSndSeqInstBaseSchemaImpl, CSndSeqInstMidiSampler
{
    public CSndSeqInstMidiSamplerImpl(nint handle) : base(handle) { }

    private static nint? _IsSoundEventOffset;

    public ref bool IsSoundEvent
    {
        get
        {
            _IsSoundEventOffset = _IsSoundEventOffset ?? Schema.GetOffset(0xF24DD653490F281C);
            return ref _Handle.AsRef<bool>(_IsSoundEventOffset!.Value);
        }
    }
    private static nint? _StopPreviousOffset;

    public ref bool StopPrevious
    {
        get
        {
            _StopPreviousOffset = _StopPreviousOffset ?? Schema.GetOffset(0xF24DD653B4A594C8);
            return ref _Handle.AsRef<bool>(_StopPreviousOffset!.Value);
        }
    }
    private static nint? _MinNoteOffset;

    public ref byte MinNote
    {
        get
        {
            _MinNoteOffset = _MinNoteOffset ?? Schema.GetOffset(0xF24DD653E43EC4EB);
            return ref _Handle.AsRef<byte>(_MinNoteOffset!.Value);
        }
    }
    private static nint? _MaxNoteOffset;

    public ref byte MaxNote
    {
        get
        {
            _MaxNoteOffset = _MaxNoteOffset ?? Schema.GetOffset(0xF24DD6533D015E2D);
            return ref _Handle.AsRef<byte>(_MaxNoteOffset!.Value);
        }
    }
    private static nint? _MinVelocityAttenOffset;

    public ref float MinVelocityAtten
    {
        get
        {
            _MinVelocityAttenOffset = _MinVelocityAttenOffset ?? Schema.GetOffset(0xF24DD65350D5C2B2);
            return ref _Handle.AsRef<float>(_MinVelocityAttenOffset!.Value);
        }
    }
    private static nint? _MaxVelocityAttenOffset;

    public ref float MaxVelocityAtten
    {
        get
        {
            _MaxVelocityAttenOffset = _MaxVelocityAttenOffset ?? Schema.GetOffset(0xF24DD6536156C9B4);
            return ref _Handle.AsRef<float>(_MaxVelocityAttenOffset!.Value);
        }
    }
    private static nint? _AttackOffset;

    public ref float Attack
    {
        get
        {
            _AttackOffset = _AttackOffset ?? Schema.GetOffset(0xF24DD6530A6A5BE7);
            return ref _Handle.AsRef<float>(_AttackOffset!.Value);
        }
    }
    private static nint? _ReleaseOffset;

    public ref float Release
    {
        get
        {
            _ReleaseOffset = _ReleaseOffset ?? Schema.GetOffset(0xF24DD65325AF90E4);
            return ref _Handle.AsRef<float>(_ReleaseOffset!.Value);
        }
    }
    private static nint? _BeatEnvelopesOffset;

    public ref bool BeatEnvelopes
    {
        get
        {
            _BeatEnvelopesOffset = _BeatEnvelopesOffset ?? Schema.GetOffset(0xF24DD653A721F512);
            return ref _Handle.AsRef<bool>(_BeatEnvelopesOffset!.Value);
        }
    }
    private static nint? _NextVoiceSlotOffset;

    public ref byte NextVoiceSlot
    {
        get
        {
            _NextVoiceSlotOffset = _NextVoiceSlotOffset ?? Schema.GetOffset(0xF24DD6535AEAA202);
            return ref _Handle.AsRef<byte>(_NextVoiceSlotOffset!.Value);
        }
    }
    private static nint? _SoundEventHashOffset;

    public ref uint SoundEventHash
    {
        get
        {
            _SoundEventHashOffset = _SoundEventHashOffset ?? Schema.GetOffset(0xF24DD6537DC8F8CE);
            return ref _Handle.AsRef<uint>(_SoundEventHashOffset!.Value);
        }
    }

}