// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSosGroupActionOcclusionSchemaImpl : CSosGroupActionSchemaImpl, CSosGroupActionOcclusionSchema
{
    public CSosGroupActionOcclusionSchemaImpl(nint handle) : base(handle) { }

    private static nint? _CalculationIntervalOffset;

    public ref float CalculationInterval
    {
        get
        {
            _CalculationIntervalOffset = _CalculationIntervalOffset ?? Schema.GetOffset(0x4ED94014C8AEEA3D);
            return ref _Handle.AsRef<float>(_CalculationIntervalOffset!.Value);
        }
    }
    private static nint? _RadiusOffset;

    public ref float Radius
    {
        get
        {
            _RadiusOffset = _RadiusOffset ?? Schema.GetOffset(0x4ED940145ACFC08D);
            return ref _Handle.AsRef<float>(_RadiusOffset!.Value);
        }
    }
    private static nint? _OcclusionScaleOffset;

    public ref float OcclusionScale
    {
        get
        {
            _OcclusionScaleOffset = _OcclusionScaleOffset ?? Schema.GetOffset(0x4ED94014FF8BE452);
            return ref _Handle.AsRef<float>(_OcclusionScaleOffset!.Value);
        }
    }
    private static nint? _OcclusionMinOffset;

    public ref float OcclusionMin
    {
        get
        {
            _OcclusionMinOffset = _OcclusionMinOffset ?? Schema.GetOffset(0x4ED9401462E6EDCC);
            return ref _Handle.AsRef<float>(_OcclusionMinOffset!.Value);
        }
    }
    private static nint? _OcclusionMaxOffset;

    public ref float OcclusionMax
    {
        get
        {
            _OcclusionMaxOffset = _OcclusionMaxOffset ?? Schema.GetOffset(0x4ED9401470D37C1E);
            return ref _Handle.AsRef<float>(_OcclusionMaxOffset!.Value);
        }
    }
    private static nint? _TestDepthOffset;

    public ref float TestDepth
    {
        get
        {
            _TestDepthOffset = _TestDepthOffset ?? Schema.GetOffset(0x4ED94014DD26B024);
            return ref _Handle.AsRef<float>(_TestDepthOffset!.Value);
        }
    }

}