// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CStateNodeInstanceDataImpl : SchemaClass, CStateNodeInstanceData
{
    public CStateNodeInstanceDataImpl(nint handle) : base(handle) { }

    private static nint? _StateWeightsOffset;

    public SchemaUntypedField StateWeights
    {
        get
        {
            _StateWeightsOffset = _StateWeightsOffset ?? Schema.GetOffset(0x6EAD9ECCC8386A37);
            return new SchemaUntypedField(_Handle + _StateWeightsOffset!.Value);
        }
    }
    private static nint? _TransitionVelocityDeltaWSOffset;

    public ref Vector TransitionVelocityDeltaWS
    {
        get
        {
            _TransitionVelocityDeltaWSOffset = _TransitionVelocityDeltaWSOffset ?? Schema.GetOffset(0x6EAD9ECCFFF02B9B);
            return ref _Handle.AsRef<Vector>(_TransitionVelocityDeltaWSOffset!.Value);
        }
    }
    private static nint? _CurrentStateStartTimeOffset;

    public SchemaUntypedField CurrentStateStartTime
    {
        get
        {
            _CurrentStateStartTimeOffset = _CurrentStateStartTimeOffset ?? Schema.GetOffset(0x6EAD9ECCEE295544);
            return new SchemaUntypedField(_Handle + _CurrentStateStartTimeOffset!.Value);
        }
    }
    private static nint? _ResetCountOffset;

    public SchemaUntypedField ResetCount
    {
        get
        {
            _ResetCountOffset = _ResetCountOffset ?? Schema.GetOffset(0x6EAD9ECC89B18BCF);
            return new SchemaUntypedField(_Handle + _ResetCountOffset!.Value);
        }
    }

}