// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CTestPulseIO__FloatStringArgs_tImpl : SchemaClass, CTestPulseIO__FloatStringArgs_t
{
    public CTestPulseIO__FloatStringArgs_tImpl(nint handle) : base(handle) { }

    private static nint? _OutFloatOffset;

    public ref float OutFloat
    {
        get
        {
            _OutFloatOffset = _OutFloatOffset ?? Schema.GetOffset(0xA77E2E5078AD32D9);
            return ref _Handle.AsRef<float>(_OutFloatOffset!.Value);
        }
    }
    private static nint? _StrOutStringOffset;

    public string StrOutString
    {
        get
        {
            _StrOutStringOffset = _StrOutStringOffset ?? Schema.GetOffset(0xA77E2E5098D585D5);
            return Schema.GetString(_Handle.Read<nint>(_StrOutStringOffset!.Value));
        }
        set
        {
            _StrOutStringOffset = _StrOutStringOffset ?? Schema.GetOffset(0xA77E2E5098D585D5);
            Schema.SetString(_Handle, _StrOutStringOffset!.Value, value);
        }
    }

}