// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CTestPulseIO__EntityHandleIntArgs_tImpl : SchemaClass, CTestPulseIO__EntityHandleIntArgs_t
{
    public CTestPulseIO__EntityHandleIntArgs_tImpl(nint handle) : base(handle) { }

    private static nint? _HandleAOffset;

    public ref CHandle<CEntityInstance> HandleA
    {
        get
        {
            _HandleAOffset = _HandleAOffset ?? Schema.GetOffset(0x662939E5C52D76D6);
            return ref _Handle.AsRef<CHandle<CEntityInstance>>(_HandleAOffset!.Value);
        }
    }
    private static nint? _ValueBOffset;

    public ref int ValueB
    {
        get
        {
            _ValueBOffset = _ValueBOffset ?? Schema.GetOffset(0x662939E50346FF18);
            return ref _Handle.AsRef<int>(_ValueBOffset!.Value);
        }
    }

}