// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CTestPulseIO__ThreeStringArgs_tImpl : SchemaClass, CTestPulseIO__ThreeStringArgs_t
{
    public CTestPulseIO__ThreeStringArgs_tImpl(nint handle) : base(handle) { }

    private static nint? _StrArg1Offset;

    public string StrArg1
    {
        get
        {
            _StrArg1Offset = _StrArg1Offset ?? Schema.GetOffset(0xA5870B1A0CCD4847);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrArg1Offset!.Value));
        }
        set
        {
            _StrArg1Offset = _StrArg1Offset ?? Schema.GetOffset(0xA5870B1A0CCD4847);
            Schema.SetCUtlString(_Handle, _StrArg1Offset!.Value, value);
        }
    }
    private static nint? _StrArg2Offset;

    public string StrArg2
    {
        get
        {
            _StrArg2Offset = _StrArg2Offset ?? Schema.GetOffset(0xA5870B1A0DCD49DA);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrArg2Offset!.Value));
        }
        set
        {
            _StrArg2Offset = _StrArg2Offset ?? Schema.GetOffset(0xA5870B1A0DCD49DA);
            Schema.SetCUtlString(_Handle, _StrArg2Offset!.Value, value);
        }
    }
    private static nint? _StrArg3Offset;

    public string StrArg3
    {
        get
        {
            _StrArg3Offset = _StrArg3Offset ?? Schema.GetOffset(0xA5870B1A0ECD4B6D);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrArg3Offset!.Value));
        }
        set
        {
            _StrArg3Offset = _StrArg3Offset ?? Schema.GetOffset(0xA5870B1A0ECD4B6D);
            Schema.SetCUtlString(_Handle, _StrArg3Offset!.Value, value);
        }
    }

}