// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CTurnHelperInstanceDataImpl : SchemaClass, CTurnHelperInstanceData
{
    public CTurnHelperInstanceDataImpl(nint handle) : base(handle) { }

    private static nint? _TurnAmountOffset;

    public ref float TurnAmount
    {
        get
        {
            _TurnAmountOffset = _TurnAmountOffset ?? Schema.GetOffset(0xA71FC88E6FAE7436);
            return ref _Handle.AsRef<float>(_TurnAmountOffset!.Value);
        }
    }
    private static nint? _TurnStartTimeOffset;

    public ref float TurnStartTime
    {
        get
        {
            _TurnStartTimeOffset = _TurnStartTimeOffset ?? Schema.GetOffset(0xA71FC88E75897B83);
            return ref _Handle.AsRef<float>(_TurnStartTimeOffset!.Value);
        }
    }
    private static nint? _DurationOffset;

    public ref float Duration
    {
        get
        {
            _DurationOffset = _DurationOffset ?? Schema.GetOffset(0xA71FC88E3D9FF5AD);
            return ref _Handle.AsRef<float>(_DurationOffset!.Value);
        }
    }

}