// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CWayPointHelperInstanceDataImpl : SchemaClass, CWayPointHelperInstanceData
{
    public CWayPointHelperInstanceDataImpl(nint handle) : base(handle) { }

    private static nint? _MovementOffset;

    public ref Vector Movement
    {
        get
        {
            _MovementOffset = _MovementOffset ?? Schema.GetOffset(0x2B35DC8AC72B27FC);
            return ref _Handle.AsRef<Vector>(_MovementOffset!.Value);
        }
    }
    private static nint? _RotationOffset;

    public ref QAngle Rotation
    {
        get
        {
            _RotationOffset = _RotationOffset ?? Schema.GetOffset(0x2B35DC8A379AFF0B);
            return ref _Handle.AsRef<QAngle>(_RotationOffset!.Value);
        }
    }
    private static nint? _WaypointPosWSOffset;

    public ref Vector WaypointPosWS
    {
        get
        {
            _WaypointPosWSOffset = _WaypointPosWSOffset ?? Schema.GetOffset(0x2B35DC8AE6239AAE);
            return ref _Handle.AsRef<Vector>(_WaypointPosWSOffset!.Value);
        }
    }
    private static nint? _StopUpdatingWaypointPosOffset;

    public ref bool StopUpdatingWaypointPos
    {
        get
        {
            _StopUpdatingWaypointPosOffset = _StopUpdatingWaypointPosOffset ?? Schema.GetOffset(0x2B35DC8A6867CCDA);
            return ref _Handle.AsRef<bool>(_StopUpdatingWaypointPosOffset!.Value);
        }
    }

}