// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class DampedPathMotorInstanceData_tImpl : SchemaClass, DampedPathMotorInstanceData_t
{
    public DampedPathMotorInstanceData_tImpl(nint handle) : base(handle) { }

    private static nint? _VelocityOffset;

    public ref Vector Velocity
    {
        get
        {
            _VelocityOffset = _VelocityOffset ?? Schema.GetOffset(0x29D3A01A4344653E);
            return ref _Handle.AsRef<Vector>(_VelocityOffset!.Value);
        }
    }
    private static nint? _AccelerationOffset;

    public ref Vector Acceleration
    {
        get
        {
            _AccelerationOffset = _AccelerationOffset ?? Schema.GetOffset(0x29D3A01A18AF3A91);
            return ref _Handle.AsRef<Vector>(_AccelerationOffset!.Value);
        }
    }
    private static nint? _StoppingOffset;

    public ref bool Stopping
    {
        get
        {
            _StoppingOffset = _StoppingOffset ?? Schema.GetOffset(0x29D3A01AE082F209);
            return ref _Handle.AsRef<bool>(_StoppingOffset!.Value);
        }
    }

}