// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class DestructiblePartDamageRequest_tImpl : SchemaClass, DestructiblePartDamageRequest_t
{
    public DestructiblePartDamageRequest_tImpl(nint handle) : base(handle) { }

    private static nint? _HitGroupOffset;

    public ref HitGroup_t HitGroup
    {
        get
        {
            _HitGroupOffset = _HitGroupOffset ?? Schema.GetOffset(0x5336DA079C854D19);
            return ref _Handle.AsRef<HitGroup_t>(_HitGroupOffset!.Value);
        }
    }
    private static nint? _DamageLevelOffset;

    public ref int DamageLevel
    {
        get
        {
            _DamageLevelOffset = _DamageLevelOffset ?? Schema.GetOffset(0x5336DA07864ED662);
            return ref _Handle.AsRef<int>(_DamageLevelOffset!.Value);
        }
    }
    private static nint? _DesiredHealthOffset;

    public ref ushort DesiredHealth
    {
        get
        {
            _DesiredHealthOffset = _DesiredHealthOffset ?? Schema.GetOffset(0x5336DA07CEA03A9B);
            return ref _Handle.AsRef<ushort>(_DesiredHealthOffset!.Value);
        }
    }
    private static nint? _DestroyFlagsOffset;

    public ref EDestructibleParts_DestroyParameterFlags DestroyFlags
    {
        get
        {
            _DestroyFlagsOffset = _DestroyFlagsOffset ?? Schema.GetOffset(0x5336DA07F89DCF50);
            return ref _Handle.AsRef<EDestructibleParts_DestroyParameterFlags>(_DestroyFlagsOffset!.Value);
        }
    }
    private static nint? _DamageTypeOffset;

    public ref DamageTypes_t DamageType
    {
        get
        {
            _DamageTypeOffset = _DamageTypeOffset ?? Schema.GetOffset(0x5336DA07A9599F54);
            return ref _Handle.AsRef<DamageTypes_t>(_DamageTypeOffset!.Value);
        }
    }
    private static nint? _BreakDamageOffset;

    public ref float BreakDamage
    {
        get
        {
            _BreakDamageOffset = _BreakDamageOffset ?? Schema.GetOffset(0x5336DA07021CFDCF);
            return ref _Handle.AsRef<float>(_BreakDamageOffset!.Value);
        }
    }
    private static nint? _BreakDamageRadiusOffset;

    public ref float BreakDamageRadius
    {
        get
        {
            _BreakDamageRadiusOffset = _BreakDamageRadiusOffset ?? Schema.GetOffset(0x5336DA07C0AA950D);
            return ref _Handle.AsRef<float>(_BreakDamageRadiusOffset!.Value);
        }
    }
    private static nint? _WsBreakDamageOriginOffset;

    public ref Vector WsBreakDamageOrigin
    {
        get
        {
            _WsBreakDamageOriginOffset = _WsBreakDamageOriginOffset ?? Schema.GetOffset(0x5336DA07F20E5215);
            return ref _Handle.AsRef<Vector>(_WsBreakDamageOriginOffset!.Value);
        }
    }
    private static nint? _WsBreakDamageForceOffset;

    public ref Vector WsBreakDamageForce
    {
        get
        {
            _WsBreakDamageForceOffset = _WsBreakDamageForceOffset ?? Schema.GetOffset(0x5336DA074F35F496);
            return ref _Handle.AsRef<Vector>(_WsBreakDamageForceOffset!.Value);
        }
    }

}