// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class GAME_HEADERImpl : SchemaClass, GAME_HEADER
{
    public GAME_HEADERImpl(nint handle) : base(handle) { }

    private static nint? _CommentOffset;

    public string Comment
    {
        get
        {
            _CommentOffset = _CommentOffset ?? Schema.GetOffset(0xA43EA28D88A0B4DF);
            return Schema.GetCUtlString(_Handle.Read<nint>(_CommentOffset!.Value));
        }
        set
        {
            _CommentOffset = _CommentOffset ?? Schema.GetOffset(0xA43EA28D88A0B4DF);
            Schema.SetCUtlString(_Handle, _CommentOffset!.Value, value);
        }
    }
    private static nint? _SpawnGroupCountOffset;

    public ref int SpawnGroupCount
    {
        get
        {
            _SpawnGroupCountOffset = _SpawnGroupCountOffset ?? Schema.GetOffset(0xA43EA28D0187B706);
            return ref _Handle.AsRef<int>(_SpawnGroupCountOffset!.Value);
        }
    }
    private static nint? _LandmarkOffset;

    public string Landmark
    {
        get
        {
            _LandmarkOffset = _LandmarkOffset ?? Schema.GetOffset(0xA43EA28D6B06E99E);
            return Schema.GetCUtlString(_Handle.Read<nint>(_LandmarkOffset!.Value));
        }
        set
        {
            _LandmarkOffset = _LandmarkOffset ?? Schema.GetOffset(0xA43EA28D6B06E99E);
            Schema.SetCUtlString(_Handle, _LandmarkOffset!.Value, value);
        }
    }
    private static nint? _RequiredAddonsOffset;

    public string RequiredAddons
    {
        get
        {
            _RequiredAddonsOffset = _RequiredAddonsOffset ?? Schema.GetOffset(0xA43EA28D4178A27C);
            return Schema.GetCUtlString(_Handle.Read<nint>(_RequiredAddonsOffset!.Value));
        }
        set
        {
            _RequiredAddonsOffset = _RequiredAddonsOffset ?? Schema.GetOffset(0xA43EA28D4178A27C);
            Schema.SetCUtlString(_Handle, _RequiredAddonsOffset!.Value, value);
        }
    }

}