// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class INavObstacleImpl : SchemaClass, INavObstacle
{
    public INavObstacleImpl(nint handle) : base(handle) { }

    private static nint? _IdOffset;

    public ref ulong Id
    {
        get
        {
            _IdOffset = _IdOffset ?? Schema.GetOffset(0xD6337050037544C4);
            return ref _Handle.AsRef<ulong>(_IdOffset!.Value);
        }
    }

}