// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class IPhysAggregateInstanceImpl : IPhysicsBodyListImpl, IPhysAggregateInstance
{
    public IPhysAggregateInstanceImpl(nint handle) : base(handle) { }

    private static nint? _SkeletonOffset;

    public SchemaUntypedField? Skeleton
    {
        get
        {
            _SkeletonOffset = _SkeletonOffset ?? Schema.GetOffset(0xF10205DC44BBF688);
            var ptr = _Handle.Read<nint>(_SkeletonOffset!.Value);
            return ptr.IsValidPtr() ? new SchemaUntypedField(ptr) : null;
        }
    }
    private static nint? _IsAxisAlignedOffset;

    public ref bool IsAxisAligned
    {
        get
        {
            _IsAxisAlignedOffset = _IsAxisAlignedOffset ?? Schema.GetOffset(0xF10205DC24D04088);
            return ref _Handle.AsRef<bool>(_IsAxisAlignedOffset!.Value);
        }
    }

}