// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class levellist_tImpl : SchemaClass, levellist_t
{
    public levellist_tImpl(nint handle) : base(handle) { }

    private static nint? _MapNameOffset;

    public string MapName
    {
        get
        {
            _MapNameOffset = _MapNameOffset ?? Schema.GetOffset(0xE2DE0512CE11EF47);
            return Schema.GetCUtlString(_Handle.Read<nint>(_MapNameOffset!.Value));
        }
        set
        {
            _MapNameOffset = _MapNameOffset ?? Schema.GetOffset(0xE2DE0512CE11EF47);
            Schema.SetCUtlString(_Handle, _MapNameOffset!.Value, value);
        }
    }
    private static nint? _LandmarkNameOffset;

    public string LandmarkName
    {
        get
        {
            _LandmarkNameOffset = _LandmarkNameOffset ?? Schema.GetOffset(0xE2DE05122DEE941D);
            return Schema.GetCUtlString(_Handle.Read<nint>(_LandmarkNameOffset!.Value));
        }
        set
        {
            _LandmarkNameOffset = _LandmarkNameOffset ?? Schema.GetOffset(0xE2DE05122DEE941D);
            Schema.SetCUtlString(_Handle, _LandmarkNameOffset!.Value, value);
        }
    }
    private static nint? _EntLandmarkOffset;

    public ref CHandle<CEntityInstance> EntLandmark
    {
        get
        {
            _EntLandmarkOffset = _EntLandmarkOffset ?? Schema.GetOffset(0xE2DE0512279EC234);
            return ref _Handle.AsRef<CHandle<CEntityInstance>>(_EntLandmarkOffset!.Value);
        }
    }
    private static nint? _LandmarkOriginOffset;

    public ref Vector LandmarkOrigin
    {
        get
        {
            _LandmarkOriginOffset = _LandmarkOriginOffset ?? Schema.GetOffset(0xE2DE0512F1602B9F);
            return ref _Handle.AsRef<Vector>(_LandmarkOriginOffset!.Value);
        }
    }
    private static nint? _LandmarkAnglesOffset;

    public ref QAngle LandmarkAngles
    {
        get
        {
            _LandmarkAnglesOffset = _LandmarkAnglesOffset ?? Schema.GetOffset(0xE2DE0512D96AD741);
            return ref _Handle.AsRef<QAngle>(_LandmarkAnglesOffset!.Value);
        }
    }

}