// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class modifiedconvars_tImpl : SchemaClass, modifiedconvars_t
{
    public modifiedconvars_tImpl(nint handle) : base(handle) { }

    private static nint? _ConvarOffset;

    public string Convar
    {
        get
        {
            _ConvarOffset = _ConvarOffset ?? Schema.GetOffset(0x4A915ED3401607E3);
            return Schema.GetString(_Handle + _ConvarOffset!.Value);
        }
        set
        {
            _ConvarOffset = _ConvarOffset ?? Schema.GetOffset(0x4A915ED3401607E3);
            Schema.SetFixedString(_Handle, _ConvarOffset!.Value, value, 128);
        }
    }
    private static nint? _CurrentValueOffset;

    public string CurrentValue
    {
        get
        {
            _CurrentValueOffset = _CurrentValueOffset ?? Schema.GetOffset(0x4A915ED378B8D6C8);
            return Schema.GetString(_Handle + _CurrentValueOffset!.Value);
        }
        set
        {
            _CurrentValueOffset = _CurrentValueOffset ?? Schema.GetOffset(0x4A915ED378B8D6C8);
            Schema.SetFixedString(_Handle, _CurrentValueOffset!.Value, value, 128);
        }
    }
    private static nint? _OrgValueOffset;

    public string OrgValue
    {
        get
        {
            _OrgValueOffset = _OrgValueOffset ?? Schema.GetOffset(0x4A915ED38A403EC1);
            return Schema.GetString(_Handle + _OrgValueOffset!.Value);
        }
        set
        {
            _OrgValueOffset = _OrgValueOffset ?? Schema.GetOffset(0x4A915ED38A403EC1);
            Schema.SetFixedString(_Handle, _OrgValueOffset!.Value, value, 128);
        }
    }

}