// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class MotionMatchingInstanceDataImpl : SchemaClass, MotionMatchingInstanceData
{
    public MotionMatchingInstanceDataImpl(nint handle) : base(handle) { }

    private static nint? _CurrentSelectionOffset;

    public MotionSelection CurrentSelection
    {
        get
        {
            _CurrentSelectionOffset = _CurrentSelectionOffset ?? Schema.GetOffset(0xC5ACB19BBD40401C);
            return new MotionSelectionImpl(_Handle + _CurrentSelectionOffset!.Value);
        }
    }
    private static nint? _PreviousSelectionOffset;

    public MotionSelection PreviousSelection
    {
        get
        {
            _PreviousSelectionOffset = _PreviousSelectionOffset ?? Schema.GetOffset(0xC5ACB19B363DEA86);
            return new MotionSelectionImpl(_Handle + _PreviousSelectionOffset!.Value);
        }
    }

}