// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class MotionSelectionImpl : SchemaClass, MotionSelection
{
    public MotionSelectionImpl(nint handle) : base(handle) { }

    private static nint? _ConfigIndexOffset;

    public NetVarConfigIndex ConfigIndex
    {
        get
        {
            _ConfigIndexOffset = _ConfigIndexOffset ?? Schema.GetOffset(0x6004D4E3636A4289);
            return new NetVarConfigIndexImpl(_Handle + _ConfigIndexOffset!.Value);
        }
    }
    private static nint? _CycleZeroTimeOffset;

    public SchemaUntypedField CycleZeroTime
    {
        get
        {
            _CycleZeroTimeOffset = _CycleZeroTimeOffset ?? Schema.GetOffset(0x6004D4E340321698);
            return new SchemaUntypedField(_Handle + _CycleZeroTimeOffset!.Value);
        }
    }
    private static nint? _PlaybackSpeedOffset;

    public SchemaUntypedField PlaybackSpeed
    {
        get
        {
            _PlaybackSpeedOffset = _PlaybackSpeedOffset ?? Schema.GetOffset(0x6004D4E3FA2B402D);
            return new SchemaUntypedField(_Handle + _PlaybackSpeedOffset!.Value);
        }
    }
    private static nint? _StartTimeOffset;

    public SchemaUntypedField StartTime
    {
        get
        {
            _StartTimeOffset = _StartTimeOffset ?? Schema.GetOffset(0x6004D4E367FE9DC4);
            return new SchemaUntypedField(_Handle + _StartTimeOffset!.Value);
        }
    }
    private static nint? _SampleOffset;

    public ref int Sample
    {
        get
        {
            _SampleOffset = _SampleOffset ?? Schema.GetOffset(0x6004D4E3BAD1917B);
            return ref _Handle.AsRef<int>(_SampleOffset!.Value);
        }
    }

}