// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class MovementDataImpl : SchemaClass, MovementData
{
    public MovementDataImpl(nint handle) : base(handle) { }

    private static nint? _GoalWayPointPosOffset;

    public ref Vector GoalWayPointPos
    {
        get
        {
            _GoalWayPointPosOffset = _GoalWayPointPosOffset ?? Schema.GetOffset(0x9D77934091B2AC1D);
            return ref _Handle.AsRef<Vector>(_GoalWayPointPosOffset!.Value);
        }
    }
    private static nint? _MoveDirOffset;

    public SchemaUntypedField MoveDir
    {
        get
        {
            _MoveDirOffset = _MoveDirOffset ?? Schema.GetOffset(0x9D7793403C9821BF);
            return new SchemaUntypedField(_Handle + _MoveDirOffset!.Value);
        }
    }
    private static nint? _AccelerationOffset;

    public SchemaUntypedField Acceleration
    {
        get
        {
            _AccelerationOffset = _AccelerationOffset ?? Schema.GetOffset(0x9D77934018AF3A91);
            return new SchemaUntypedField(_Handle + _AccelerationOffset!.Value);
        }
    }
    private static nint? _CurrentMoveSpeedOffset;

    public SchemaUntypedField CurrentMoveSpeed
    {
        get
        {
            _CurrentMoveSpeedOffset = _CurrentMoveSpeedOffset ?? Schema.GetOffset(0x9D7793402DC5BA78);
            return new SchemaUntypedField(_Handle + _CurrentMoveSpeedOffset!.Value);
        }
    }
    private static nint? _TargetMoveSpeedOffset;

    public SchemaUntypedField TargetMoveSpeed
    {
        get
        {
            _TargetMoveSpeedOffset = _TargetMoveSpeedOffset ?? Schema.GetOffset(0x9D7793404E0A57EA);
            return new SchemaUntypedField(_Handle + _TargetMoveSpeedOffset!.Value);
        }
    }
    private static nint? _GoalDistanceOffset;

    public SchemaUntypedField GoalDistance
    {
        get
        {
            _GoalDistanceOffset = _GoalDistanceOffset ?? Schema.GetOffset(0x9D77934093CDFB0B);
            return new SchemaUntypedField(_Handle + _GoalDistanceOffset!.Value);
        }
    }
    private static nint? _BoundaryRadiusOffset;

    public SchemaUntypedField BoundaryRadius
    {
        get
        {
            _BoundaryRadiusOffset = _BoundaryRadiusOffset ?? Schema.GetOffset(0x9D779340EAA8B14F);
            return new SchemaUntypedField(_Handle + _BoundaryRadiusOffset!.Value);
        }
    }
    private static nint? _GoalChangedOffset;

    public ref bool GoalChanged
    {
        get
        {
            _GoalChangedOffset = _GoalChangedOffset ?? Schema.GetOffset(0x9D77934035661DB2);
            return ref _Handle.AsRef<bool>(_GoalChangedOffset!.Value);
        }
    }
    private static nint? _HasPathOffset;

    public SchemaUntypedField HasPath
    {
        get
        {
            _HasPathOffset = _HasPathOffset ?? Schema.GetOffset(0x9D77934055BD9884);
            return new SchemaUntypedField(_Handle + _HasPathOffset!.Value);
        }
    }
    private static nint? _FacingHeadingOffset;

    public SchemaUntypedField FacingHeading
    {
        get
        {
            _FacingHeadingOffset = _FacingHeadingOffset ?? Schema.GetOffset(0x9D779340468A8059);
            return new SchemaUntypedField(_Handle + _FacingHeadingOffset!.Value);
        }
    }
    private static nint? _ManualFacingDirectionOffset;

    public ref Vector ManualFacingDirection
    {
        get
        {
            _ManualFacingDirectionOffset = _ManualFacingDirectionOffset ?? Schema.GetOffset(0x9D779340050A712E);
            return ref _Handle.AsRef<Vector>(_ManualFacingDirectionOffset!.Value);
        }
    }
    private static nint? _ManualFacingTargetOffset;

    public ref Vector ManualFacingTarget
    {
        get
        {
            _ManualFacingTargetOffset = _ManualFacingTargetOffset ?? Schema.GetOffset(0x9D779340BA28DB3C);
            return ref _Handle.AsRef<Vector>(_ManualFacingTargetOffset!.Value);
        }
    }
    private static nint? _FacingModeOffset;

    public SchemaUntypedField FacingMode
    {
        get
        {
            _FacingModeOffset = _FacingModeOffset ?? Schema.GetOffset(0x9D779340E554ACBC);
            return new SchemaUntypedField(_Handle + _FacingModeOffset!.Value);
        }
    }
    private static nint? _ForceFacingOffset;

    public SchemaUntypedField ForceFacing
    {
        get
        {
            _ForceFacingOffset = _ForceFacingOffset ?? Schema.GetOffset(0x9D77934053CE3CEE);
            return new SchemaUntypedField(_Handle + _ForceFacingOffset!.Value);
        }
    }
    private static nint? _ActiveMotorIndexOffset;

    public SchemaUntypedField ActiveMotorIndex
    {
        get
        {
            _ActiveMotorIndexOffset = _ActiveMotorIndexOffset ?? Schema.GetOffset(0x9D7793405A3853D4);
            return new SchemaUntypedField(_Handle + _ActiveMotorIndexOffset!.Value);
        }
    }
    private static nint? _OnGroundOffset;

    public SchemaUntypedField OnGround
    {
        get
        {
            _OnGroundOffset = _OnGroundOffset ?? Schema.GetOffset(0x9D779340E1C4912B);
            return new SchemaUntypedField(_Handle + _OnGroundOffset!.Value);
        }
    }
    private static nint? _FacingPositionOffset;

    public SchemaUntypedField FacingPosition
    {
        get
        {
            _FacingPositionOffset = _FacingPositionOffset ?? Schema.GetOffset(0x9D779340475A3AA8);
            return new SchemaUntypedField(_Handle + _FacingPositionOffset!.Value);
        }
    }
    private static nint? _PrevFacingPositionOffset;

    public ref Vector PrevFacingPosition
    {
        get
        {
            _PrevFacingPositionOffset = _PrevFacingPositionOffset ?? Schema.GetOffset(0x9D779340B6A62BF9);
            return ref _Handle.AsRef<Vector>(_PrevFacingPositionOffset!.Value);
        }
    }

}