// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class NavHull_tImpl : SchemaClass, NavHull_t
{
    public NavHull_tImpl(nint handle) : base(handle) { }

    private static nint? _HullIdxOffset;

    public ref int HullIdx
    {
        get
        {
            _HullIdxOffset = _HullIdxOffset ?? Schema.GetOffset(0x2A185DAA595B303D);
            return ref _Handle.AsRef<int>(_HullIdxOffset!.Value);
        }
    }

}