// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class NetVarConfigIndexImpl : SchemaClass, NetVarConfigIndex
{
    public NetVarConfigIndexImpl(nint handle) : base(handle) { }

    private static nint? _IndexOffset;

    public SchemaUntypedField Index
    {
        get
        {
            _IndexOffset = _IndexOffset ?? Schema.GetOffset(0x51249341491963CB);
            return new SchemaUntypedField(_Handle + _IndexOffset!.Value);
        }
    }

}