// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class PairedSequenceDataImpl : SchemaClass, PairedSequenceData
{
    public PairedSequenceDataImpl(nint handle) : base(handle) { }

    public ISchemaClassFixedArray<PairedSequence_t> PairedSequences
    {
        get => new SchemaClassFixedArray<PairedSequence_t>(_Handle, 0x8EAA5275E703C552, 8, 32, 8);
    }

}