// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class PhysObjectHeader_tImpl : SchemaClass, PhysObjectHeader_t
{
    public PhysObjectHeader_tImpl(nint handle) : base(handle) { }

    private static nint? _TypeOffset;

    public ref PhysInterfaceId_t Type
    {
        get
        {
            _TypeOffset = _TypeOffset ?? Schema.GetOffset(0xBB54A9005127F14D);
            return ref _Handle.AsRef<PhysInterfaceId_t>(_TypeOffset!.Value);
        }
    }
    private static nint? _EntityOffset;

    public ref CHandle<CBaseEntity> Entity
    {
        get
        {
            _EntityOffset = _EntityOffset ?? Schema.GetOffset(0xBB54A90025B27FD0);
            return ref _Handle.AsRef<CHandle<CBaseEntity>>(_EntityOffset!.Value);
        }
    }
    private static nint? _FieldNameOffset;

    public string FieldName
    {
        get
        {
            _FieldNameOffset = _FieldNameOffset ?? Schema.GetOffset(0xBB54A9007D0E6744);
            return Schema.GetString(_Handle.Read<nint>(_FieldNameOffset!.Value));
        }
        set
        {
            _FieldNameOffset = _FieldNameOffset ?? Schema.GetOffset(0xBB54A9007D0E6744);
            Schema.SetString(_Handle, _FieldNameOffset!.Value, value);
        }
    }
    private static nint? _ObjectsOffset;

    public ref int Objects
    {
        get
        {
            _ObjectsOffset = _ObjectsOffset ?? Schema.GetOffset(0xBB54A900594B2767);
            return ref _Handle.AsRef<int>(_ObjectsOffset!.Value);
        }
    }
    private static nint? _ModelNameOffset;

    public string ModelName
    {
        get
        {
            _ModelNameOffset = _ModelNameOffset ?? Schema.GetOffset(0xBB54A9004A8A4B01);
            return Schema.GetString(_Handle.Read<nint>(_ModelNameOffset!.Value));
        }
        set
        {
            _ModelNameOffset = _ModelNameOffset ?? Schema.GetOffset(0xBB54A9004A8A4B01);
            Schema.SetString(_Handle, _ModelNameOffset!.Value, value);
        }
    }
    private static nint? _BboxOffset;

    public AABB_t Bbox
    {
        get
        {
            _BboxOffset = _BboxOffset ?? Schema.GetOffset(0xBB54A90094AAAED2);
            return new AABB_tImpl(_Handle + _BboxOffset!.Value);
        }
    }
    private static nint? _SphereOffset;

    public physics_save_sphere_t Sphere
    {
        get
        {
            _SphereOffset = _SphereOffset ?? Schema.GetOffset(0xBB54A900AFD98518);
            return new physics_save_sphere_tImpl(_Handle + _SphereOffset!.Value);
        }
    }
    private static nint? _CollideOffset;

    public ref int Collide
    {
        get
        {
            _CollideOffset = _CollideOffset ?? Schema.GetOffset(0xBB54A900239916A2);
            return ref _Handle.AsRef<int>(_CollideOffset!.Value);
        }
    }

}