// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class PhysBlockHeader_tImpl : SchemaClass, PhysBlockHeader_t
{
    public PhysBlockHeader_tImpl(nint handle) : base(handle) { }

    private static nint? _SavedOffset;

    public ref int Saved
    {
        get
        {
            _SavedOffset = _SavedOffset ?? Schema.GetOffset(0x92435DA85698EE00);
            return ref _Handle.AsRef<int>(_SavedOffset!.Value);
        }
    }
    private static nint? _WorldObjectOffset;

    public ref ulong WorldObject
    {
        get
        {
            _WorldObjectOffset = _WorldObjectOffset ?? Schema.GetOffset(0x92435DA8DFF44742);
            return ref _Handle.AsRef<ulong>(_WorldObjectOffset!.Value);
        }
    }

}