// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class PlayerInputMotorInstanceData_tImpl : SchemaClass, PlayerInputMotorInstanceData_t
{
    public PlayerInputMotorInstanceData_tImpl(nint handle) : base(handle) { }

    private static nint? _InputVectorWSOffset;

    public ref Vector InputVectorWS
    {
        get
        {
            _InputVectorWSOffset = _InputVectorWSOffset ?? Schema.GetOffset(0x6A8D4939041B4416);
            return ref _Handle.AsRef<Vector>(_InputVectorWSOffset!.Value);
        }
    }
    private static nint? _VelocityWSOffset;

    public ref Vector VelocityWS
    {
        get
        {
            _VelocityWSOffset = _VelocityWSOffset ?? Schema.GetOffset(0x6A8D49395D3351C8);
            return ref _Handle.AsRef<Vector>(_VelocityWSOffset!.Value);
        }
    }
    private static nint? _AccelerationWSOffset;

    public ref Vector AccelerationWS
    {
        get
        {
            _AccelerationWSOffset = _AccelerationWSOffset ?? Schema.GetOffset(0x6A8D4939AA6DC133);
            return ref _Handle.AsRef<Vector>(_AccelerationWSOffset!.Value);
        }
    }

}