// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class PrecipitationFilter_tImpl : SchemaClass, PrecipitationFilter_t
{
    public PrecipitationFilter_tImpl(nint handle) : base(handle) { }

    private static nint? _MaxRadiusOffset;

    public ref float MaxRadius
    {
        get
        {
            _MaxRadiusOffset = _MaxRadiusOffset ?? Schema.GetOffset(0x3570A38989E61C15);
            return ref _Handle.AsRef<float>(_MaxRadiusOffset!.Value);
        }
    }

}