// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class SamplerVoice_tImpl : SchemaClass, SamplerVoice_t
{
    public SamplerVoice_tImpl(nint handle) : base(handle) { }

    private static nint? _NoteNumOffset;

    public ref byte NoteNum
    {
        get
        {
            _NoteNumOffset = _NoteNumOffset ?? Schema.GetOffset(0x406618906990C347);
            return ref _Handle.AsRef<byte>(_NoteNumOffset!.Value);
        }
    }

}