// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class SAVE_HEADERImpl : SchemaClass, SAVE_HEADER
{
    public SAVE_HEADERImpl(nint handle) : base(handle) { }

    private static nint? _SaveIdOffset;

    public ref int SaveId
    {
        get
        {
            _SaveIdOffset = _SaveIdOffset ?? Schema.GetOffset(0xB5CD27F0F8DF1435);
            return ref _Handle.AsRef<int>(_SaveIdOffset!.Value);
        }
    }
    private static nint? _VersionOffset;

    public ref int Version
    {
        get
        {
            _VersionOffset = _VersionOffset ?? Schema.GetOffset(0xB5CD27F004D046B7);
            return ref _Handle.AsRef<int>(_VersionOffset!.Value);
        }
    }
    private static nint? _ConnectionCountOffset;

    public ref int ConnectionCount
    {
        get
        {
            _ConnectionCountOffset = _ConnectionCountOffset ?? Schema.GetOffset(0xB5CD27F0B19B756C);
            return ref _Handle.AsRef<int>(_ConnectionCountOffset!.Value);
        }
    }
    private static nint? _MapVersionOffset;

    public ref int MapVersion
    {
        get
        {
            _MapVersionOffset = _MapVersionOffset ?? Schema.GetOffset(0xB5CD27F0150AD79F);
            return ref _Handle.AsRef<int>(_MapVersionOffset!.Value);
        }
    }
    private static nint? _SpawnGroupNameOffset;

    public string SpawnGroupName
    {
        get
        {
            _SpawnGroupNameOffset = _SpawnGroupNameOffset ?? Schema.GetOffset(0xB5CD27F0B2281EA3);
            return Schema.GetCUtlString(_Handle.Read<nint>(_SpawnGroupNameOffset!.Value));
        }
        set
        {
            _SpawnGroupNameOffset = _SpawnGroupNameOffset ?? Schema.GetOffset(0xB5CD27F0B2281EA3);
            Schema.SetCUtlString(_Handle, _SpawnGroupNameOffset!.Value, value);
        }
    }
    private static nint? _WorldOffsetOffset;

    public ref matrix3x4_t WorldOffset
    {
        get
        {
            _WorldOffsetOffset = _WorldOffsetOffset ?? Schema.GetOffset(0xB5CD27F083450700);
            return ref _Handle.AsRef<matrix3x4_t>(_WorldOffsetOffset!.Value);
        }
    }
    private static nint? _SaveTimeOffset;

    public ref float SaveTime
    {
        get
        {
            _SaveTimeOffset = _SaveTimeOffset ?? Schema.GetOffset(0xB5CD27F00FC8CABB);
            return ref _Handle.AsRef<float>(_SaveTimeOffset!.Value);
        }
    }

}