// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class SceneOpportunityActor_tImpl : SchemaClass, SceneOpportunityActor_t
{
    public SceneOpportunityActor_tImpl(nint handle) : base(handle) { }

    private static nint? _ActorOffset;

    public ref CHandle<CBaseModelEntity> Actor
    {
        get
        {
            _ActorOffset = _ActorOffset ?? Schema.GetOffset(0x5320DA26C0FFC404);
            return ref _Handle.AsRef<CHandle<CBaseModelEntity>>(_ActorOffset!.Value);
        }
    }
    private static nint? _DynamicActorOffset;

    public ref bool DynamicActor
    {
        get
        {
            _DynamicActorOffset = _DynamicActorOffset ?? Schema.GetOffset(0x5320DA2677B40F17);
            return ref _Handle.AsRef<bool>(_DynamicActorOffset!.Value);
        }
    }
    private static nint? _AnchorOffset;

    public ref bool Anchor
    {
        get
        {
            _AnchorOffset = _AnchorOffset ?? Schema.GetOffset(0x5320DA26D0E53414);
            return ref _Handle.AsRef<bool>(_AnchorOffset!.Value);
        }
    }
    private static nint? _StrActorNameOffset;

    public string StrActorName
    {
        get
        {
            _StrActorNameOffset = _StrActorNameOffset ?? Schema.GetOffset(0x5320DA26EC1D987A);
            return Schema.GetString(_Handle.Read<nint>(_StrActorNameOffset!.Value));
        }
        set
        {
            _StrActorNameOffset = _StrActorNameOffset ?? Schema.GetOffset(0x5320DA26EC1D987A);
            Schema.SetString(_Handle, _StrActorNameOffset!.Value, value);
        }
    }
    private static nint? _StrEntityNameOffset;

    public string StrEntityName
    {
        get
        {
            _StrEntityNameOffset = _StrEntityNameOffset ?? Schema.GetOffset(0x5320DA2676CEFEF0);
            return Schema.GetString(_Handle.Read<nint>(_StrEntityNameOffset!.Value));
        }
        set
        {
            _StrEntityNameOffset = _StrEntityNameOffset ?? Schema.GetOffset(0x5320DA2676CEFEF0);
            Schema.SetString(_Handle, _StrEntityNameOffset!.Value, value);
        }
    }
    private static nint? _InterestTagsOffset;

    public SceneInterestTags_t InterestTags
    {
        get
        {
            _InterestTagsOffset = _InterestTagsOffset ?? Schema.GetOffset(0x5320DA265D952E86);
            return new SceneInterestTags_tImpl(_Handle + _InterestTagsOffset!.Value);
        }
    }

}