// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class SceneInterestTags_tImpl : SchemaClass, SceneInterestTags_t
{
    public SceneInterestTags_tImpl(nint handle) : base(handle) { }

    private static nint? _TagsOffset;

    public ref CUtlVector<CUtlString> Tags
    {
        get
        {
            _TagsOffset = _TagsOffset ?? Schema.GetOffset(0xF39A296331C5D020);
            return ref _Handle.AsRef<CUtlVector<CUtlString>>(_TagsOffset!.Value);
        }
    }

}