// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class SceneRequestTargetMapPair_tImpl : SchemaClass, SceneRequestTargetMapPair_t
{
    public SceneRequestTargetMapPair_tImpl(nint handle) : base(handle) { }

    private static nint? _ActorNameOffset;

    public string ActorName
    {
        get
        {
            _ActorNameOffset = _ActorNameOffset ?? Schema.GetOffset(0xEE4298563E51AE81);
            return Schema.GetString(_Handle.Read<nint>(_ActorNameOffset!.Value));
        }
        set
        {
            _ActorNameOffset = _ActorNameOffset ?? Schema.GetOffset(0xEE4298563E51AE81);
            Schema.SetString(_Handle, _ActorNameOffset!.Value, value);
        }
    }
    private static nint? _TargetNameOffset;

    public string TargetName
    {
        get
        {
            _TargetNameOffset = _TargetNameOffset ?? Schema.GetOffset(0xEE429856C58FE46B);
            return Schema.GetString(_Handle.Read<nint>(_TargetNameOffset!.Value));
        }
        set
        {
            _TargetNameOffset = _TargetNameOffset ?? Schema.GetOffset(0xEE429856C58FE46B);
            Schema.SetString(_Handle, _TargetNameOffset!.Value, value);
        }
    }

}