// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class SelectorInstanceData_tImpl : SchemaClass, SelectorInstanceData_t
{
    public SelectorInstanceData_tImpl(nint handle) : base(handle) { }

    private static nint? _WeightsOffset;

    public SchemaUntypedField Weights
    {
        get
        {
            _WeightsOffset = _WeightsOffset ?? Schema.GetOffset(0x9F2CBD2C77B2F91E);
            return new SchemaUntypedField(_Handle + _WeightsOffset!.Value);
        }
    }
    private static nint? _CurrentIndexStartTimeOffset;

    public SchemaUntypedField CurrentIndexStartTime
    {
        get
        {
            _CurrentIndexStartTimeOffset = _CurrentIndexStartTimeOffset ?? Schema.GetOffset(0x9F2CBD2C31724957);
            return new SchemaUntypedField(_Handle + _CurrentIndexStartTimeOffset!.Value);
        }
    }
    private static nint? _CurrentIndexOffset;

    public ref int CurrentIndex
    {
        get
        {
            _CurrentIndexOffset = _CurrentIndexOffset ?? Schema.GetOffset(0x9F2CBD2C883AA9CE);
            return ref _Handle.AsRef<int>(_CurrentIndexOffset!.Value);
        }
    }
    private static nint? _PreviousIndexOffset;

    public ref int PreviousIndex
    {
        get
        {
            _PreviousIndexOffset = _PreviousIndexOffset ?? Schema.GetOffset(0x9F2CBD2CBF6FC124);
            return ref _Handle.AsRef<int>(_PreviousIndexOffset!.Value);
        }
    }

}