// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class SlopeDataImpl : SchemaClass, SlopeData
{
    public SlopeDataImpl(nint handle) : base(handle) { }

    private static nint? _SlopeNormalOffset;

    public ref Vector SlopeNormal
    {
        get
        {
            _SlopeNormalOffset = _SlopeNormalOffset ?? Schema.GetOffset(0x7F2D2390294F61EF);
            return ref _Handle.AsRef<Vector>(_SlopeNormalOffset!.Value);
        }
    }

}