// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class SoundCommand_tImpl : SchemaClass, SoundCommand_t
{
    public SoundCommand_tImpl(nint handle) : base(handle) { }

    private static nint? _TimeOffset;

    public ref float Time
    {
        get
        {
            _TimeOffset = _TimeOffset ?? Schema.GetOffset(0xD141C5B61D93C884);
            return ref _Handle.AsRef<float>(_TimeOffset!.Value);
        }
    }
    private static nint? _DeltaTimeOffset;

    public ref float DeltaTime
    {
        get
        {
            _DeltaTimeOffset = _DeltaTimeOffset ?? Schema.GetOffset(0xD141C5B6198A8E98);
            return ref _Handle.AsRef<float>(_DeltaTimeOffset!.Value);
        }
    }
    private static nint? _CommandOffset;

    public ref soundcommands_t Command
    {
        get
        {
            _CommandOffset = _CommandOffset ?? Schema.GetOffset(0xD141C5B66D7F00D2);
            return ref _Handle.AsRef<soundcommands_t>(_CommandOffset!.Value);
        }
    }
    private static nint? _ValueOffset;

    public ref float Value
    {
        get
        {
            _ValueOffset = _ValueOffset ?? Schema.GetOffset(0xD141C5B66B99AEEA);
            return ref _Handle.AsRef<float>(_ValueOffset!.Value);
        }
    }

}