// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class SPAWNGROUP_HEADERImpl : SchemaClass, SPAWNGROUP_HEADER
{
    public SPAWNGROUP_HEADERImpl(nint handle) : base(handle) { }

    private static nint? _GroupNameOffset;

    public string GroupName
    {
        get
        {
            _GroupNameOffset = _GroupNameOffset ?? Schema.GetOffset(0x2E01B7B958F7B716);
            return Schema.GetCUtlString(_Handle.Read<nint>(_GroupNameOffset!.Value));
        }
        set
        {
            _GroupNameOffset = _GroupNameOffset ?? Schema.GetOffset(0x2E01B7B958F7B716);
            Schema.SetCUtlString(_Handle, _GroupNameOffset!.Value, value);
        }
    }
    private static nint? _EntityLumpNameOffset;

    public string EntityLumpName
    {
        get
        {
            _EntityLumpNameOffset = _EntityLumpNameOffset ?? Schema.GetOffset(0x2E01B7B9DE736A98);
            return Schema.GetCUtlString(_Handle.Read<nint>(_EntityLumpNameOffset!.Value));
        }
        set
        {
            _EntityLumpNameOffset = _EntityLumpNameOffset ?? Schema.GetOffset(0x2E01B7B9DE736A98);
            Schema.SetCUtlString(_Handle, _EntityLumpNameOffset!.Value, value);
        }
    }
    private static nint? _WorldOffsetOffset;

    public ref matrix3x4_t WorldOffset
    {
        get
        {
            _WorldOffsetOffset = _WorldOffsetOffset ?? Schema.GetOffset(0x2E01B7B983450700);
            return ref _Handle.AsRef<matrix3x4_t>(_WorldOffsetOffset!.Value);
        }
    }
    private static nint? _ClientSpawnGroupOffset;

    public ref bool ClientSpawnGroup
    {
        get
        {
            _ClientSpawnGroupOffset = _ClientSpawnGroupOffset ?? Schema.GetOffset(0x2E01B7B9E83030E4);
            return ref _Handle.AsRef<bool>(_ClientSpawnGroupOffset!.Value);
        }
    }
    private static nint? _SuppressAllEntitiesOffset;

    public ref bool SuppressAllEntities
    {
        get
        {
            _SuppressAllEntitiesOffset = _SuppressAllEntitiesOffset ?? Schema.GetOffset(0x2E01B7B93755331A);
            return ref _Handle.AsRef<bool>(_SuppressAllEntitiesOffset!.Value);
        }
    }

}