// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class TestComponent_tImpl : SchemaClass, TestComponent_t
{
    public TestComponent_tImpl(nint handle) : base(handle) { }

    private static nint? _ComponentDataOffset;

    public string ComponentData
    {
        get
        {
            _ComponentDataOffset = _ComponentDataOffset ?? Schema.GetOffset(0xF9BE36BBF07BDB48);
            return Schema.GetCUtlString(_Handle.Read<nint>(_ComponentDataOffset!.Value));
        }
        set
        {
            _ComponentDataOffset = _ComponentDataOffset ?? Schema.GetOffset(0xF9BE36BBF07BDB48);
            Schema.SetCUtlString(_Handle, _ComponentDataOffset!.Value, value);
        }
    }

}