// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class VelocityZone_tImpl : SchemaClass, VelocityZone_t
{
    public VelocityZone_tImpl(nint handle) : base(handle) { }

    private static nint? _MaxVelOffset;

    public ref byte MaxVel
    {
        get
        {
            _MaxVelOffset = _MaxVelOffset ?? Schema.GetOffset(0xEA1490275CA763E8);
            return ref _Handle.AsRef<byte>(_MaxVelOffset!.Value);
        }
    }
    private static nint? _NextSelectionOffset;

    public ref byte NextSelection
    {
        get
        {
            _NextSelectionOffset = _NextSelectionOffset ?? Schema.GetOffset(0xEA149027333B01B2);
            return ref _Handle.AsRef<byte>(_NextSelectionOffset!.Value);
        }
    }
    private static nint? _NumSamplesOffset;

    public ref byte NumSamples
    {
        get
        {
            _NumSamplesOffset = _NumSamplesOffset ?? Schema.GetOffset(0xEA149027D602013A);
            return ref _Handle.AsRef<byte>(_NumSamplesOffset!.Value);
        }
    }
    public ISchemaFixedArray<uint> Samples
    {
        get => new SchemaFixedArray<uint>(_Handle, 0xEA149027730A51EA, 4, 4, 4);
    }

}